### ISSUE TITLE
TiffFile.save() cannot write ExifTag or GPSTag metadata

### ISSUE THREAD

**Issue by CliffDellamano** [cgohlke/tifffile#1]
As part of my work, I am attempting to open a single-page .TIF, perform some calculations based on the contents of the image array, modify the array accordingly, and then save the array back to a .TIF. However, I need to do this in a way that preserves **all** valid metadata from the original image (valid meaning that tags such as `DateTime` would be ignored). 

This is easy enough with standard tags -- simply extract them from the original `TiffTags` object, store them in a list of `(code, dtype, count, value)` tuples, and pass them to the `extratags` argument of `save()`. However, this approach fails when attempting to write both `ExifTag` and `GPSTag` IFD groups.

Is there a relatively simple method, with the current library, to bypass this limitation? I thought I might be able to recursively traverse the `TiffTags` dictionary, pull the individual tags out of their groups, and append them on to the full `extratags` list, but then they no longer belong to an IFD group.

I am not sure if this is the best place to pose this issue, so please feel free to close if so.

**Comment by cgohlke** [comment]
Writing EXIF or GPS IFDs is not supported and out of the scope as documented:
```
    TiffWriter's main purpose is saving nD numpy array's as TIFF,
    not to create any possible TIFF format. Specifically, SubIFDs, ExifIFD,
    and GPSIFD tags are not supported.
```

You might be able to directly change the image data in the TIFF file using memory mapping if the image data is stored contiguously, uncompressed, un-predicted, etc.

**Comment by CliffDellamano** [comment]
I see; I’m not sure if the memory map approach would work, as the data changes size as a result of the computation (packed 12-bit to float32). Assuming I could implement this functionality within TiffWriter, would you be open to receiving PRs?
