### ISSUE TITLE
opening .SCN file returns compressed image

### ISSUE THREAD

**Issue by asasama12** [cgohlke/tifffile#10]
I am attempting to open .scn files using tifffile in python 3.7.7

I have installed:
 tifffile 2020.6.3 
imagecodecs 2020.5.30
numpy 1.16.6

When I read in the .scn file it appears to have automatically compressed it to some degree.  When this file is opened in ImageScope, it correctly shows the native image shape as (31090, 15884, 3) but tifffile reads it at  (12776, 5689, 3).  The .scn file is in a pyramidal format, but none of the pyramid levels correlate to the shape that tifffile read.  

Code: 
import tifffile
file = '/home/~~~~~~.scn'
image = tifffile.imread(file)
image.shape

Is there a way to force tifffile to read the image at native resolution?

**Comment by cgohlke** [comment]
Tifffile does not currently have a dedicated reader for SCN metadata/series. I don't have the specifications or access to many SCN files for testing. What happens is that tifffile.imread uses the generic reader for series, which is likely not what you want. Instead, read a specific page from the file (e.g. `imread(filename, key=1`) or better inspect the pages for the largest image before reading: `for page in tifffile.TiffFile(filename).pages: print(page.shape)`

**Comment by asasama12** [comment]
That worked perfectly, Thank you so much Christoph!

![Screenshot from 2020-06-09 13-46-53](https://user-images.githubusercontent.com/41748563/84187516-c576df00-aa57-11ea-9b67-5fe72d383fa0.png)
