### ISSUE TITLE
Implement qpi_metadata property of TiffFile

### ISSUE THREAD

**Issue by afrendeiro** [cgohlke/tifffile#101]
I realized that while QPTIFF files (QPI) are supported, and there is a `is_qpi` flag, the corresponding `qpi_metadata` does not exist.

I would be great if it would be possible to easily access the metadata of these files.

**Comment by cgohlke** [comment]
I think the reason that there is no `TiffFile.qpi_metadata` function is that, unlike many other formats, QPI files have no global metadata. Instead, each page in the file has it's own XML metadata in the `ImageDescription` tag. I'm not sure how to consolidate those, or if it even makes sense (?).

**Comment by afrendeiro** [comment]
I see, I wasn't aware. It makes sense there is no metadata at the file level - not sure consolidating it from the various pages makes sense either.
Thank you so much for developing such essential software.
