### ISSUE TITLE
TypeError using imagej_metadata

### ISSUE THREAD

**Issue by Slagt** [cgohlke/tifffile#103]
When opening a file made with Fiji, I get the following error although the data are correctly loaded:
> TiffPage 0: TypeError: read_bytes() missing 3 required positional arguments: 'dtype', 'count', and 'offsetsize'

The traceback yields this:
> File "/opt/homebrew/lib/python3.9/site-packages/tifffile/tifffile.py", line 3099, in __init__
    self.pages = TiffPages(self)
> File "/opt/homebrew/lib/python3.9/site-packages/tifffile/tifffile.py", line 5269, in __init__
    page = TiffPage(self.parent, index=pageindex)
> File "/opt/homebrew/lib/python3.9/site-packages/tifffile/tifffile.py", line 5893, in __init__
    tags[50839].value = imagej_metadata(
> File "/opt/homebrew/lib/python3.9/site-packages/tifffile/tifffile.py", line 14845, in imagej_metadata
    values.append(func(data[pos:pos1], byteorder))
> File "/opt/homebrew/lib/python3.9/site-packages/tifffile/tifffile.py", line 13960, in read_bytes

The method `read_bytes` is called in `imagej_metadata` without the last three arguments.

Minimum working example (use enclosed file: [triple-sphere.zip](https://github.com/cgohlke/tifffile/files/7453926/triple-sphere.zip)):
```python3
import tifffile

with tifffile.TiffFile("/foo/bar/data.tif") as tf:
    data = tf.asarray()
```

Expected output:
I have not notice anything wrong except the error being displayed. The data are correctly loaded in memory and returned by `tf.asarray`. 

Versions:
- `tifffile`: 2021.10.12
- `python`: 3.9.7

**Comment by cgohlke** [comment]
Thank you for raising the issue and providing a test file. `_read_bytes` is the wrong fallback function. Should be `_string`. Anyway, tifffile does not currently handle the ImageJ `prop` metadata type. I'm going to fix both in the next version.

**Comment by Slagt** [comment]
Sorry that's my mistake. I renamed the method `read_bytes` to `_read_bytes` and created a new method `read_bytes` to display the stack trace and find where the problem was coming from. Of course, the error is still present without my modifications. Sorry for the confusion I have edited the original message.

**Comment by cgohlke** [comment]
Fixed in v2021.11.2

**Comment by psratl** [comment]
I have this exact problem when I save a 16-bit image file (from a PCOEdge camera) after normalizing it using FIJI and saving as 16-bit. I am trying to use the normalized, saved images in TrackPy v0.5.0. Anaconda Navigator shows version tifffile v2021.4.8. 
I understand that I want a later version, but I seem unable to update to the latest version of tifffile! From the conda prompt, I type: 
conda install -c conda-forge tifffile   or 
conda install -c conda-forge/label/main tifffile 
Installation seems to go OK, but Anaconda Navigator still shows v2021.4.8 
I'm new to Python, Anaconda, and TrackPy., so please forgive me if I have done something silly. I'm just trying to get through a TrackPy session with our own images rather than the test data sets.

**Comment by cgohlke** [comment]
Did you try [`conda update`](https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/manage-pkgs.html#updating-packages)?

**Comment by psratl** [comment]
Thank you. Yes, I tried conda update conda. Old version is still there. Maybe some other package insists on the old version? Is that what Anaconda Navigator does—keep things compatible? I have asked some students to look into it, but maybe I will try to run the code in Spyder.

**Comment by psratl** [comment]
I had previously tried a conda update conda command. 

Check out this conda update tifffile result:
(base) C:\Users\*****>conda update tifffile
Collecting package metadata (current_repodata.json): done
Solving environment: |
Updating tifffile is constricted by
anaconda -> requires tifffile==2021.4.8=pyhd3eb1b0_2
If you are sure you want an update of your package either try `conda update --all` or install a specific version of the package you want using `conda install <pkg>=<version>`
# All requested packages already installed.

Here's a guy with a similar problem, and it suggests perhaps I need square images. 
https://github.com/HenriquesLab/ZeroCostDL4Mic/issues/86
