### ISSUE TITLE
Append to existing Tif file

### ISSUE THREAD

**Issue by Engwer** [cgohlke/tifffile#104]
Hello,

I have a somewhat similar problem to #28. I want to read consecutive timepoints of image data from single files, compile them into a multi-channel stack and append them to an existing tif file without having to store the full image in the memory or reading it at the end again.

The problem that I have is highlighted by the code below:

```Python
import numpy as np
import tifffile

fname = "image.tif"

for i in range(10):
    im = np.random.random((4, 512, 512)) * (2**16 - 1)
    im = im.astype(np.uint16)
    tifffile.imwrite(
        fname,
        im,
        append=True,
        contiguous=True,
    )

tif = tifffile.TiffFile(fname)

image = tif.asarray()
print(image.shape) # (4, 512, 512)

print(len(tif.series)) # 10
image = np.array([series.asarray() for series in tif.series])
print(image.shape) # (10, 4, 512, 512)

print(len(tif.pages)) # 10
image = np.array([page.asarray() for page in tif.pages])
print(image.shape) # (10, 4, 512, 512)
```

In summary: I am able to append image stacks to an existing tif file. However, when trying to read the final tif file, the image cannot be retrieved directly, i.e. only a single series is recognized. Moreover, ImageJ throws an error that it cannot open the image as well:

```
(Fiji Is Just) ImageJ 2.1.0/1.53c; Java 1.8.0_172 [64-bit]; Windows 10 10.0; 131MB of 98092MB (<1%)
 
java.lang.IllegalArgumentException: Unknown stack type
	at ij.ImageStack.getProcessor(ImageStack.java:289)
	at ij.ImagePlus.setStack(ImagePlus.java:742)
	at ij.ImagePlus.<init>(ImagePlus.java:158)
	at ij.io.Opener.openTiffStack(Opener.java:809)
	at ij.io.Opener.openTiff2(Opener.java:1034)
	at ij.io.Opener.openTiff(Opener.java:842)
	at ij.io.Opener.openImage(Opener.java:317)
	at ij.io.Opener.openImage(Opener.java:243)
	at ij.io.Opener.open(Opener.java:109)
	at ij.io.Opener.openAndAddToRecent(Opener.java:292)
	at ij.plugin.DragAndDrop.openFile(DragAndDrop.java:194)
	at ij.plugin.DragAndDrop.run(DragAndDrop.java:160)
	at java.lang.Thread.run(Thread.java:748)
```

Any help is appreciated

## More information:

* TiffFile 2021.4.8
* Numpy 1.18.3

**Comment by cgohlke** [comment]
Several issues: 

`tifffile.imwrite` writes a new series to the file.

`contiguous=True` has no effect when appending to a file with imwrite.

You may want to disable writing metadata identifying the series with `metadata=None`.

Appending to a file does not scale well with the number of pages existing in the file.

Arrays of shape `(4, 512, 512)` are stored as planar RGBA. Use `photometric='minisblack'` to save the array as 4 pages of grayscale images instead.

I don't think ImageJ can handle stacks of planar uint16 RGBA images.

**Comment by Engwer** [comment]
Thanks for your help. I was actually never aware of the difference between `tifffile.imwrite`and `tifffile.imsave`. With the latter one, the code already works. And indeed, adding `photometric='minisblack'` saves it correctly as grayscale images which makes it compatible with IJ.

Is it possible, then to add metadata to a tif file, after all the pages have been saved without having to read and re-write the whole file?

**Comment by cgohlke** [comment]
> difference between `tifffile.imwrite` and `tifffile.imsave`

`tifffile.imwrite` and `tifffile.imsave` are the same function. You probably meant to compare those to the class functions `tifffile.TiffWriter.write/save`.

> Is it possible, then to add metadata to a tif file, after all the pages have been saved without having to read and re-write the whole file?

That depends. You can overwrite the value of existing tags. There's a convenience function [`tiffcomment`](https://github.com/cgohlke/tifffile/blob/0eadc15ca044429f8af70a59ae9cc5a3d54b18e2/tifffile/tifffile.py#L17801-L17814) to overwrite the ImageDescription tag of the first page, which is used to store OME-XML or ImageJ metadata.

If you know the size/shape of the image data you want to write to a ImageJ compatible file, create an empty file with ImageJ metadata first and then write directly to the memory-mapped array. Similar to https://github.com/cgohlke/tifffile/blob/0eadc15ca044429f8af70a59ae9cc5a3d54b18e2/tifffile/tifffile.py#L558-L568
