### ISSUE TITLE
Slicing multi-page tiff on a different axis

### ISSUE THREAD

**Issue by manoaman** [cgohlke/tifffile#105]
Hello,

I have a multi-page tiff stack which is a representation of a 3D image, and an each slice is stacked on a y-axis.  I would like to re-slice this multi-page tiff on a z-axis instead, and eventually split into each slice.  Does tifffile supports such a feature?  I would appreciate if you could advise me.

Thank you,
-m

**Comment by cgohlke** [comment]
Do you mean something like this?
```Python
yzx = tifffile.imread('yzx.tif')
zyx = numpy.moveaxis(yzx, 1, 0)
tifffile.imwrite('zyx.tif', zyx)
```
Does the stack fit into memory? Does the TIFF file need to be written in a certain format? Do any metadata need to be retained?

**Comment by manoaman** [comment]
Hi @cgohlke 

Thank you for your feedbacks and a solution.  A tif is 245GB so it's a bet tough to run on 32GB RAM machine.  An output can remain in TIFF format.  Although, I'm curious if the original file is a NRRD format instead of multi-page TIFF, I wonder if I could use the same operation.  

Thank you for your knowledge!
-m

**Comment by cgohlke** [comment]
If the original file is a uncompressed NRRD format, you can probably memory map the image data in the file to a numpy array. Then you could write to a memory mapped TIFF file, e.g.:

https://github.com/cgohlke/tifffile/blob/0eadc15ca044429f8af70a59ae9cc5a3d54b18e2/tifffile/tifffile.py#L558-L568

It might be better to iterate through the frames of the TIFF file and save them (transposed) to a chunked HDF5 or zarr file instead of a TIFF file.

**Comment by manoaman** [comment]
@cgohlke how do I split memmap image to a tiff sequence?  (splitting tiff files?)  Sorry, I have not used HDF5 nor zarr formats.  Are they easy to handle for splitting multi-page tiffs?

```
zyx_image = np.moveaxis(memmap_image,1,0)
// zyx_image split with tifffile ?
```

**Comment by manoaman** [comment]
@cgohlke sorry to get back to you late.  It took sometime to process and verify the axis swaps.  One problem from the following numpy conversion is that the image on a Y-axis is flipped up side down.  Could this be it?

```
yzx = tifffile.imread('yzx.tif')
zyx = numpy.moveaxis(yzx, 1, 0)
numpy.flip(zyx, axis=1)
tifffile.imwrite('zyx.tif', zyx)

```

**Comment by cgohlke** [comment]
Suppose you have a yzx memory-mapped numpy array or bigger-than-memory zarr/dask array, then you can pass a generator of yx slices as numpy arrays to `tifffile.imwrite`, assuming that each slice fits into memory:
```Python
def yx_sices(yzx):
    # return generator of yx slices through yzx volume
    for z in range(yzx.shape[1]):
        yield yzx[:, z]

tifffile.imwrite(
    'zyx.tif',
    yx_sices(yzx),
    shape=(yzx.shape[1], yzx.shape[0], yzx.shape[2]),
    dtype=yzx.dtype,
    bigtiff=True
)
```
Alternatively you could successively write yx slices with `TiffWriter.write`.

As for the y-axis being flipped up side down, that depends on your dataset. If necessary, you could reverse the order of the yx slices returned by the generator.

**Comment by manoaman** [comment]
@cgohlke does tifffile have a feature to downsample multi-page tiff?  I probably should have asked this also before moving around axis.
