### ISSUE TITLE
Most imagecodec compressions cause black tiff

### ISSUE THREAD

**Issue by cookmscott** [cgohlke/tifffile#109]
Sample:
```
import tifffile as tf
import numpy as np

data = np.random.randint(0, 255, (256, 256, 3), 'uint8')
tf.imwrite('black.tif', data, compression="LZMA", photometric='rgb')
```

Including compression="LZMA" causes output to be black. It will do the same with various other imagecodec compressions. It works fine with "jpeg" fwiw. 

Left is seen with code from above, right is expected:
![image](https://user-images.githubusercontent.com/2273452/147425276-014cb59d-7fe1-49d0-ba46-428a20cb64fd.png)

**Comment by cgohlke** [comment]
I can't reproduce the issue with current versions. This case is also included in the tifffile and imagecodecs unit tests.

What are the versions? And what's the output of `imagecodecs.version()` and `sys.version`?

**Comment by cookmscott** [comment]
Thanks for the quick response! I'm on a PC
*imagecodecs.version()*
```
imagecodecs-2021.11.20, cython-0.29.24, numpy-1.21.5, numpy_abi-0x1000009.14, imcd-2021.11.11, bitshuffle-0.3.5, brotli-1.0.9, brunsli-0.1, c-blosc-1.21.1, c-blosc2-2.0.4, cfitsio-3.49, charls-2.2.0, giflib-5.2.1, imcd-2021.11.11, jpegsof3-2020.12.22, jxrlib-1.1, lcms2-2.12.0, lerc-3.0.0, libaec-1.0.6, libavif-0.9.3, libbzip2-1.0.8, libdeflate-1.8, libjpeg12_turbo-2.1.2/8.0, 
libjpeg_turbo-2.1.2/8.0, libjxl-0.6.1, liblj92-2014, liblzf-1.5, liblzma-5.2.5, libpng-1.6.37, libspng-0.7.0, libtiff-4.3.0, libwebp-1.2.1, lz4-1.9.3, mozjpeg-4.0.3/8.0, openjpeg-2.4.0, pg_lzcompress-13.2, snappy-1.1.7, zfp-0.5.5, zlib-1.2.11, zlib_ng-2.0.5, zopfli-1.0.3, zstd-1.5.0
```
*sys.version*
```
3.10.1 (tags/v3.10.1:2cd268a, Dec  6 2021, 19:10:37) [MSC v.1929 64 bit (AMD64)]
```

**Comment by cgohlke** [comment]
Those versions are certainly working. What's the code (and library versions) you use to read and display the 'black.tif' file?

**Comment by cookmscott** [comment]
Ah, yeah I think I just made the assumption the other compression methods were widely supported. It seems LZW and JPEG are the crowd favorites for most programs. I know it's out of the scope of this request, but any idea how I could get noobOriented's custom [lzw_encoder](https://github.com/cgohlke/tifffile/issues/34#issuecomment-928909213) working with a simple example like above?
