### ISSUE TITLE
Save uint16 array as 12-bit tif image

### ISSUE THREAD

**Issue by pietz** [cgohlke/tifffile#11]
I would like to save a np.uint16 array as a 12-bit precision tif image because the camera has only 12-bit and I don't want to waste disk space. Is this possible? If yes, how?

Thank you

**Comment by cgohlke** [comment]
Tifffile can currently only read, not write packed integers (except for 1 bit, bool arrays). Packing integers would need to be implemented in the imagecodecs library.
