### ISSUE TITLE
Setting a single-channel colormap

### ISSUE THREAD

**Issue by antho214** [cgohlke/tifffile#115]
# Problem

I am trying to set the colormap of a single tif image so that when I open it in ImageJ the image will be displayed with the desired colormap. I am able to set the colormap of a multi-channel image using the `LUTs` option. I am also able to set the displayed range of the image using `min/max` options.

## Troubleshooting

I found that a single tif image saved with ImageJ with a colormap used the `Properties` with `CurrentLUT` option. I obtained this information using `TiffFile(file).imagej_metadata`. When I used this option with `tifffile.imwrite`, the information from the image (obtained with `ctrl+i` in ImageJ) displays that the lut used is as the one specified _but_ the image is still using the default colormap (gray).

Below is a code snippet to reproduce my problem.

```python
import numpy, tifffile
from skimage import filters

# Creates an image
numpy.random.seed(42)
data = numpy.random.rand(256, 256)
data[data < 0.99] = 0
data = filters.gaussian(data, 4)
data = (data * 255).astype(numpy.float32)

# Saves the image
file = "./single-channel.tif"
metadata = {
    "min" : 0.0,
    "max" : 5.0,
    "Properties" : {
        "CurrentLUT" : 'cyan',
    },
}
tifffile.imwrite(file=file, data=data, imagej=True, metadata=metadata)
```

## Versions

```bash
tifffile: 2022.2.2
python: 3.8.8
```

**Comment by antho214** [comment]
It works perfectly!
Could you elaborate on the options that you passed through the `extratags`?
Thank you in advance!

**Comment by cgohlke** [comment]
> Could you elaborate on the options that you passed through the extratags?

https://github.com/cgohlke/tifffile/blob/424a2b7cede62727f911a143678e95edc922801c/tifffile/tifffile.py#L1467-L1480

**Comment by cgohlke** [comment]
In v2022.2.9 you should be able to write a colormap to 32-bit ImageJ files:

```Python
colormap = numpy.vstack(
    [
        numpy.zeros(256, dtype='uint16'),
        numpy.arange(0, 2**16, 2**8, dtype='uint16'),
        numpy.arange(0, 2**16, 2**8, dtype='uint16'),
    ]
)

tifffile.imwrite(
    file,
    data,
    imagej=True,
    metadata=metadata,
    colormap=colormap,
)
```

**Comment by antho214** [comment]
That's great news! Will this method work with multichannel images as well?

**Comment by cgohlke** [comment]
> Will this method work with multichannel images as well?

Yes, if you want the same colormap for all channels, else use the `LUTs` option.
