### ISSUE TITLE
OME TIFF image reads as a 2D array rather than a 3D array

### ISSUE THREAD

**Issue by ajaysingh096** [cgohlke/tifffile#118]
When reading an OME-TIFF image as a NumPy array using the function image.shape, I get a 2D array back when it should be a 3D array.

**For example, here is what I wrote:** 

with tifffile.TiffFile(file_path) as tif:
    image = tif.asarray(key=0, series=0, level=5)

image.shape

**Here is what was returned:**

(2047, 1006)

**Comment by cgohlke** [comment]
Why do you expect a 3D array? The array returned for a single page/frame is 2D if SamplesPerPixel is 1, which is common for OME-TIFF.

**Comment by jessecanada** [comment]
Hi @cgohlke, 

First of all this is an awesome tool and I’m thankful you are keeping it up to date. 

What @ajaysingh096 is saying that when we try to use pagination to get the image as an array from one of the levels of our pyramidal OME-TIFF, we want to retrieve RGB values. So, we are expecting the array in the form of (channel, X, Y) but instead only got (X, Y). We are still learning tifffile so perhaps we are not using the right approach. Any help will be appreciated.

**Comment by jessecanada** [comment]
@cgohlke Thank you! Got it to work. The alternative was to load the first 3 pages of a level and do np.dstack()
