### ISSUE TITLE
Removing an entire image series from OME-TIFF

### ISSUE THREAD

**Issue by jessecanada** [cgohlke/tifffile#119]
Hi @cgohlke,

What's the best approach to removing an entire series from OME-TIFF files? I tried to read series0 only, and write it to a new pyramidal OME-TIFF. Everything works, except I can't figure out how to copy the original tifftags over.

**Comment by jessecanada** [comment]
Follow up:
For tag codes that are common to the new OME-TIFF (series0 only) and the original OME-TIFF (series0, series1), for example 256, 257..., I can use the TiffTag.overwrite() function to restore the original tag values. However, for those tag codes that only exist in the original OME-TIFF, I can't figure out how to add new tags to the new file.

**Comment by cgohlke** [comment]
Write the image data of the selected image series to a new OME-TIFF file. The only tag in the newly written OME-TIFF file that should be updated is the ImageDescription tag in the first TIFF page, which contains a minimal valid new OME-XML. Manually copy missing XML attributes of the selected image series from the original OME-XML, but do not replace existing attributes or change the TiffData elements in the new OME-XML. [Ome-types](https://pypi.org/project/ome-types/) may be the best tool to do that. Validate the OME-XML with tifffile.OmeXml.validate() and write the updated OME-XML back to the ImageDescription tag in the first TIFF page. Then test if the file can be opened with tifffile and Bio-Formats.
