### ISSUE TITLE
Not clear how to read metadata from tifffile object (created with `imread`)

### ISSUE THREAD

**Issue by jimcost** [cgohlke/tifffile#12]
I have a tiff stack that I hope to extract the metadata from, but none of the `imread` object's methods seem to fit the bill. Searching the internet, I didn't find an example on the `tifffile` webpages. Any guidance would be much appreciated!

**Comment by cgohlke** [comment]
There are several examples accessing different kinds of metadata in the docstring: 
https://github.com/cgohlke/tifffile/tree/v2020.6.3/#examples
https://pypi.org/project/tifffile/#examples

The format of metadata in TIFF files is often often specific to the application generating the file, e.g. OME-TIFF, ImageJ, LSM. Tifffile includes metadata readers for several formats:

https://github.com/cgohlke/tifffile/blob/v2020.6.3/tifffile/tifffile.py#L3257-L3485
