### ISSUE TITLE
How can I parse metadata from a separate OMEXMLMetadata.ome file?

### ISSUE THREAD

**Issue by michaelmell** [cgohlke/tifffile#123]
Dear all,

I am using tifffile to read OME-TIFF stacks and process them. My program uses the metadata stored inside the TIFF files.
Something went wrong recently with the recording of a colleague and the metadata was not stored to the TIFF file, but in a separate OMEXMLMetadata.ome file instead (it is unclear how this happened). The data was recorded with MicroManager 2.
The program now fails with this data, because the metadata is not available anymore in the TIFF file.

So, is there a way to parse this information and use it as if it were read in directly from the TIFF file? Here is an excerpt from my program to illustrate how I currently access the metadata, when it is read from the TIFF file:

```python
import tifffile as tff
...
tiff = tff.TiffFile(path_to_first_tiff_file)
...
metadata = tiff.micromanager_metadata['Summary']
height = metadata['Height']
width = metadata['Width']
channels = [c.strip(' ') for c in metadata['ChNames']]
number_of_channels = len(self.channels)
...
```

Best regards and thank you for your support,
Michael

**Comment by cgohlke** [comment]
To use tifffile's series interface to access the image data in a OME multi+companion file set, try to set/replace the `imagedescription` attribute of the first page with the XML from the OME companion file before reading the series, e.g.:
```Python
import tifffile

with open('multifile.companion.ome', 'r') as fh:
    omexml = fh.read()
    assert omexml.endswith('</OME>')

with tifffile.TiffFile('multifile-Z1.ome.tiff', is_ome=True) as tif:
    tif.pages[0].description = omexml
    data = tif.asarray()
```

To access the metadata in the OME XML, just parse the companion xml file with Python's xml module, lxml, or the [ome-types](https://pypi.org/project/ome-types/) package.
