### ISSUE TITLE
TiffWriter Combine Y Dimension

### ISSUE THREAD

**Issue by VenturaFranklin** [cgohlke/tifffile#124]
I have a CYX image that does not fit in memory.
On top of that I need to read the channel cube for processing (unmixing).
So I can not work with just the tile itself, but I need the CYX cube for each tile.
I have been sucessful in reading the image and saving down to intermediate step of the tile cube that I then can unmix.

I am having difficulty bringing the tile cubes back together in one final CYX file.

For a small test file, after breaking it up, I have 87 CYX images on disk. 
The simple solution I have tried below adds each tile in the Time dimension not the Y dimension that the tiles are broken into
```python
with TiffWriter(file_name_out) as tif:
    for file_name in file_names:
        # We are XYC right now
        tile = np.load(file_name)
        # change to CYX b/c image depth, length (height), width, and samples.
        tile = np.moveaxis(tile, 2, 0)
        tif.write(
            tile, 
            # shape=(3, 5518, 5376),
            # dtype="float64",
            # tile=(3, 64, 5376) # tile.shape does not work b/c not multi of 16
            )
```

I see in the documentation, the statement below.
> If 'shape', 'dtype', and 'tile' are specified, 'data' must be an iterable of all tiles in the image.

I tried to make a generator to work with this, but this does not run at all
```python
def slices(file_names):
    for file_name in file_names:
        # We are XYC right now
        tile = np.load(file_name)
        # change to CYX b/c image depth, length (height), width, and samples.
        tile = np.moveaxis(tile, 2, 0)
        for channel in tile:
            yield channel

tifffile.imwrite(
    file_name_out,
    slices(file_names),
    dtype='float64',
    shape=(3, 5518, 5376),
    tile=(1, 64, 5376)
)
```

I feel like I am misunderstanding something fundamental.
Even if I try to write only one channel eg. tile[0] 
I still get a T dimension not combining on the Y dimension.

**Comment by cgohlke** [comment]
The length and width of TIFF tiles must be a multiple of 16. If your CYX cubes do not have compatible dimensions, you have to re-tile or you cannot use tiled TIFF.

TIFF tiles can have dimensions YX or YXS, but not SYX (S being samples). There's a volumetric extension to TIFF that allows tiles to have an additional dimension (e.g. ZYXS), but that format is not well supported by other software.

Change the tile generator to first generate all YX tiles for the first channel, then the second channel and so on.

Specify `photometric` and `planarconfig` so there is no ambiguity how the data are stored in TIFF.

Specify `bigtiff=True` if your files may exceed 4 GB.

The format of the TIFF file should depend on which software is used to read the files. Consider OME-TIFF or ImageJ hyperstacks.

Consider writing to a memory mapped array inside a TIFF file if the TIFF files do not need to be tiled or compressed or if the cube length and width are not a multiple of 16.

**Comment by VenturaFranklin** [comment]
> Consider writing to a memory mapped array inside a TIFF file if the TIFF files do not need to be tiled or compressed or if the cube length and width are not a multiple of 16.

Thank you! That was the concept I didn't see.

What ended up working:
```python
memmap_image = tifffile.memmap(
    file_name_out,
    shape=(3,5568, 5374),
    photometric='MINISBLACK',
    planarconfig=None,  # "SEPARATE"
    dtype='float64',
)

for count, file_name in enumerate(file_names):
    # We are XYC right now
    tile = np.load(file_name)
    tile = np.moveaxis(tile, 2, 0)
    start, stop = count*tile.shape[1], (count+1)*tile.shape[1]
    memmap_image[:,start:stop] = tile
    memmap_image.flush()
```
