### ISSUE TITLE
Problems loading tiff on latest release `Julian_datetime raises ValueError for dates before year 1 (breaking).`

### ISSUE THREAD

**Issue by emmanuel-contreras** [cgohlke/tifffile#129]
Hello, one the latest commits appears to have have broken the way my tiffs are loaded. I get the error below which I think came from the release 2022.4.22 where I see the commit `Julian_datetime raises ValueError for dates before year 1 (breaking).`  which may be where this error got introduced?

I'll keep trying to debug this but I thought I'd submit an issue and attach one of our tiffs (extension changed to .txt so that I could upload it here) if you'd have a chance to look at this.

[Cells-003_Cycle00001_Ch1_000001.ome..txt](https://github.com/cgohlke/tifffile/files/8576521/Cells-003_Cycle00001_Ch1_000001.ome.txt)

Thank you

**Comment by cgohlke** [comment]
Thanks for the test file! All files I had so far seem to contain valid dates in the UIC tags. Maybe the format changed or the PrairieView software just doesn't write dates? Anyway, the fatal exception will be fixed in the next version of tifffile.

**Comment by cgohlke** [comment]
Fixed in v2022.4.28.

**Comment by emmanuel-contreras** [comment]
yes these are older files so possibly something changed. I just tested it and appears to be working and displaying the `failed reading` warnings. Thanks again!
