### ISSUE TITLE
[question] why does tag 282 (XResolution) yield a 2-tuple? 

### ISSUE THREAD

**Issue by PiRK** [cgohlke/tifffile#13]
When I read tiff tag 282 with PIL, I get a scalar:

        resX = pil_img.tag.get(282) 
        if resX not in [None, 0]:
            # from px / unit to unit / px
            self.x_resolution = 1. / resX

With tifffile, when reading page 0 of a NDPI file, I get a 2-tuple:

        tags = tif.pages[0].tags
        resX_tag = tags.get(282)
        if resX_tag is not None:
            resX = resX_tag.value
            if hasattr(resX, "__len__"):
                resX = resX[0]
            # from px / unit to unit / px
            self.x_resolution = 1. / resX if resX else 0.

Can you explain the meaning of the 2 values? In the case of my NDPI file, only the first value seems meaningful, the second one is 1.
But in the examples you give in the Readme file, it seems there are 2 meaningfull values:
```
>>> with TiffFile('temp.tif') as tif:
...     tag = tif.pages[0].tags['XResolution']
>>> tag.value
(2000, 5351)
```

This page seems to indicate that we should expect a single value from this tag: https://www.awaresystems.be/imaging/tiff/tifftags/xresolution.html

**Comment by cgohlke** [comment]
The TIFF types of the `XResolution` and `YResolution` tags are `RATIONAL` (5) which is defined in the TIFF specification as "two LONGs: the first represents the numerator of a fraction; the second, the denominator."

https://github.com/cgohlke/tifffile/blob/4e67de4bb7bf50ff4f21306a9a27eaf9f2aca7f0/tifffile/tifffile.py#L8028-L8029

You could use [fractions.Fraction](https://docs.python.org/3/library/fractions.html) to handle those values.
