### ISSUE TITLE
Adding thumbnail to pyramidal TIF file

### ISSUE THREAD

**Issue by Amy-so** [cgohlke/tifffile#130]
I am trying to add thumbnail to pyramidal TIF file, but I cannot find any option to add that. Is there anyway to write pyramidal TIF file with thumbnail?
Thank you

**Comment by cgohlke** [comment]
That depends on the specific format of the TIFF file and/or the software that will be used to read the files. Some formats/software expect the thumbnail at a specific position in the IFD chain, e.g. the second or last. Some require the ImageDescription tag to be "Thumbnail", others don't allow for a thumbnail or ignore any images that don't fit in the pyramid...

**Comment by Amy-so** [comment]
Thank you for your response. 
I want to see image preview when I browsing them in the folder. I am using czifile package to read my czi format images and then using tifffile package to convert those images to pyramidal tif format. This is my code:
img = czifile.imread(image_path)
block1=np.squeeze(img)
with TiffWriter('temp.ome.tif', bigtiff=True) as tif:
    options = dict(tile=(256, 256), photometric='rgb', compression='jpeg')
    tif.write(block1, subifds=4, **options)
    tif.write(block1[::4, ::4], subfiletype=1, **options)
    tif.write(block1[::8, ::8], subfiletype=1, **options)
    tif.write(block1[::16, ::16], subfiletype=1, **options)
    tif.write(block1[::32, ::32], subfiletype=1, **options)

Is it possible to add thumbnail to the final image?

**Comment by cgohlke** [comment]
> how can I use ImageDescription tag or IFD chain to add thumbnail?

Just write another image, e.g. `tif.write(thumbnail_array, photometric='rgb', description='Thumbnail')`, but that will neither be recognized as a thumbnail by Windows Explorer nor by any other software...
