### ISSUE TITLE
`ZarrTiffStore.write_fsspec` make template key configurable

### ISSUE THREAD

**Issue by ap--** [cgohlke/tifffile#131]
Hi @cgohlke,

I'm currently experimenting with combining multiple tiffs via kerchunk. If `.write_fsspec` would allow to configure the url template `"{{u}}"` used in reference `version=1` it would simplify some of the downstream code I use to combine multiple references into one.

I already prepared a patch: https://github.com/ap--/tifffile/commit/3018569ea66a6d0ffba8ebe2a3d80fc88629024a

Cheers,
Andreas 😃

**Comment by cgohlke** [comment]
Thanks for the suggestion! v2022.4.28 added a `templatename` parameter to the `write_fsspec` functions.

**Comment by ap--** [comment]
Thanks for the super quick update!

I can still write a test if it's helpful.

Regarding the performance issue: I haven't experienced this. For the larger aperio svs WSI images I am dealing with (~5GB) the version=1 reference json (including all levels) is around 12MB and loads almost instantly via `ReferenceFileSystem`.

Here's the lowest level .zarray info:

```json
{
 "chunks": [
  240,
  240,
  3
 ],
 "compressor": {
  "bitspersample": 8,
  "colorspace_data": 2,
  "colorspace_jpeg": 2,
  "header": null,
  "id": "imagecodecs_jpeg",
  "tables": "/9j/2wBDAAoHBwgHBgoICAgLCgoLDhgQDg0NDh0VFhEYIx8lJCIfIiEmKzcvJik0KSEiMEExNDk7Pj4+JS5ESUM8SDc9Pjv/2wBDAQoLCw4NDhwQEBw7KCIoOzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozv/xAAfAAABBQEBAQEBAQAAAAAAAAAAAQIDBAUGBwgJCgv/xAC1EAACAQMDAgQDBQUEBAAAAX0BAgMABBEFEiExQQYTUWEHInEUMoGRoQgjQrHBFVLR8CQzYnKCCQoWFxgZGiUmJygpKjQ1Njc4OTpDREVGR0hJSlNUVVZXWFlaY2RlZmdoaWpzdHV2d3h5eoOEhYaHiImKkpOUlZaXmJmaoqOkpaanqKmqsrO0tba3uLm6wsPExcbHyMnK0tPU1dbX2Nna4eLj5OXm5+jp6vHy8/T19vf4+fr/xAAfAQADAQEBAQEBAQEBAAAAAAAAAQIDBAUGBwgJCgv/xAC1EQACAQIEBAMEBwUEBAABAncAAQIDEQQFITEGEkFRB2FxEyIygQgUQpGhscEJIzNS8BVictEKFiQ04SXxFxgZGiYnKCkqNTY3ODk6Q0RFRkdISUpTVFVWV1hZWmNkZWZnaGlqc3R1dnd4eXqCg4SFhoeIiYqSk5SVlpeYmZqio6Slpqeoqaqys7S1tre4ubrCw8TFxsfIycrS09TV1tfY2dri4+Tl5ufo6ery8/T19vf4+fr/2Q=="
 },
 "dtype": "|u1",
 "fill_value": 0,
 "filters": null,
 "order": "C",
 "shape": [
  92801,
  165336,
  3
 ],
 "zarr_format": 2
}
```

**Comment by ap--** [comment]
I just realized you might be talking about performance issues when combining many WSI images into one kerchunk reference.

I'm still in the experimenting phase and tested with combined lowest levels of ~300 files that have been manually reshaped (to `tuple(N_chunks_total, *chunks)`) and loaded via xarray. I had no performance issues there either. But I'll revisit the topic, and will create a benchmark and report back.
