### ISSUE TITLE
TiffWriter.write doesn't write TIFF TAG 254 (NewSubfileType) if the value is 0 (UNDEFINED) but it should do.

### ISSUE THREAD

**Issue by tykwak-deepbio** [cgohlke/tifffile#132]
I was trying to set subfiletype=0 for the pyramid base level image (the first page of the first series), but I couldn't get the written 254 tag with value 0.
And, I found that:
![image](https://user-images.githubusercontent.com/39817113/166623878-c9b002e9-56ca-42f2-88c1-1c3fb1e0b92b.png)
, which doesn't work with subfiletype=0.
I think that it should be like ```if subfiletype is not None:``` or some.

**Comment by cgohlke** [comment]
Thanks. Fixed in v2022.5.4.
