### ISSUE TITLE
syntax error in python 3.6.7 during "import tifffile"

### ISSUE THREAD

**Issue by Marc-3d** [cgohlke/tifffile#133]
Hello, 

I can import tifffile from an anaconda environment with version 3.10, no problem there. 

However, when I try to import tifffile from slicer, which comes with its own python 3.6.7, I get a syntax error. 

In particular, I get an error due to the use of a forward slash in the arguments of tifffile.py/imwrite:

https://github.com/cgohlke/tifffile/blob/375d97f62df6482142b51f1b38a49bdd24d18a60/tifffile/tifffile.py#L1041-L1043

I guess renaming the argument "/" would ensure backward compatibility with previous python versions, such as 3.6.7.

**Comment by cgohlke** [comment]
This project follows [NEP 29](https://numpy.org/neps/nep-0029-deprecation_policy.html). The last version of tifffile to support Python 3.6 was 2020.6.3. Current versions only support Python 3.8, 3.9 and 3.10.
