### ISSUE TITLE
Random Access within Tiled TIFF files

### ISSUE THREAD

**Issue by ebnertom** [cgohlke/tifffile#134]
Hi,

I really appreciate your work on this library and like it's functionality and usage.

However, I really miss the functionality to read tiled TIFF files with random access.
i.e.: access only only a small region of the image defined by x,y,width,height without reading the whole image in memory.

Is some functionality like this planned or is this functionality even available and I've overlooked it in the documentation?

BR,
Thomas

**Comment by cgohlke** [comment]
That's what the [zarr](https://zarr.readthedocs.io/en/stable/) store interface is for, e.g.:

https://github.com/cgohlke/tifffile/blob/375d97f62df6482142b51f1b38a49bdd24d18a60/tifffile/tifffile.py#L632-L643

There are also packages that built on tifffile to provide openslide like interfaces: [tiffslide](https://github.com/bayer-science-for-a-better-life/tiffslide) and [opentile](https://github.com/imi-bigpicture/opentile).

**Comment by ebnertom** [comment]
Thanks a lot, I've overlooked this feature in the documentation.
BR,
Thomas
