### ISSUE TITLE
Metadata in Hamamatsu ndpi file

### ISSUE THREAD

**Issue by dakomura** [cgohlke/tifffile#138]
Hi there,

I'm trying to read metadata in Hamamatsu .ndpi files such as mpp (microns per pixel).
But I cannot find it in the TiffFile.
```
import tifffile as t
data = t.TiffFile("./CX446.ndpi")
vars(data)
```

> {'_fh': <tifffile.FileHandle 'CX446.ndpi'>,
>  '_multifile': True,
>  '_files': {'CX446.ndpi': <tifffile.TiffFile 'CX446.ndpi'>},
>  '_decoders': {},
>  '_parent': <tifffile.TiffFile 'CX446.ndpi'>,
>  'tiff': <tifffile.tifffile._TIFF.NDPI_LE.<locals>.NdpiTiffLe at 0x7fbee0cd5980>,
>  'pages': <tifffile.TiffPages @234219866>,
>  'is_lsm': False,
>  'is_scanimage': False,
>  'is_philips': False,
>  'is_ndpi': True}

I could read the metadata using openslide like this.

```
import openslide
op = openslide.OpenSlide("./CX446.ndpi")
print(op.properties['hamamatsu.XOffsetFromSlideCentre'])
print(op.properties['openslide.mpp-x'])
```
> 17860735
> 0.2208187960959237

Are there any ways to get the information?

**Comment by cgohlke** [comment]
I guess `openslide.mpp-x` comes from the `XResolution` tag. The `XOffsetFromSlideCenter` and other NDPI specific values are stored in private tags, which are also consolidated in the `ndpi_tags` property:

https://github.com/cgohlke/tifffile/blob/375d97f62df6482142b51f1b38a49bdd24d18a60/tifffile/tifffile.py#L15076-L15124

```Python
from tifffile import TiffFile
with TiffFile('CMU-1.ndpi') as ndpi:
    print(ndpi.series[0].keyframe.tags['XResolution'].value)
    print(ndpi.series[0].keyframe.tags['ResolutionUnit'].value)
    print(ndpi.series[0].keyframe.ndpi_tags['XOffsetFromSlideCenter'])
```
```
(21910, 1)
RESUNIT.CENTIMETER
4876667
```

See also https://openslide.org/formats/hamamatsu/.

**Comment by dakomura** [comment]
It works. Thank you so much!
Daisuke

**Comment by anesdo** [comment]
Where can I find the numpy array (image)?

**Comment by cgohlke** [comment]
> Where can I find the numpy array (image)?

There are several examples how to access the image data in tiled, pyramidal files:

https://github.com/cgohlke/tifffile/blob/35c19b7c6c8b85aa09e490520677b5a2a31c14e4/tifffile/tifffile.py#L676-L735
