### ISSUE TITLE
maxworkers

### ISSUE THREAD

**Issue by uutzinger** [cgohlke/tifffile#139]
Multithreaded compression was introduced with version 2022.3.16. For me this resulted in performance drop of factor of 4.

I write 720x540x14 data blocks with PACKBITS. When I set maxworkers=1 (disables multi threading) performance is regained. I use nvme and M.2 drives for testing.

Perhaps it would be useful to specify under which conditions multi threading improves write performance or only enable multi threading when favorable conditions are met.

In my application, I create storage thread and pass data through queue. A bigtiff file is opened during thread initialization
tiff = tifffile.TiffWriter(filename, bigtiff=True)
and data is written with 
tiff.write(data_cube, compression='PACKBITS', photometric='MINISBLACK', contiguous=False, metadata ={'time': cube_time, 'author': 'camera'}, maxworkers=1) 

imagecodecs 2022.2.22
tifffile affected 2022.5.4 -2022.3.16

**Comment by cgohlke** [comment]
Yes. This is on the TODO list. The current implementation is too simplistic:
https://github.com/cgohlke/tifffile/blob/375d97f62df6482142b51f1b38a49bdd24d18a60/tifffile/tifffile.py#L3467-L3487

For simple codecs like PackBits, multithreading should probably be disabled. Multithreading works well with JPEG and JPEG2000 for example. Some codecs use internal multithreading. As you noted, multithreading efficiency also depends on storage type... Maybe it's better to make this opt-in or significantly increase the threshold?

The documentation should be improved too. For reference, there's some notes for multithreading when reading:
https://github.com/cgohlke/tifffile/blob/375d97f62df6482142b51f1b38a49bdd24d18a60/tifffile/tifffile.py#L3769-L3779

**Comment by uutzinger** [comment]
Thank you for fast and detailed reply and putting this on todo list.
It looks to me that multiple workers is useful for LZMA and also other compressors when images are high definition.

For test I used 
- 720x540x14x8bit random int
- 1920x1080x14x8bit random int
as image data.

I write to WD SN850 in windows

720X540 results:
Compression None:  250 per second (>1Gbyte/sec)
Compression PACKBITS: 52 per second 1 worker
Compression PACKBITS: 14 per second 4 workers
Compression LZMA: 1 per second 1 worker
Compression LZMA: 2 per second 4 workers
Compression LZMA: 2.2 per second 8 workers
Compression ZSTD: 24 per second 1 worker
Compression ZSTD: 13.2 per second 4 workers
Compression zlib: 16 per second 1 worker
Compression zlib: 12 per second 4 worker

1080p results:
Compression NONE: 33 per second (0.9 Gbytes/sec)
Compression PACKBITS: 10.6 per second 1 worker
Compression PACKBITS 7.5 per second 4 workers
Compression LZMA 0.2 per second 1 worker
Compression LZMA 0.6 per second 4 workers
Compression zlib 3.2 per second 1 worker
Compression zlib 5.8 per second 4 workers

Throughput without compression of your library is very good and several times higher than what I could achieve with HDF5 writer. Thank you for your work.

**Comment by cgohlke** [comment]
Thank you! I will also run some benchmarks. It looks like multi-threading may better be disabled for the default strip size of ~8KB. That strip size is the recommended maximum by the TIFF/EP standard but it's just too small given Python's and threading overhead. For common tile sizes of 256x256 the advantage of multi-threading should be more obvious...

**Comment by cgohlke** [comment]
I can't really reproduce those results. With the exception of PackBits on the smaller image, all cases show significant lower write times with multiple-threads. What's the output of the following script?
```Python
import numpy
from tifffile import TiffWriter, Timer

for shape in [(14, 540, 720), (14, 1080, 1920)]:
    data = numpy.random.randint(0, 255, size=shape, dtype='uint8')
    for compression in ['none', 'zlib', 'zstd', 'packbits', 'lzma']:
        for maxworkers in (1, 2, 4, 6):
            fname = f'test_{shape}_{compression}_{maxworkers}.tif'
            with TiffWriter(fname, bigtiff=True) as tif:
                with Timer(fname):
                    for frame in data:
                        tif.write(
                            frame,
                            compression=compression,
                            photometric='minisblack',
                            maxworkers=maxworkers,
                        )
        print()
```

Is the virus checker disabled for TIF files or the python.exe process? Explorer shell extensions or Windows search might also mess with timing TIF writing speed.

According to testing on my system with WSI image data, PackBits, JPEG, and LERC compression work well with multiple threads for segment sizes >~128KB, zlib and zstd with >~32KB, JPEGXR and PNG >~8KB, JPEG2000 and JPEGXL > 2KB, LZMA and WEBP >~1 KB.

**Comment by cgohlke** [comment]
Hopefully this improved in v2022.7.28.
