### ISSUE TITLE
How to read single tiles from a file?

### ISSUE THREAD

**Issue by rfezzani** [cgohlke/tifffile#14]
Hello @cgohlke and thank you for developing/maintaining this awesome package ^^.

I am trying to read a large pyramidal,  multi-stack WS image in `svs` format (15×91775×87648×3 pixels at full resolution):

```python
>>> with tifffile.TiffFile(fname) as f:
...   for s in f.series:
...     print(s.shape)
... 
(15, 91775, 87648, 3)
(768, 733, 3)
(15, 22943, 21912, 3)
(15, 5735, 5478, 3)
(15, 2867, 2739, 3)
(680, 653, 3)
(613, 1600, 3)
```

I would like to read the image by chunks, and I saw in the [changelog](https://github.com/cgohlke/tifffile/blob/master/tifffile/tifffile.py#L116) that it is possible to read individual tiles from the image but I can't found the function or doc for this.
Can you please point me to the correct method for doing this?
Thank you.

**Comment by cgohlke** [comment]
The function is `TiffPage.decode`:

https://github.com/cgohlke/tifffile/blob/4e67de4bb7bf50ff4f21306a9a27eaf9f2aca7f0/tifffile/tifffile.py#L4295-L4323

Iterate over all tiles in a SVS file:
```Python
with TiffFile(filename) as tif:
    print(tif)
    fh = tif.filehandle
    for page in tif.pages:
        print(page)
        jpegtables = page.tags.get('JPEGTables', None)
        if jpegtables is not None:
            jpegtables = jpegtables.value
        for index, (offset, bytecount) in enumerate(
            zip(page.dataoffsets, page.databytecounts)
        ):
            fh.seek(offset)
            data = fh.read(bytecount)
            segment, indices, shape = page.decode(data, index, jpegtables)
            print(segment.shape, indices)
```

or
```Python
with TiffFile(filename) as tif:
    print(tif)
    for page in tif.pages:
        print(page)
        for segment, indices, shape in page.segments():
            print(segment.shape, indices)

```

**Comment by rfezzani** [comment]
Excellent, thank you @cgohlke, I will give this a try ;)

**Comment by rfezzani** [comment]
If anyone is interested, I wrote a [gist](https://gist.github.com/rfezzani/b4b8852c5a48a901c1e94e09feb34743) allowing to read a crop from a tiled TIFF image file directory without loading the whole page.

Thank you @cgohlke for your help ;)
