### ISSUE TITLE
Multi-resolution imread

### ISSUE THREAD

**Issue by sidward14** [cgohlke/tifffile#140]
Hello, thank you for the package. It's by far the fastest one in Python I've tested for our data.

We have multiple resolutions stored in our tiffs, so I was wondering if there was a way to read these in using your package, at specific pages / keys? I don't know the resolution of each key beforehand.

**Comment by cgohlke** [comment]
Use the `TiffFile.series` interface to access levels if the format is know by tifffile, e.g.:

https://github.com/cgohlke/tifffile/blob/375d97f62df6482142b51f1b38a49bdd24d18a60/tifffile/tifffile.py#L610-L616

To directly access specific pages, index `TiffFile.pages` (for main IFD chain) and `TiffPage.pages` (for SubIFDs).

**Comment by sidward14** [comment]
Okay thank you. I used imread per series, and then filtered down to the pages I wanted afterward. However, now it seems to be 10-100X slower per page read. I tried different values of maxworkers, but that didn't help much.

But anyways, thank you very much. I will definitely use this library when I know the pages I need are all the same resolution.
