### ISSUE TITLE
change to default resolutionunit when resolution is not provided

### ISSUE THREAD

**Issue by grlee77** [cgohlke/tifffile#145]
In tifffile>=2022.7.28 it seems that when `resolution` is None, the default `resolutionunit` changed from `tifffile.RESUNIT.NONE` to `tifffile.RESUNIT.INCH`. Was this intentional? (The 2022.7.8 release notes do list "Standardize resolution parameter and property.", but didn't mark it as breaking)

compare:
https://github.com/cgohlke/tifffile/blob/375d97f62df6482142b51f1b38a49bdd24d18a60/tifffile/tifffile.py#L2571
vs.
https://github.com/cgohlke/tifffile/blob/7f691c3270377a9c37efabb9e0d35433a06fa766/tifffile/tifffile.py#L2639

**Comment by cgohlke** [comment]
First thought: no, it wasn't intentional. I'll look in more detail and also check why the tests did not catch this...

**Comment by cgohlke** [comment]
Fixed in v2022.8.3.

**Comment by grlee77** [comment]
Thanks for the quick fix @cgohlke!
