### ISSUE TITLE
imwrite: Does not write with RGB photometric interpretation

### ISSUE THREAD

**Issue by juanenofbit** [cgohlke/tifffile#146]
Hi, 

I am encountering the following problem in all the examples I am testing:
when I want to write a three-channel image with photometric 'rgb', it is recorded as 'YCbCr'

```
tifffile.imwrite(fFilename_output, 
                 stack,
                 bigtiff=True,
                 tile=(512, 512),
                 photometric='rbg',
                 compression =('jpeg', 95))

!tiffinfo $fFilename_output

```

```
TIFF Directory at offset 0x16 (10)
  Image Width: 5358 Image Length: 5000
  Tile Width: 512 Tile Length: 512
  Resolution: 1, 1 (unitless)
  Bits/Sample: 8
  Compression Scheme: JPEG
  Photometric Interpretation: YCbCr
  YCbCr Subsampling: 2, 2
  Samples/Pixel: 3
  Planar Configuration: single image plane
  Reference Black/White:
     0:     0   255
     1:   128   255
     2:   128   255
  ImageDescription: {"shape": [5000, 5358, 3]}
  Software: tifffile.py
```

**Comment by cgohlke** [comment]
That's on purpose.

JPEG compression in TIFF is specified in the "Adobe Photoshop TIFF Technical Notes, March 22, 2002", which states:

```
The PhotometricInterpretation and sub sampling fields written to the file must describe 
what is actually in the file. 

A JPEG-compressed TIFF file will typically have Photometric Interpretation = YCbCr 
```

RGB images saved by tifffile are converted to YCbCr by default during the JPEG compression and the PhotometricInterpretation tag value reflects that.

It is possible to instruct the JPEG encoder not to convert to YCbCr. However, the libtiff library does not seem to decode the resulting JPEG stream correctly. I'll have to investigate if that is a bug in the encoding or libtiff. I think it's best to avoid non-YCbCr JPEG streams in TIFF.

Note that, for these reasons, JPEG compression in tifffile is considered experimental.

**Comment by cgohlke** [comment]
> the libtiff library does not seem to decode the resulting JPEG stream correctly. I'll have to investigate if that is a bug in the encoding or libtiff.

It's a bug in the imagecodecs library. 

Once it is fixed in the next release of imagecodecs, it will be possible to write TIFF with JPEG compression in RGB mode:

```Python
tifffile.imwrite(
    filename,
    image_array,
    photometric='rgb',
    subsampling=(1, 1),
    compression='jpeg',
    compressionargs={'level': 95, 'outcolorspace': 'rgb'}
)
```

Still, the Windows Imaging Component used by many software can only decode TIFF with JPEG compression using YCbCr colorspace.
