### ISSUE TITLE
Support large NDPI files ( > 4GB)

### ISSUE THREAD

**Issue by ksidis** [cgohlke/tifffile#15]
When I try to read a large NDPI file, I get only the first page and the rest are truncated. I understand the problem and the fact that NDPI is based on the classic TIFF format, which does not support files larger than 4 GB. However, large NDPI files are out there. Given the fact that some libraries out there (i.e. openslide) are able to read them and that there are "To-Do" comments in your code pointing to it, I wanted to ask you what is your plan on supporting this? 

Please have a look [here](https://github.com/openslide/openslide/pull/276) on how openslide addressed the issue last year.

**Comment by cgohlke** [comment]
The current state of NDPI support in tifffile is described at

https://github.com/cgohlke/tifffile/blob/4e67de4bb7bf50ff4f21306a9a27eaf9f2aca7f0/tifffile/tifffile.py#L266-L270

To read JPEG compressed tiles with dimensions > 65536, the imagecodecs library needs to be compiled with a patched libjpeg-turbo library https://github.com/cgohlke/imagecodecs/blob/v2020.5.30/imagecodecs/patches/libjpeg-turbo.diff. Currently only the wheels for Windows are compiled with this patch.

To enable experimental > 4GB NDPI support, use `TiffFile(..., is_ndpi=True)`

https://github.com/cgohlke/tifffile/blob/4e67de4bb7bf50ff4f21306a9a27eaf9f2aca7f0/tifffile/tifffile.py#L2222-L2225

However, offsets found in tiff tag structures are not corrected (not implemented yet), which makes this option currently unusable. AFAICT correcting the offsets is undocumented and the implementation would be hacky.

**Comment by cgohlke** [comment]
NDPI files > 4 GB will be supported in the next version. However, those files can contain large JPEG compressed segments which cannot be decompressed even with the patched libjpeg-turbo library. 2 GB compressed size seems to be the limit.

**Comment by ksidis** [comment]
Thank you for your response.

**Comment by cgohlke** [comment]
Should be fixed in v2020.7.4.
