### ISSUE TITLE
Broken linkes in README.rst file

### ISSUE THREAD

**Issue by MatthiasSagerer** [cgohlke/tifffile#151]
### I found five broken links in the README.rst file under references:

- https://www.adobe.io/open/standards/TIFF.html
- http://www.ultralum.com/images%20ultralum/pdf/UQStart%20Up%20Guide.pdf
- http://www.cipa.jp/std/documents/e/DC-008-Translation-2016-E.pdf
- https://www.adobe.com/content/dam/acom/en/products/photoshop/pdfs/
- https://diagnostics.roche.com/content/dam/diagnostics/Blueprint/en/pdf/rmd/

Just wanted to let you know.

**Comment by cgohlke** [comment]
Try the waybackmachine, e.g. https://web.archive.org/web/20211209104854/https://www.adobe.io/open/standards/TIFF.html
