### ISSUE TITLE
ImageJ spacing reads only the last dimension

### ISSUE THREAD

**Issue by schlegelp** [cgohlke/tifffile#152]
Hi Christoph!

First of all thanks for this library - it's been super useful to me.

Not sure whether this is a bug or expected behavior but I noticed that when reading stacks where ImageJ shows spacing and units for each of the three axes, the `Tifffile.imagej_metadata` only returns units/spacing for the third axis.

I'm attaching this zipped [test.tif.zip](https://github.com/cgohlke/tifffile/files/9585181/test.tif.zip) which is just an empty stack with voxel sizes set to 10x10x20 microns:

![Screenshot 2022-09-16 at 16 02 44](https://user-images.githubusercontent.com/7161148/190670352-71ce294b-80e0-4b4e-b4a8-c1556a149a53.png)

When I open the same file using `tifffile` I only get the third dimension:

```Python
>>> with tifffile.TiffFile('test.tif') as tif:
>>>   meta = tif.imagej_metadata
>>> meta
{'ImageJ': '1.53q',
 'images': 10,
 'slices': 10,
 'unit': 'microns',
 'spacing': 20.0,
 'loop': False}
```

Perhaps the x/y spacing is just hiding in some other property? Any help would be greatly appreciated!

Thanks,
Philipp

**Comment by schlegelp** [comment]
Ok, immediately found the x/y resolution, I think:

```Python
>>> tif = tifffile.TiffFile('test.tif')
>>> res = tif.pages[0].resolution
>>> spacing = (1 / res[0], 1 / res[1])
>>> spacing
(10.0, 10.0)
```

I guess it makes sense that x/y is stored in the pages and z is part of the meta data. I couldn't find the unit for x/y though.

**Comment by cgohlke** [comment]
ImageJ uses TIFF tag `ResolutionUnit=NONE` for x/y since TIFF only knows inch and centimeter. I think the unit for x/y is the same as for z, `imagej_metadata['unit']`, usually micrometer.
