### ISSUE TITLE
memmap and subifds

### ISSUE THREAD

**Issue by VenturaFranklin** [cgohlke/tifffile#153]
I have large images (80+ GB) that I am trying to generate multi channel pyramid tiffs for. 
I am using memmap to write out the files and this works well, but now adding in pyramids I do not see how to do this with the memmap method. Specifically memmap uses imwrite but imwrite does not pass subifds through. 

Is there a way to generate a large multichannel pyramid image using tifffile?

**Comment by cgohlke** [comment]
The high-level `memmap` and `imwrite` methods cannot create SubIFDs.

You could do something like this (don't):
```
from tifffile import TiffWriter, memmap

with TiffWriter('issue153.tif', bigtiff=True) as tif:
    tif.write(shape=(6, 256, 256), dtype='uint16', subifds=2)
    tif.write(shape=(6, 256//2, 256//2), dtype='uint16', subfiletype=1)
    tif.write(shape=(6, 256//4, 256//4), dtype='uint16', subfiletype=1)

level0 = memmap('issue153.tif', series=0)
level1 = memmap('issue153.tif', series=0, level=1)
level2 = memmap('issue153.tif', series=0, level=2)
```

However, I don't think any software can efficiently read such files if they are multi-GB. Instead, create [tiled, multi-dimensional, multi-resolution (pyramidal) OME-TIFF](https://github.com/cgohlke/tifffile/blob/eb79f64e65fdd17fa5722dac9ce32ec6dd224f5d/tifffile/tifffile.py#L554-L599) files. Either [create a zeroed OME-TIFF and then write to it via the Zarr interface](https://github.com/cgohlke/tifffile/blob/eb79f64e65fdd17fa5722dac9ce32ec6dd224f5d/tifffile/tifffile.py#L660-L676) or [use a generator of tiles](https://github.com/cgohlke/tifffile/blob/eb79f64e65fdd17fa5722dac9ce32ec6dd224f5d/tifffile/tifffile.py#L538-L552).

**Comment by cgohlke** [comment]
It's probably more efficient to move the creation of the zarr array outside the loop:
```Python
...
store = imread(file_name_out, mode='r+', aszarr=True)
zarr_image = zarr.open(store, mode='r+')
for count, file_name in enumerate(file_names):
    ...
store.close()
```
