### ISSUE TITLE
Open image as stream like PIL

### ISSUE THREAD

**Issue by rk-exxec** [cgohlke/tifffile#154]
Is there a way to open an image (compressed tiff in my case) without reading it to memory just like PIL.Image.open() ?

I am using it like so:
```py 
img = Image.open(path)
imshape = (*img.size,len(img.getbands()))
mask = np.memmap(TEMPDIR.name  + "/temp_mask.dat", mode="w+", dtype=np.uint8, shape=imshape)
mask[:] = np.array(img)
```
I want to reduce my memory footprint and this does seem to work nicely and I was wondering if something similar is possible with tifffile. 

I am currently using PIL to read and tifffile to write and it would be nice to reduce the deps on my project.

Thanks!

**Comment by cgohlke** [comment]
Set the [`out`](https://github.com/cgohlke/tifffile/blob/eb79f64e65fdd17fa5722dac9ce32ec6dd224f5d/tifffile/tifffile.py#L20869-L20883) parameter: `mask = tifffile.imread(path, out=TEMPDIR.name  + "/temp_mask.dat")`.

Btw, `mask[:] = np.array(img)` reads the whole image into memory before copying it to the memory mapped array.
