### ISSUE TITLE
 OME-TIFF roundtrip

### ISSUE THREAD

**Issue by gsakkis** [cgohlke/tifffile#156]
I'm looking for a way to recreate arbitrary OME-TIFF files that have been read in memory as `TiffFile` instances. Ideally the conversion should be lossless, i.e. the recreated file should be a byte for byte copy of the original. Is this in generally possible and if so how? If not, what's the closest approximation?

**Comment by cgohlke** [comment]
Probably not. TiffWriter is a high level tool to save numpy arrays to TIFF with several options to control how to write the file. Lossless round tripping the image data in OME format is possible, but there is no guarantee that the file layout, all metadata, and TIFF tags are recreated, especially not byte for byte.  

What is your specific use case, example? Maybe TiffWriter can create an approximated copy that comes close enough to the original?

Also consider [tifftools](https://github.com/DigitalSlideArchive/tifftools).

**Comment by gsakkis** [comment]
> Probably not. 

I thought so, hence the "ideally lossless".

> Maybe TiffWriter can create an approximated copy that comes close enough to the original?

That's what I'm trying to do at at the moment but my first attempts don't seem to be "close enough". Any sample code towards this direction would be quite helpful.

**Comment by cgohlke** [comment]
I added a new test in v2022.10.10 that rewrites an OME-TIFF file. However, this will only write minimal OME-XML metadata, not copy all existing metadata. That is out of the scope of this library and can be done for example with [ometypes](https://github.com/tlambert03/ome-types). Also, `TiffFile` and `TiffWriter` come from separate developments and properties/arguments might be out of sync. Please report such cases if you run into them.

https://github.com/cgohlke/tifffile/blob/a73812e98f58b068a590de862ed547820fd332ad/tests/test_tifffile.py#L16286-L16434

**Comment by gsakkis** [comment]
Can you expand a bit on how to use [ometypes](https://github.com/tlambert03/ome-types) to copy all existing metadata? AFAICT `ometypes` parses OME-XML metadata into python dataclasses, alllows manipulating them and finally writing back the modified metadata as xml. I don't need to modify any metadata, only copy them over to the output.

Btw I tried passing `metadata = dict(tifffile.xml2dict(tif.ome_metadata), axes=series.axes)` and it does copy some metadata but ignores others (e.g. `Instrument`, `StructuredAnnotations`, `ObjectiveSettings`, etc.).
