### ISSUE TITLE
installation requirements

### ISSUE THREAD

**Issue by ionymikler** [cgohlke/tifffile#158]
the module requires also the "imagecodecs" module, not installed together with this.

**Comment by cgohlke** [comment]
Imagecodecs is an [optional dependency](https://github.com/cgohlke/tifffile/blob/a73812e98f58b068a590de862ed547820fd332ad/setup.py#L89-L97) like matplotlib, lxml, etc. Imagecodecs is only required to decode some compression and prediction schemes. Imagecodecs binaries are not available for all platforms such as ARM or latest Python releases.
