### ISSUE TITLE
Write Tiff files that are fully readable by OpenSlide/QuPath

### ISSUE THREAD

**Issue by vrishk** [cgohlke/tifffile#159]
I'm currently using code from the README to write out a numpy array as a tiled tiff that is readable by tiffslide. However, openslide and QuPath are unable to read anything but the first level of the file. 

How should I go about writing out images that are completely readable by openslide and viewable in openslide with TiffFile?

**Comment by cgohlke** [comment]
QuPath supports OME-TIFF via Bio-Formats:
https://github.com/cgohlke/tifffile/blob/a73812e98f58b068a590de862ed547820fd332ad/tifffile/tifffile.py#L590-L635

The only open TIFF format supported by OpenSlide is [Generic TIFF](https://openslide.org/formats/generic-tiff/). It can be written in a way similar to the example above, but 

- set `metadata=None` and `subifds=None` 
-  do not write the thumbnail image
- does not support T, C, Z dimensions.

**Comment by rdbs-oss** [comment]
Hello, thank you for the answer and maintaining tifffile.

I have a related issue.
The method you propose works fine when I read regions at level 0, however, when I read regions at level 1, it works only if the coordinates of the region are multiple of the `tile` argument (tile-size used to write the `.tiff`).

I attached below an example with screenshot of the resulting tiles I read.

```python3
subsamplings = (1, 2, 4)
with tifffile.TiffWriter(file_path, bigtiff=True) as outtif:
    options = dict(
        photometric="rgb",
        tile=(1024, 1024),
        metadata={},
    )

    # Convert mpp to pixels per centimeters
    base_res = int(1 / input_image_mpp * 10_000)

    for i in range(len(subsamplings)):

        this_res = base_res / subsampling
        kwargs = {}
        if i == 0:
            kwargs['subifds'] = len(subsamplings) - 1
        else:
            kwargs['subfiletype'] = 1
            pass
        outtif.write(
            img_array[::(2 ** i), ::(2 ** i)],
            subfiletype=1,
            subifds=None,
            resolution=(this_res, this_res, "CENTIMETER"),
            **options,
            dtype=np.uint8
        )
```

And the code I use to read the resulting image:
```python3
slide = openslide.open_slide(file_path)
good_image = slide.read_region((2048, 2048), 1, (1024, 1024))
bad_image = slide.read_region((2048, 2048 + 1), 1, (1024, 1024))

```
The good image below
![good_image](https://user-images.githubusercontent.com/72745434/200652524-8b6c011a-c842-4762-856a-ffa8613fb158.png)
The bad image here, where coordinates were just shifted one pixel rightward
![bad_image](https://user-images.githubusercontent.com/72745434/200652608-ae8219bb-aa2a-4bb1-8732-fddd2a9cc5a9.png)

**Comment by cgohlke** [comment]
Try to set `subfiletype=None` on the first page.

Does OpenSlide require the sub-resolutions to be of certain size, e.g. rounded to nearest or up instead of rounded down after division by 2, 4, etc? Try to match the `resolution` value to the resizing/rounding method used.

**Comment by rdbs-oss** [comment]
Thank you for the advice.

I tried setting `subfiletype=None` on the first page, but it does not solve the issue. I digged into openslide-compatible slides and could not find any clear relationship between resolution and image size.  
I paste below a MRE with skimage data:
Note that the input (level-0) image is 512 (power of 2) and the base resolution is 128 px / cm (power of 2), so there are no risks of rounding errors / resolution issues.

```python3
from skimage.data import astronaut
import tifffile
import numpy as np
import openslide
import matplotlib.pyplot as plt

img_array = astronaut()
base_res = 128 # 128 px / cm

subsamplings = 3
H, W, C = img_array.shape
with tifffile.TiffWriter("/tmp/astronaut.tif", bigtiff=True) as outtif:
    options = dict(
        photometric="rgb",
        tile=(128, 128),
        metadata={},
    )

    for i in range(subsamplings):

        data = np.ascontiguousarray(img_array[::(2 ** i), ::(2 ** i)]).astype(np.uint8)
        this_res = base_res / (2 ** i)
        outtif.write(
            data,
            subfiletype=1,
            subifds=None,
            resolution=(this_res, this_res, "CENTIMETER"),
            **options,
            shape=data.shape,
            dtype=np.uint8
        )

slide = openslide.open_slide('/tmp/astronaut.tif')
f, ax = plt.subplots(ncols=2)
ax[0].imshow(slide.read_region((0, 1), 0, (512, 512)))
ax[1].imshow(slide.read_region((0, 1), 1, (255, 255)))
f.show()
```

Which should produce something like this:
![iTerm2 uHwWSb plot](https://user-images.githubusercontent.com/72745434/200793067-8cce34fa-7fd8-4e37-a6b7-2413efda4c3d.png)

(Maybe it is worth opening a proper issue for that ?)

**Comment by cgohlke** [comment]
Thanks for the standalone example. It works as expected on my system with openslide-python-1.2.0 and openslide-win64-20220811.

**Comment by 464hee** [comment]
> 

Therefore, it is OK to update the dependency library, right

**Comment by 464hee** [comment]
> Thank you very much for taking the time to look into it. The bug is not due to `tifffile` but to `openslide` (more precisely: to one of `openslide`'s dependencies: `pixman` whose version 0.38 is buggy).
> 
> thanks a lot

Therefore, it is OK to update the dependency library, right @rdbs-oss

**Comment by rdbs-oss** [comment]
I am not sure to understand, are you talking about `tifffile`'s dependency list ?
The faulty library in my example is the `pixman` library, which is not a dependency of `tifffile`, but of `openslide`.
The issue has already been identified by other `openslide` users (see [this issue](https://github.com/openslide/openslide-python/issues/114) for instance).
