### ISSUE TITLE
Got damaged .tif from .svs

### ISSUE THREAD

**Issue by HanyingYan** [cgohlke/tifffile#160]
Hi @cgohlke,

I have a series of .svs images that I would like to convert into .tiff. Most of them are small (less than 300MB) and I got .tif using your tifffile package without any problem.
```
image = tifffile.imread(svs_file)
tifffile.imwrite(tif_file, image, photometric='rgb')

```

However, there is one .svs  file of size ~4GB. I first read with `tifffile.imread` and image is of size around 50GB. Then when I tried to write the .tif file, which ended up generating a damaged file that I couldn't open, without any error or warning message. 
<img width="1126" alt="image" src="https://user-images.githubusercontent.com/47466577/198713698-d1ae10d7-fc93-42b3-9fd4-da6ebd4da406.png">

![image](https://user-images.githubusercontent.com/47466577/198713854-433a8fc9-640d-46bb-b6b9-b30c98a6308d.png)

I wonder if you know what happened and what I can do to solve this issue. 

Thank you!
Hanying

**Comment by cgohlke** [comment]
The 50 GB array is written in BigTIFF format as one contiguous segment. I don't think the file is corrupt (check if you can read it back with tifffile). Either the Preview app does not support the BigTIFF format or it has a size limit (e.g., to prevent DOS or RAM exhaustion).

**Comment by HanyingYan** [comment]
Thank you for your quick response! Yes, you are correct! The .tif generated is of size 54G and can be read back with tifffile. In this case, I think everything works fine and it's just Preview couldn't load image of this large size. Thanks :)

**Comment by cgohlke** [comment]
Btw, such large images are typically stored using compressed tiles (`tiles=(512, 512), compression=...`).

**Comment by HanyingYan** [comment]
Oh, I see. Let me give it a try! Thank you!
