### ISSUE TITLE
imwrite python function

### ISSUE THREAD

**Issue by k1moradi** [cgohlke/tifffile#161]
`compression: COMPRESSION | int | str | None = None,`

should change to 

`compression: COMPRESSION | int | str | None | tuple[str, int] = None,`

**Comment by cgohlke** [comment]
`compression: tuple[str, int]` is deprecated and no longer documented. Use `compressionargs`, e.g.,

https://github.com/cgohlke/tifffile/blob/a73812e98f58b068a590de862ed547820fd332ad/tifffile/tifffile.py#L480-L481
