### ISSUE TITLE
ValueError: invalid tile shape

### ISSUE THREAD

**Issue by gsakkis** [cgohlke/tifffile#162]
I'm trying to rewrite the attached OME-TIFF  [CMU-1-Small-Region.ome.zip](https://github.com/cgohlke/tifffile/files/9990268/CMU-1-Small-Region.ome.zip) using the code posted [here](https://github.com/cgohlke/tifffile/issues/156#issuecomment-1274996473) and getting `ValueError: invalid tile shape`. The file was generated by converting [CMU-1-Small-Region.svs](https://openslide.cs.cmu.edu/download/openslide-testdata/Aperio/CMU-1-Small-Region.svs) to OME-Zarr via [bioformats2raw](https://github.com/glencoesoftware/bioformats2raw) and then converting the latter to OME-TIFF by [raw2ometiff](https://github.com/glencoesoftware/raw2ometiff).

Running the rewrite code with the debugger I see that `keyframe.tile == (768, 574)`, which triggers one condition for the ValueError, namely that a tile dimension is not divisible by 16. Is this condition necessary? If yes, is this a bug in `bioformats2raw`?

**Comment by cgohlke** [comment]
The TIFF specification is quite clear that `TileWidth` and `TileLength` must be a multiple of 16. In addition, if DCT-based JPEG compression is used, they are required to be a multiple of 8 times the largest sampling factor.

**Comment by gsakkis** [comment]
Thanks for the information, I'll open an issue to `bioformats2raw` then.
