### ISSUE TITLE
Write huge data with low memory

### ISSUE THREAD

**Issue by lingdu0001** [cgohlke/tifffile#163]
I want to write a huge data into tif with low memory, is  there any way to do that？

**Comment by cgohlke** [comment]
Use memory-mapping, generators of tiles or pages, or zarr, e.g.:

https://github.com/cgohlke/tifffile/blob/a73812e98f58b068a590de862ed547820fd332ad/tifffile/tifffile.py#L521-L534

https://github.com/cgohlke/tifffile/blob/a73812e98f58b068a590de862ed547820fd332ad/tifffile/tifffile.py#L574-L588

https://github.com/cgohlke/tifffile/blob/a73812e98f58b068a590de862ed547820fd332ad/tifffile/tifffile.py#L696-L712
