### ISSUE TITLE
Is there any way to create a TIFF file from a generator which is in a callback?

### ISSUE THREAD

**Issue by Altermoe** [cgohlke/tifffile#164]
Like this:

```python
def tiles():
    def on_tile_output(tile: cv.Mat):
        yield tile

    # this is an image fusion task
    fusion = ImageFusion()
    fusion.on('tile_output', on_tile_output)

tifffile.imwrite(
    'temp.tiff',
    tiles(),
    tile=(128, 128),
    shape=(35000, 35000),
    dtype=np.uint8,
)
```

**Comment by cgohlke** [comment]
That's more a general programming question, not really specific to tifffile. Try the solution to [StackOverflow: Turn functions with a callback into Python generators?](https://stackoverflow.com/a/9968886/453463). You might want to disable multi-threading in tifffile, i.e., set `maxworkers=1`.

**Comment by Altermoe** [comment]
> That's more a general programming question, not really specific to tifffile. Try the solution to [StackOverflow: Turn functions with a callback into Python generators?](https://stackoverflow.com/a/9968886/453463). You might want to disable multi-threading in tifffile, i.e., set `maxworkers=1`.

Thanks for your replying, it totally solved my problem!
