### ISSUE TITLE
Unable to create a multi-channel image

### ISSUE THREAD

**Issue by lingdu0001** [cgohlke/tifffile#165]
I want to create a six-channel tiff image , and tested the codes in ReadMe as followings.
The file was successfully generated, but an error was reported when the file was dragged to qupath。

![image](https://user-images.githubusercontent.com/5213652/203942186-b30ad2da-555b-4bc1-b888-1fee5706df90.png)

data = numpy.random.randint(0, 1023, (8, 2, 512, 512, 3), 'uint16')
subresolutions = 2
pixelsize = 0.29  # micrometer
with TiffWriter('temp.ome.tif', bigtiff=True) as tif:
    metadata = {
        'axes': 'TCYXS',
        'SignificantBits': 10,
        'Channel': {'Name': ['Channel 1', 'Channel 2']},
        'TimeIncrement': 0.1,
        'TimeIncrementUnit': 's',
        'PhysicalSizeX': pixelsize,
        'PhysicalSizeXUnit': 'µm',
        'PhysicalSizeY': pixelsize,
        'PhysicalSizeYUnit': 'µm',
    }
    options = dict(
        photometric='rgb',
        tile=(128, 128),
        compression='zlib',
        resolutionunit='CENTIMETER'
    )
    tif.write(
        data,
        subifds=subresolutions,
        resolution=(1e4 / pixelsize, 1e4 / pixelsize),
        metadata=metadata,
        **options
    )
    # save pyramid levels to the two subifds
    # in production use resampling to generate sub-resolution images
    for level in range(subresolutions):
        mag = 2 ** (level + 1)
        tif.write(
            data[..., ::mag, ::mag, :],
            subfiletype=1,
            resolution=(1e4 / mag / pixelsize, 1e4 / mag / pixelsize),
            **options
        )
    # add a thumbnail image as a separate series
    # it is recognized by QuPath as an associated image
    thumbnail = (data[0, 0, ::8, ::8] >> 2).astype('uint8')
    tif.write(thumbnail, metadata={'Name': 'thumbnail'})

**Comment by cgohlke** [comment]
The file is valid. Looks like QuPath does not support multi-channel RGB images. If you think that's a bug, report it to the QuPath developers. If possible, use grayscale channels:
```
import numpy
from tifffile import TiffWriter

data = numpy.random.randint(0, 1023, (8, 6, 512, 512), 'uint16')
subresolutions = 2
pixelsize = 0.29  # micrometer

with TiffWriter('temp.ome.tif', bigtiff=True) as tif:
    metadata={
        'axes': 'TCYX',
        'SignificantBits': 10,
        'Channel': {'Name': ['Ch 1', 'Ch 2', 'Ch 3', 'Ch 4', 'Ch 5', 'Ch 6']},
        'TimeIncrement': 0.1,
        'TimeIncrementUnit': 's',
        'PhysicalSizeX': pixelsize,
        'PhysicalSizeXUnit': 'µm',
        'PhysicalSizeY': pixelsize,
        'PhysicalSizeYUnit': 'µm',
    }
    options = dict(
        photometric='minisblack',
        tile=(128, 128),
        compression='zlib',
        resolutionunit='CENTIMETER'
    )
    tif.write(
        data,
        subifds=subresolutions,
        resolution=(1e4 / pixelsize, 1e4 / pixelsize),
        metadata=metadata,
        **options
    )
    # save pyramid levels to the two subifds
    # in production use resampling to generate sub-resolution images
    for level in range(subresolutions):
        mag = 2**(level + 1)
        tif.write(
            data[..., ::mag, ::mag],
            subfiletype=1,
            resolution=(1e4 / mag / pixelsize, 1e4 / mag / pixelsize),
            **options
        )
    # add a thumbnail image as a separate series
    # it is recognized by QuPath as an associated image
    thumbnail = (data[0, 0, ::8, ::8] >> 2).astype('uint8')
    tif.write(thumbnail, metadata={'Name': 'thumbnail'})
```

**Comment by lingdu0001** [comment]
Thank you very much. I have another question.

**Comment by cgohlke** [comment]
> How to change the color of " Ch 1 "to Blue?

Double click on the "Ch 1" row and change the channel color to blue.

Please as QuPath related questions on the https://forum.image.sc forum.
