### ISSUE TITLE
Create pyramidal page when writting TIFF with generator tiles

### ISSUE THREAD

**Issue by Altermoe** [cgohlke/tifffile#166]
Hi.

I am trying to create a large TIFF file through some scanning image (30MB * 700), with no more than 4GB avaliable memory.
The answer of issue #163 which mention generators tiles works awesome for me.

But there's a question, I can't cache previous image due to low memory.

So I tried the following two methods:
1. Finished writting -> Closed TiffWriter -> Opened the tiff -> Created full pyramidal page with downsample 2 and cached it -> Closed the tiff -> Opened with TiffWriter -> Wrote pyramidal page in append mode -> Cycled above operations with downsample 4, 8, 16
2. Created tiles with downsample 2, 4, 8, 16, and cached in file when First writting -> Wrote pyramidal page with those generator tiles in append mode

Both above methods looks ugly. Is there other way to write pyramidal page with generator tiles?

Thank you.

**Comment by cgohlke** [comment]
The most straightforward way is probably to keep the base level in a memory mapped numpy array on a local disc and generate tiles from it. Fast local storage (NVMe) can reach in the order of 1/10 of RAM speed.

Generation of pyramids, especially under low memory constraints, is out of the scope of this library. There are probably publication on that matter. [Libvips](https://www.libvips.org/) is known to be very efficient at this. Maybe their algorithm can be adapted...
