### ISSUE TITLE
is there a cpp version tifffile to write tiff or svs file except libtiff as it is pretty slow

### ISSUE THREAD

**Issue by zhusihan-python** [cgohlke/tifffile#168]
Question:
is there a cpp version tifffile to write tiff or svs file except libtiff as it is pretty slow?
the TIFFWriteEncodedStrip is slow according to my test, but tiffile gen svs from a numpy array is pretty fast, 
any help would be appreciated!

**Comment by cgohlke** [comment]
Tifffile is a "pure Python" library. Compression is handled by [imagecodecs](https://github.com/cgohlke/imagecodecs) and multi-threaded by tifffile.

Consider [libvips](https://www.libvips.org/), which is one of the most efficient libraries around.
