### ISSUE TITLE
Creating a multi-page BigTiff file

### ISSUE THREAD

**Issue by dlasusa** [cgohlke/tifffile#169]
I'm trying to create a multi-page BigTiff file.

I've got it kinda working:
```py
from pathlib import Path
from tifffile import TiffWriter, imread

with TiffWriter('temp.tif', bigtiff=True) as tif:
    for file in Path('C:\\Path_to_files\\').glob('*.tif'):
        print(file.name)
        img = imread(file)
        tif.write(img)
```
In my for loop, the print statement prints every file (as expected), but my final multipage tif only has the first 3 pages (5 images are in the input folder).  Which makes me think my loop is ok, but how I'm reading the input file or writing to the output file is wrong?  But then why does it work at all?  Why do I simply get 3 pages?

I'm not getting any errors.

My Environment:
```
Windows 10
Python 3.11.0 (in a python venv)

Package    Version
---------- ----------
numpy      1.23.5
pip        22.3.1
setuptools 65.5.0
tifffile   2022.10.10
tiffile    2018.10.18
```

I'm not sure what I'm doing wrong.  Any input would be appreciated.  Thanks!

**Comment by cgohlke** [comment]
How do you count the pages in the output file? What does the following code print?
```
with TiffFile('temp.tif') as tif:
    for page in tif.pages:
        print(page)
```

**Comment by dlasusa** [comment]
I had been using `IrfanView` but using the code you provided, it does indeed look like all 5 pages are there!

Output:
```
TiffPage 0 @16  3979x2979x3  uint8  rgb shaped memmappable
TiffPage 1 @35560724  3878x2962x3  uint8  rgb shaped memmappable 
TiffPage 2 @70021012  3863x2895x3  uint8  rgb shaped memmappable 
TiffPage 3 @103571548  3863x2932x3  uint8  rgb shaped memmappable
TiffPage 4 @137550868  3863x2865x3  uint8  rgb shaped memmappable
```

Thanks for the super quick response!  I should have thought to programmatically check the pages and not rely on outside software.

Thank you also for a great utility!
