### ISSUE TITLE
Character encoding

### ISSUE THREAD

**Issue by damianbrzoza** [cgohlke/tifffile#17]
Hi!

I am working on images from microscopes and I noticed that biological software not always following strict to TIFF specification (ASCII encoding). Now with forcing ASCII encoding in the output image I lose some valuable data. It's will be great if output's encoding can be change by developer.

Please, consider another parameter to the save function.

**Comment by cgohlke** [comment]
You can provide your own encoded bytes instead of str (e.g. `imwrite(filename, data, description='micron \xB5'.encode('latin-1'))`) but can't expect TIFF readers, including tifffile, to read the string back correctly.

**Comment by damianbrzoza** [comment]
Nice workaround! It's work for me. Thanks :+1:
