### ISSUE TITLE
Pre-encoded image tiles

### ISSUE THREAD

**Issue by AlexanderWinterl** [cgohlke/tifffile#170]
Hello

I want to write stacks of jpeg compressed images into a tiff stack, but I perform the jpeg compression outside tifffile (working on a device with a hardware encoder, that increases compression speed between 5-10 times).
Some parts of the inline doc mention support for pre-compressed tiles, however I could only manage to implement this in one release (2021.7.2). 

```
with tifffile.TiffWriter('temp.tif') as tif:
    for image in images:
        tif.write(
            [JC.encodeRGB(image)], # JC.encodeRGB takes a 3 dim uint8 image array (H,W,3) and returns the jpeg as bytes
            photometric='rgb',
            compression='jpeg',
            tile=im_shape[:2],
            shape=im_shape,
            dtype="uint8",
        )
```
The current version (2022.10.10) will throw a ValueError in line 1883 of tifffile.py:
```
dataarray = numpy.asarray(data, datadtype, 'C')
ValueError: invalid literal for int() with base 10: b'\xff\xd.....
```
On the other hand the support for pre-compressed tiles is already there a layer deeper in encode_tiles line 20383 to 203391
```
    numtiles -= 1
    tile = next(tileiter)
    if isinstance(tile, bytes):
        # pre-encoded
        yield tile
        for _ in range(numtiles):
            tile = next(tileiter)
            # assert isinstance(tile, bytes)
            yield tile  # type: ignore
            del tile
        return
```
Am I just not using pre-compressed tiles properly here?

Best regards
Alex

**Comment by cgohlke** [comment]
Use a generator that returns all compressed tiles as bytes (type `Iterator[bytes]`). Also make sure the `photometric`, `subsampling`, and `jpegtables` tags are correct. E.g. set `photometric='ycbcr'` and `subsampling=...` if the jpeg encoder is using ycbcr colorspace and subsampling.

https://github.com/cgohlke/tifffile/blob/a73812e98f58b068a590de862ed547820fd332ad/tifffile/tifffile.py#L1514-L1520

https://github.com/cgohlke/tifffile/blob/a73812e98f58b068a590de862ed547820fd332ad/tifffile/tifffile.py#L1569-L1586

**Comment by AlexanderWinterl** [comment]
Thank you! That worked perfectly.
