### ISSUE TITLE
add support to `memmap` to take in a list of tiff files with compatible shapes

### ISSUE THREAD

**Issue by kushalkolar** [cgohlke/tifffile#172]
It might be useful to add support to `memmap` to take in a list of tif files of compatible shapes and return a `numpy.memmap` with a shape representing concatenation along one of the axes. I could create a wrapper class for my own use cases but I thought I'd post here because this type of functionality might be useful to other users. I could help implement it (no timeline though) if you think it's worth having.

**Comment by cgohlke** [comment]
This should already be possible with `TiffSequence(...).asarray(out='memmap')` but is not available through the `memmap` function.

**Comment by kushalkolar** [comment]
Thanks for the fast response! I just tried this and there is a noticeable memory footprint where it seems to be opening each file in RAM as its iterating through the sequence. By creating a wrapper class I was thinking of mapping slices passed to the wrapper instance `__getitem__` to the corresponding memmap from a list of memmaps

**Comment by kushalkolar** [comment]
(does this functionality already exists or is of interest to tifffile)

**Comment by cgohlke** [comment]
It is currently not possible to pass through an `out` argument from `FileSequence.asarray` to the `imread` function. I'll add it to the next version. Maybe an option can be added to decode directly to the final memory mapped array if the `imread` function is known to support it...
Anyway, for most cases it would be better to map the segments in each file of the sequence as a zarr store. This is currently only possible for multi-file OME-TIFF or via generating fsspec reference files. A general solution would require support for zarr sharding...

**Comment by cgohlke** [comment]
Should be fixed in version 2023.1.23.
