### ISSUE TITLE
The logic of judging OME is too rough

### ISSUE THREAD

**Issue by Silver-Fang** [cgohlke/tifffile#173]
https://github.com/cgohlke/tifffile/blob/a73812e98f58b068a590de862ed547820fd332ad/tifffile/tifffile.py#L9205
This code verifies OME-XML based solely on whether it ends exactly with the 4 characters "OME>", which is too crude. Many XML generation libraries (e.g. pugixml) append an additional line break at the end of the XML text, and this single one newline character will cause the tifffile library to not recognize OME-XML.
My suggestion is to call a professional xml library here to judge legitimacy.

**Comment by cgohlke** [comment]
Fixed in the dev version. For now just override the `is_ome` property.
