### ISSUE TITLE
ValueError: <COMPRESSION.JBIG: 34661> not supported

### ISSUE THREAD

**Issue by khanfarhan10** [cgohlke/tifffile#175]
Is there any support for JBIG compression type in the tifffile library?

Or am I just missing something from the documentation?

@cgohlke Kindly help.

Platform : Linux

Minimum reproducable code example:
```python
from tifffile import TiffFile
from PIL import Image
fname = "temp/input/tifs/MultipleFormats.tif"

page_num = 4

with TiffFile(fname) as tif_file:
    page_pil = Image.fromarray(tif_file.pages[page_num].asarray())
```

[Document Attached here](https://www.leadtools.com/support/forum/resource.ashx?a=545&b=1).

NOTE : This multipage document contains multiple tiff formats as provided in [this LeadTools discussion](https://www.leadtools.com/support/forum/posts/t10960-).

**Comment by cgohlke** [comment]
JBIG compression is not supported by tifffile/imagecodecs. Fax and bi-level images are not a focus of this library and the license of the "reference" JBIG-KIT library restricts it from being used in tifffile/imagecodecs.

**Comment by khanfarhan10** [comment]
Thanks for the incredibly fast response.

Is there any workaround open source library (without licensing issues) that can be looked upon for reading the particular image @cgohlke  ?

Edits - Have re-attached the document and provided the error traceback above.

P. S. - Great & Easy to use library to work with tiffs! Absolutely love it! ❤️

**Comment by cgohlke** [comment]
I don't know any software that can decode all pages in that file. I guess software based on LeadTools could. 

One option is to build libtiff with jbig-kit from source and use the tiffcp tool to convert the TIFF file to another compression scheme. Maybe some linux distributions contain such a build? Another option is to extract the compressed strips from the TIFF and decode them with jbigkit Python bindings https://pypi.org/project/jbigkit-py/ ...

**Comment by cgohlke** [comment]
Here's an example of decoding JBIG compressed segments in a TIFF file using the jbigkit-py library:

```python
"""Plot all JBIG compressed images in TIFF file."""

import numpy
import tifffile
import imagecodecs
import jbigkit  # GPL license

filename = 'MultipleFormats.tif'

with tifffile.TiffFile(filename) as tif:
    for page in tif.pages:
        if page.compression != tifffile.COMPRESSION.JBIG:
            continue
        assert page.planarconfig == 1

        for offset, bytecount in zip(page.dataoffsets, page.databytecounts):
            tif.filehandle.seek(offset)
            jbg_data = tif.filehandle.read(bytecount)

            decoder = jbigkit.JbgDecoder()
            status, processed_len = decoder.decode_in(jbg_data)
            assert status == jbigkit.JbgErrno.EOK
            assert processed_len == len(jbg_data)
            assert decoder.get_width() == page.imagewidth
            assert decoder.get_height() == page.imagelength
            assert decoder.get_planes_num() == 1

            image = numpy.frombuffer(decoder.get_plane(0), page.dtype)

            if page.bitspersample == 1:
                image = imagecodecs.packints_decode(
                    image,
                    page.dtype,
                    page.bitspersample,
                    page.imagewidth * page.samplesperpixel,
                )
            image = image.reshape(page.shape)

            tifffile.imshow(image, show=True)
```

**Comment by khanfarhan10** [comment]
This is exactly what I needed.

Lovely, thanks for the extended help! I really appreciate it!
