### ISSUE TITLE
Tiff files operations

### ISSUE THREAD

**Issue by PasaOpasen** [cgohlke/tifffile#176]
I did not find information about next operations with .tiff files (without loading them as arrays to memory, decompress and so on):
* splitting files by pages
* union files into one

Is it possible?

**Comment by cgohlke** [comment]
Consider the [tifftools](https://github.com/DigitalSlideArchive/tifftools) library instead. It is made for those use cases.

Tifffile has no high level functions or scripts to split or merge TIFF files. There are many existing tools (e.g., libtiff or ImageMagick executables) to do that. 

See the [tifffile examples](https://github.com/cgohlke/tifffile#examples) for how to access TIFF properties without decompressing any image data.
