### ISSUE TITLE
Tests are missing

### ISSUE THREAD

**Issue by mgorny** [cgohlke/tifffile#177]
b8f1e74463418860925fd76a2775bdc84cccd553 removed `test_tifffile.py` and b350140736008ec39ce5f302f9c0eb50f6427091 suggests that a `test` or `tests` directory was meant to be added in its place but such a directory was never added to the repository. FWICS, there are currently no tests to be found. Could you please add them?

**Comment by cgohlke** [comment]
Fixed in [v2023.1.23.1](https://github.com/cgohlke/tifffile/releases/tag/v2023.1.23.1)

**Comment by mgorny** [comment]
Thank you!
