### ISSUE TITLE
Tifffile cannot read MPP attributes, but openslide can

### ISSUE THREAD

**Issue by 464hee** [cgohlke/tifffile#181]
<tifffile.TiffTag 270 @829688804> coercing invalid ASCII to bytes

Here is the link to my file：
https://drive.google.com/file/d/1ctw5-oxXxtXYdGXnSO-AFFcW5OuMm8eV/view?usp=share_link

**Comment by cgohlke** [comment]
Cross posted from https://github.com/bayer-science-for-a-better-life/tiffslide/issues/65

At least one ImageDescription tag is corrupted and does not contain ASCII characters as required by the TIFF specification. 

Tifffile actually tries to decode the tag value as UTF-8 and cp1252, both of which also fails.

The hexdump shows garbage at the end of the ImageDescription tag (note the `8d` character:
```
00: 41 70 65 72 69 6f 20 46 6f 72 6d 61 74 20 53 63 61 6e 6e 65 64 20 42 79 20 4b 46 42 Aperio Format Scanned By KFB
1c: 49 4f 0d 0a 37 34 30 30 34 78 34 34 32 36 39 20 5b 30 2c 30 20 37 34 30 30 34 78 34 IO..74004x44269 [0,0 74004x4
38: 34 32 36 39 5d 20 28 32 35 36 78 32 35 36 29 2c 20 4a 50 45 47 2f 52 47 42 20 51 3d 4269] (256x256), JPEG/RGB Q=
54: 33 30 7c 41 70 70 4d 61 67 20 3d 20 32 30 7c 4d 50 50 20 3d 20 30 2e 34 38 34 34 39 30|AppMag = 20|MPP = 0.48449
70: 38 7c 55 73 65 72 20 3d 20 4b 46 50 42 4c 30 32 30 30 30 31 31 30 30 32 32 7c 54 69 8|User = KFPBL02000110022|Ti
8c: 6d 65 20 3d 20 31 38 3a 31 31 3a 30 37 7c 54 69 6d 65 2d 55 73 65 64 20 3d 20 03 28 me = 18:11:07|Time-Used = .(
a8: 3a 2e 29 3a 8d 2c 00                                                                :.):.,.
```

Check the software used to write the file.

**Comment by 464hee** [comment]
感谢你的回复
