### ISSUE TITLE
Reading and Writing requiring different shapes of images.

### ISSUE THREAD

**Issue by deepushajia** [cgohlke/tifffile#182]
I have a multi-page tifffile which I am planning to split to n chunks. The shape of image in each page as:
(2339, 1653, 4)
But when I try to append this same page (using page.asarray()) into one of the chunks, the number of pages of the output file comes out to be different (>10000).
So I reshape the dimension to (4, 2339, 1653) before saving the page. This works but I need to have it  revert back to the original file dimensions.

**Comment by cgohlke** [comment]
Please provide a minimal reproducible example. 

Could it be that the `(2339, 1653, 4)` images are written as grayscale with `photometric='minisblack'`? In that case there will be `2339` pages of `(1653, 4)` images.
