### ISSUE TITLE
Is mmstack parsing reliable?

### ISSUE THREAD

**Issue by SeanLeRoy** [cgohlke/tifffile#186]
Hi, I have an mmstack TIFF file with I believe 2 scenes (series) and when accessing the second scene in the series produced by `tifffile==2023.3.15` I get an index error since the series output by `tifffile` only has one scene in it. I assume this is due to the addition of `mmstack` in the parsers in version `2023.3.15` since `2023.2.28` produces a series with 2 scenes and I am able index them accordingly. [I noticed this snippet](https://github.com/cgohlke/tifffile/blob/fc5f5a4eea5d510e7592a84f9c1017265e718cca/tifffile/tifffile.py#L270-L274) (specifically "...The TIFF structures and metadata
  are often corrupted or wrong.. ") which has me curious whether mmstack files are to be trusted?

**Comment by cgohlke** [comment]
Older versions of tifffile used the OME-XML metadata to create series. In the OME model, positions are separate series. The new MMStack parser uses MicroManager metadata to create series. The positions are now part of a single series. It's a breaking change. Maybe this explains your issue?

**Comment by SeanLeRoy** [comment]
I believe it does, thank you!

**Comment by cgohlke** [comment]
> whether mmstack files are to be trusted

See the discussion at https://github.com/czbiohub/iohub/issues/66#issuecomment-1449399620 and below for the type of corruptions found in MMstack files.
