### ISSUE TITLE
Preserving singlet dimensions when loading ImageJ hyperstack tifs

### ISSUE THREAD

**Issue by nhthayer** [cgohlke/tifffile#19]
Noticed a change in behavior between 2019.5.30 -> 2019.6.18 and wanted to make sure it was intended. Hopefully I'm just missing a new way of preserving dimensions of size 1 when loading ImageJ hyperstack tifs. 

```python
# works on tifffile==2019.5.30
# assert fails on tifffile==2019.6.18
import numpy as np
import tifffile
a = np.zeros((10, 5, 1, 256, 256), dtype='uint16')
md = {'frames': 10, 'slices': 5, 'channels': 1}
tifffile.imsave('test.tif', a, imagej=True, metadata=md)
b = tifffile.imread('test.tif')
assert b.shape == a.shape, f'Loaded array has shape {b.shape}, not {a.shape}'
```

In the new version, it appears that dimensions of size 1 are not included in the final stack shape, even if they are specified in the imagej metadata:

https://github.com/cgohlke/tifffile/blob/6991c4ba1a1d1936cfad1bb249d1c74de08d449b/tifffile/tifffile.py#L2630-L2648

In the older version, the channel dim would be included if it was specified in the metadata:

https://github.com/cgohlke/tifffile/blob/ffbdf61b9c7cc627d17260d2cfd25c053001b0fc/tifffile/tifffile.py#L2526-L2529

**Comment by cgohlke** [comment]
That is intended. AFAIK ImageJ does not write `channels`, `slices`, or `frames` if they are 1. Tifffile determines `images`, `channels`, `slices`, `frames` from the array shape and does not let users overwrite them using metadata. The singlet dimensions can be recovered using the axes property of ImageJ series, e.g with the `transpose_axes` function.

https://github.com/cgohlke/tifffile/blob/987083705d1d988da2f27a3fb40784963cb2dab9/tifffile/tifffile.py#L12547-L12570

**Comment by nhthayer** [comment]
Thank you for the clarification. 

I tend to read/write 5D tifs with Tifffile, and keeping the same dimensions when saving/loading is important to me. I know this can be achieved by omitting the `imagej=True` in `tifffile.imsave`. 

I had been using the `imagej` option so tifs would open as a hyperstack if I needed to visually inspect any of the data with ImageJ. I guess I had been more tolerant of singlet dimensions being squeezed when interactively viewing the data. 

Do you have any suggestion on how this can be achieved now - creating a tif that would load with the "correct dimensions" with only `tifffile.imread` and still open as a hyperstack in ImageJ? The ability to include other ImageJ metadata (lookup tables, min/max settings, etc.) would be a plus. 

Also, feel free to close the issue, as maybe this is getting beyond the scope of your project.

**Comment by cgohlke** [comment]
Using `transpose_axes` should be able to achieve what you want. E.g.:

```Python
def imread(filename):
    with TiffFile(filename) as tif:
        axes = tif.series[0].axes
        hyperstack = tif.series[0].asarray()
    return transpose_axes(hyperstack, axes, 'TZCYXS')
```

**Comment by nhthayer** [comment]
That would definitely work for me, but I think I will opt for preserving the singlet dimensions by giving up the `imagej` option. 

I was hoping for a `.tif` that would open as a hyperstack in ImageJ and preserve the dimensions when loaded with the native `tifffile.imread` function. However, I appreciate that the new behavior replicates what ImageJ does and actually allows you to use `frames`, `slices` and `channels` as keys in the metadata and still open the file! 

Thank you for your help and the time that you put into this!

**Comment by AndrewGYork** [comment]
I have the same problem as nhthayer; I want to save and load 5d numpy arrays that open as hyperstacks in imagej, and don't drop singlet dimensions. I guess I can redefine imread in every script I have that uses tifffile, but it seems like the old behavior was strictly superior. What am I missing?

(Disclaimer: I deeply appreciate the work you put into tifffile, and I know you don't owe me your valuable labor for free. I hope my question isn't annoying, and I hope my appreciation and respect for your work is clear.)

**Comment by cgohlke** [comment]
IIUC you want an option to include e.g. `channels=1` in the ImageJ file and have tifffile return the singlet dimension in the array when reading, even tough ImageJ itself is unable to produce such files and probably no other software will keep the dimension?

**Comment by AndrewGYork** [comment]
This was the old behavior, right? Load(save(x)).shape == x.shape, and if you open the file in imagej, it opens as a hyperstack.

I think this use case is fairly common: tif as basically numpy arrays on disk, with easy casual inspection via imagej, but for any serious work you load back to python.

**Comment by cgohlke** [comment]
I am -1 on extending the ImageJ format for tifffile. Maybe an option `squeeze=False` in the reader, which returns axes of length one instead of squeezing them out? That would apply to formats with defined axes order, e.g. ImageJ, OME-TIFF, and LSM files. Basically a convenience to avoid calling transpose_axes...
