### ISSUE TITLE
Reading the whole images stack as NumPy array not working

### ISSUE THREAD

**Issue by naourass** [cgohlke/tifffile#191]
I'm using tifffile v2023.3.21. When I `imread()` a multi-pages tiff file, it returns the first page only instead of a stack of all the images.

```
stack = imread("my_file_path")  # multi-pages tiff
print(stack.shape)  # returns (height, width)
```

In v2023.2.3, I was using it without any problem to split and save a tiff (`stack[start:end, ...]`).

Am I missing something?

**Comment by cgohlke** [comment]
Please share a file to reproduce the issue.

Are there any messages/warnings printed on the console?

This is probably due to the addition of the Micro-Manager MMStack parser:

https://github.com/cgohlke/tifffile/blob/fbe8976d8602b0a3ac7866a4271678a7f71e8f0a/tifffile/tifffile.py#L123

**Comment by naourass** [comment]
Thanks for the quick reply @cgohlke!

I'm going to create a minimal example, double check, and update the issue.

**Comment by naourass** [comment]
@cgohlke
Attached is a sample tiff file to reproduce the issue.

Please replace `.gif` extension with `.tiff` _(sorry github doesn't accept `.tiff` upload so I've just manually edited the extension)_.

BTW, the file was generated using the following function to simulate/mimic my real life use case:
```
def generate_tiff():
    for i in range(1, 10):
        width, height = 550, 800
        image = Image.new("L", (width, height), "white")
        draw = ImageDraw.Draw(image)
        text = f"Page {i}"
        text_width, text_height = draw.textsize(text)
        draw.text(((width - text_width) // 2, (height - text_height) // 2), text, fill="black")
        if i == 1:
            tifffile.imwrite(
                "stack_read_sample.tiff",
                np.array(image),
                photometric="minisblack",
                compression="zlib"
            )
        else:
            tifffile.imwrite(
                "stack_read_sample.tiff",
                np.array(image),
                photometric="minisblack",
                compression="zlib",
                append=True,
            )
```

![stack_read_sample](https://user-images.githubusercontent.com/4897498/229319934-5d694edf-9dcd-4dd6-bb29-8e0e8fd5dad1.gif)

**Comment by cgohlke** [comment]
Thanks for the file and the code.

I cannot reproduce the issue. Both versions, v2023.3.21 and v2023.2.3, give the same, correct result.

`tifffile.imwrite` writes a new "series" by default, and `imread` returns the first series by default. To disable this behavior, pass `metadata=None` to the `imwrite` call.

**Comment by naourass** [comment]
Thanks for the clarification @cgohlke!

Can you confirm that this is the right approach to create a tiff file with a first image, then append frames to it later:
```
def create_then_append(pil_images_list):
    tifffile.imwrite(
        "stack_read_sample.tiff",
        np.array(pil_images_list[0]),
        metadata=None
    )
    # ...
    for img in (pil_images_list[1:]):
        tifffile.imwrite(
            "stack_read_sample.tiff",
            np.array(img),
            photometric="minisblack",
            compression="zlib",
            append=True,
            metadata=None
        )
```

**Comment by cgohlke** [comment]
It's more efficient to keep the file open if possible, e.g.:
```python
with TiffWriter('temp.tif') as tif:
    for image in image_list:
        tif.write(image, metadata=None)
```

If all images have the same shape and dtype, try contiguous mode:
```python
with TiffWriter('temp.tif') as tif:
    for image in image_list:
        tif.write(image, contiguous=True)
```
or pass the list to imwrite (the list is converted to a numpy array intermediately):
```python
imwrite(image_list, dtype=image_list[0].dtype)
```

**Comment by naourass** [comment]
Got it. Thanks a lot for the details @cgohlke . And also many thanks for providing python with such an awesome tiff processing library!
