### ISSUE TITLE
Loading "sparse" tiff files

### ISSUE THREAD

**Issue by LMeyling** [cgohlke/tifffile#192]
Hello, 
I am currently working on a project that is currently using your library to load tiff files, with an average size of 6 mb, since there are many images that need to be loaded in it takes some time to load all the images. This is why I am looking for a faster way of loading them. 
The attribute the the images have is that they are sparse with around 95% of the pixel intensities being equal to 0. It would be sufficent to just load the other values and their coordinates. Is there any way to do this with this library or do you have any ideas on how to implement that?

Kind regards

**Comment by ziw-liu** [comment]
Zarr might help if you have completely blank (`min==max==0`) pages, but that's still a dense array. Not sure if TIFF supports a truly point-wise sparse data structure though.

**Comment by cgohlke** [comment]
What's the format of the TIFF files, e.g. compression, strip/tile sizes and numbers? 6 MB is relatively small and tifffile as a Python library has a large overhead and does not perform well with many small segments. If possible, use multiple threads and `imagecodecs.tiff_decode` instead to read large numbers of small TIFF files.
