### ISSUE TITLE
Appending to an image results in incorrect metadata and image issues

### ISSUE THREAD

**Issue by plehman2000** [cgohlke/tifffile#194]
```  
    with tifffile.TiffFile(tiff_filepath) as tiff:
        metadata = tiff.geotiff_metadata
        array = tiff.asarray()
        tifffile.imwrite("test_planet - Copy.tif", append=True,data=array)# *
```

When I append the same tiff data to the original file, it should just duplicate the image, but instead, it changes the image from the correctly colored and georeferenced version to a larger, incorrectly located/colored version:
![image](https://user-images.githubusercontent.com/54288924/230954769-e8f90fad-2981-4cea-955a-43806ecaed1e.png)
After code is run:
![image](https://user-images.githubusercontent.com/54288924/230954823-aaec7f42-310b-4660-9384-ab7d34a0a64f.png)

Also, if there is a more effective way to transition between georeferenced tiff files and images in array form, please notify me. Thanks!

**Comment by cgohlke** [comment]
Please provide a file to reproduce the corruption. 

Tifffile does not have any high level support for writing GeoTIFF files or GPS tags. Better use the GDAL or rasterio libraries for handling GeoTIFF files.
