### ISSUE TITLE
imsave/imread swap axes for 3 dimensional stack with 3 or 4 slices

### ISSUE THREAD

**Issue by ser5kovskiy** [cgohlke/tifffile#196]
I try to save a 3D stack with 3 slices as tif file. However, after saving stack and reading it there is swap axes. As I understand, if the number of slices is 3 or 4 then the stack is automatically considered RGB and RGBA, respectively. I have tried to save with photometric='MINISBLACK' (I tried it due to #100)), but it did not help.

```
import tifffile
import numpy as np
from skimage import io
tifffile.__version__
#Out: 2022.10.10

#Do not work 
data = np.random.rand(3, 10, 11)
io.imsave('temp.tif', data)
image = io.imread('temp.tif')
image.shape
#Out: (10, 11, 3)
#Desired: (3, 10, 11)

#Do not work
data = np.random.rand(3, 10, 11)
io.imsave('temp.tif', data, photometric='MINISBLACK')
image = io.imread('temp.tif')
image.shape
#Out: (10, 11, 3)
#Desired: (3, 10, 11)

#Correct work
data = np.random.rand(5, 10, 11)
io.imsave('temp.tif', data)
image = io.imread('temp.tif')
image.shape
#Out: (5, 10, 11)
```

Am I missing something?

**Comment by cgohlke** [comment]
Use tifffile's imwrite and imread. [Skimage.io is swapping axes](https://github.com/scikit-image/scikit-image/issues/5242).
