### ISSUE TITLE
How to only read one "band" with imread?

### ISSUE THREAD

**Issue by JesseRMeyer** [cgohlke/tifffile#197]
Hi,

Thanks for a nice package.

I have a GeoTiff raster image with 5 non-interleaved bands.  However, I see no way to tell `imread` to only read from one of these bands.  Instead, I seem to be forced to read them all, and then ignore the ones I don't want to use, but this image is too large to fit into memory.

Thanks

**Comment by cgohlke** [comment]
Use the zarr interface:

https://github.com/cgohlke/tifffile/blob/84c9c41668173965fdeb2907bfb42d037bf0cd00/tifffile/tifffile.py#L750-L755
