### ISSUE TITLE
Scene indexing in imread with MMstack images 

### ISSUE THREAD

**Issue by BrianWhitneyAI** [cgohlke/tifffile#198]
Using the new parser for Micro-Manager MMStack series, An image of dimensions (50, 5, 3, 256, 256) " TZCYX with two scenes ("Image:0", "Image:1") becomes dimensions (50, 2, 5, 3, 256, 256) TRZCYX with scenes stored in R. When trying to read the second scene using the series parameter of imread, all info is stored in self.series[0] rather than each scene being stored at an index of self.series. This specifically becomes a problem when reading with aszarr, which relies on a specific scene index with series = self.series[scene_index]. Is there another way to access an individual scene without pulling the whole image from self.series[0] and reshaping the data manually?

```
with fs.open(path) as open_resource:
  with imread(
      open_resource, aszarr=True, series= 1, level=0, chunkmode="page", 
  ) as store:
      arr = da.from_zarr(store)
```
        def aszarr(
            self,
            key: int | None = None,
            *,
            series: int | TiffPageSeries | None = None,
            level: int | None = None,
            **kwargs: Any,
        ) -> ZarrTiffStore:
            """Return images from select pages as Zarr store.
    
            By default, the images from the first series, including all levels,
            are wrapped as a Zarr store.
    
            Parameters:
                key:
                    Index of page in file (if `series` is None) or series to wrap
                    as Zarr store.
                    By default, a series is wrapped.
                series:
                    Index of series to wrap as Zarr store.
                    The default is 0 (if `key` is None).
                level:
                    Index of pyramid level in series to wrap as Zarr store.
                    By default, all levels are included as a multi-scale group.
                **kwargs:
                    Additional arguments passed to :py:meth:`TiffPage.aszarr`
                    or :py:meth:`TiffPageSeries.aszarr`.
    
            """
            if not self.pages:
                raise NotImplementedError('empty Zarr arrays not supported')
            if key is None and series is None:
                return self.series[0].aszarr(level=level, **kwargs)
    
            pages: Any
            if series is None:
                pages = self.pages
            else:
                if not isinstance(series, TiffPageSeries):
                     series = self.series[series]
                     IndexError: list index out of range

**Comment by cgohlke** [comment]
Micro-Manager MMStack files have three sets of metadata: 

1. Micro-Manager's own format, in which the position dimension (`R`) is just another dimension in first or second axis depending on acquisition parameters. This allows zarr to access all image data in the file as one store.
2. OME-XML, where the positions are described as separate "series". Several stores are needed to access the image dataset.
3. ImageJ metadata, which is plain wrong for multi-position or multi-file datasets.

Older versions of tifffile used the OME-XML metadata (2) while newer versions default to (1). There are other differences between these metadata and implementations, but they probably don't matter here. 

To instruct tifffile to ignore the Micro-Manager metadata and fall back to OME-XML, specify `is_mmstack=False` in `imread`.
