### ISSUE TITLE
Missing xml declaration from apeer-ometiff-library

### ISSUE THREAD

**Issue by manzt** [cgohlke/tifffile#2]
I have made the maintainers of [`apeer-ometiff-library`](https://github.com/apeer-micro/apeer-ometiff-library/issues/12) aware, but OME-TIFFs generated from `apeer-ometiff-library.io.write_ometiff` fail to have the property `tifffile.TiffFile.is_ome` (and subsequently `tifffile.TiffFile.ome_metadata`) when read by `tifffile`. I believe this is due to the line in the return that checks the first characters of the xml. This is because `apeer-ometiff-library` does not generate the xml declaration header `<?xml version="1.0" encoding="UTF-8"?>`. It is not clear to me if the xml declaration is required to have a [valid schema](https://en.wikipedia.org/wiki/XML#Key_terminology), but does this check need to be so stringent here?

https://github.com/cgohlke/tifffile/blob/5f9f1381b6c8dae0fbad7d65818063d8a17be117/tifffile/tifffile.py#L5216-L5221

**Comment by cgohlke** [comment]
Fixed in [v2020.5.5](https://github.com/cgohlke/tifffile/blob/v2020.5.5/tifffile/tifffile.py#L5318)
