### ISSUE TITLE
How to open cmyk alpha file?

### ISSUE THREAD

**Issue by tlxfif** [cgohlke/tifffile#201]
How to open cmyk alpha file? When I open it, there will be 5 channels, and the alpha channel will occupy a channel independently. Open it and save it immediately, and the transparent channel will be lost, thank you :)

`
    img = tif.imread(imgpath)
    tif.imwrite("temp.tif", img, photometric='SEPARATED')
`

[cdr_cmyka_100.zip](https://github.com/cgohlke/tifffile/files/11582304/cdr_cmyka_100.zip)

**Comment by cgohlke** [comment]
Try to specify the kind of extrasample:

```
import tifffile

tifffile.imwrite(
    'temp.tif',
    tifffile.imread('cdr_cmyka_100.tif'),
    photometric=tifffile.PHOTOMETRIC.SEPARATED,
    extrasamples=(tifffile.EXTRASAMPLE.UNASSALPHA,),
)
```
