### ISSUE TITLE
How to specify the channel name

### ISSUE THREAD

**Issue by tlxfif** [cgohlke/tifffile#202]
I have a cmyk channel and two other w1, w2 channels, how to specify it in the tifffile
thank you :)

**Comment by tlxfif** [comment]
I tried using the following code, but it doesn't work
```
metadata={
            'Channel': {'Name': ['Ch 1', 'Ch 2', 'Ch 3', 'Ch 4', 'Ch 5', 'Ch 6', 'Ch 7']},
        }
```

**Comment by cgohlke** [comment]
Please provide a minimal reproducible example to demonstrate the issue. 

TIFF does not have a way to specify channel names. It uses PhotometricInterpretation and ExtraSamples tags to describe image samples.

It looks like you are trying to create an OME-TIFF file. Make sure to enable the OME format and specify the axes order. See the [example](https://github.com/cgohlke/tifffile/blob/84c9c41668173965fdeb2907bfb42d037bf0cd00/tifffile/tifffile.py#L630-L676) in the module docstring.
