### ISSUE TITLE
How to properly merge additional channels

### ISSUE THREAD

**Issue by tlxfif** [cgohlke/tifffile#203]
[cmyk_cdr_100_w1.zip](https://github.com/cgohlke/tifffile/files/11593244/cmyk_cdr_100_w1.zip)
use code 

```

import tifffile as tif
import numpy as np

img = tif.imread("cmyk_cdr_100_w1.tif")
extrasamples = (tif.EXTRASAMPLE.UNASSALPHA,tif.EXTRASAMPLE.UNSPECIFIED)

c = img[:, :, 3]
m = img[:, :, 3]
y = img[:, :, 3]
k = img[:, :, 3]
alpha = img[:, :, 3]
extra = img[:, :, 3]
tif.imwrite(
    "cdr_cmyka_100_out.tif",
    np.dstack([c,m,y,k,alpha,extra]),
    photometric=tif.PHOTOMETRIC.SEPARATED,
    extrasamples=extrasamples,
)

```

The extra channel colors are inconsistent with the normal channel and are inverted

![image](https://github.com/cgohlke/tifffile/assets/30333934/a38ca824-4d93-4596-be5f-1ee7005fc414)

**Comment by tlxfif** [comment]
I want one of the channels to be an extension, but the colors are inverted, which is from google translate. Thanks :)

**Comment by cgohlke** [comment]
That's probably because CMYK is a subtractive color model while the alpha channel is not. Anyway, this is not a tifffile specific issue.
