### ISSUE TITLE
Skip tests that requires network access

### ISSUE THREAD

**Issue by opoplawski** [cgohlke/tifffile#204]
For building the Fedora package we need to skip any tests that require network access (or provide a set of pre-downloaded data).  I see a SKIP_HTTP parameter in test_tifffile.py but no obvious way to set that other than editing the file.  Is that right?

**Comment by cgohlke** [comment]
Setting the `SKIP_HTTP` environment variable to `1` should work. Does it not?

**Comment by opoplawski** [comment]
I don't think that gets evaluated (at least at version 2022.10.10 which is what I'm stuck on at the moment):
```
+ export SKIP_HTTP=True
+ SKIP_HTTP=True
+ pytest-3.11 -v tests
============================= test session starts ==============================
platform linux -- Python 3.11.3, pytest-7.3.1, pluggy-1.0.0 -- /usr/bin/python3
versions: tifffile-2022.10.10, imagecodecs-2022.9.26, numpy-1.24.3, zarr-2.14.1, dask-2023.4.1, xarray-2023.4.2, fsspec-2023.5.0
test config: SKIP_PRIVATE | SKIP_PUBLIC | SKIP_VALIDATE | SKIP_WIN
rootdir: /builddir/build/BUILD/tifffile-2022.10.10
```
and various tests fail trying to download files.
If I edit the file to set SKIP_HTTP to True:
```
+ sed -i 's/SKIP_HTTP = False/SKIP_HTTP = True/' tests/test_tifffile.py
+ pytest-3.11 -v tests
============================= test session starts ==============================
platform linux -- Python 3.11.3, pytest-7.3.1, pluggy-1.0.0 -- /usr/bin/python3
versions: tifffile-2022.10.10, imagecodecs-2022.9.26, numpy-1.24.3, zarr-2.14.1, dask-2023.4.1, xarray-2023.4.2, fsspec-2023.5.0
test config: SKIP_HTTP | SKIP_PRIVATE | SKIP_PUBLIC | SKIP_VALIDATE | SKIP_WIN
rootdir: /builddir/build/BUILD/tifffile-2022.10.10
```
and it works.

**Comment by opoplawski** [comment]
same issue with SKIP_HTTP=1 (just to be sure)

**Comment by cgohlke** [comment]
> version 2022.10.10

Support for environment variables was added in v2023.1.23.

**Comment by opoplawski** [comment]
Ah, great - will switch to that when we can update to that.
