### ISSUE TITLE
use tiffile  stored in a multi-resolution pyramid structure with tiff file

### ISSUE THREAD

**Issue by chengdonglin** [cgohlke/tifffile#207]
I known different scale tiles , how can I use tifffile build the Whole slide images tiff file,like below
![image](https://github.com/cgohlke/tifffile/assets/28192795/2dd3e4d8-c0e4-428d-b967-dad9b4d23752)

**Comment by cgohlke** [comment]
It depends on which software you use to read the image pyramid from TIFF. There are several TIFF based formats that support pyramids, e.g. [OME-TIFF](https://docs.openmicroscopy.org/ome-model/6.3.1/ome-tiff/specification.html#sub-resolutions), [ZIF](https://github.com/cgohlke/tifffile/blob/84c9c41668173965fdeb2907bfb42d037bf0cd00/tifffile/tifffile.py#L630-L676), [Generic tiled TIFF](https://openslide.org/formats/generic-tiff/), and [Cloud Optimized GeoTIFF](https://www.cogeo.org/).

There's an example in the docstring to create a pyramidal OME-TIFF:
https://github.com/cgohlke/tifffile/blob/84c9c41668173965fdeb2907bfb42d037bf0cd00/tifffile/tifffile.py#L630-L676

There are more examples and discussions on the [Image.sc forum](https://forum.image.sc/tag/tifffile)
