### ISSUE TITLE
'chroma subsampling not supported without JPEG compression'

### ISSUE THREAD

**Issue by rodrigo-j-goncalves** [cgohlke/tifffile#209]
I have a mp4 video file that was converted to TIF files using ffmpeg:
`ffmpeg -i inputVideo3.mp4 -vsync passthrough $filename%05d.tiff`

Then I try to open the image sequence using [pims](http://soft-matter.github.io/pims/v0.6.1/):
`pims.open('path/to/img/*.tiff')`

I get the following error:
```
~/.virtualenvs/VirtEnv1/lib/python3.10/site-packages/tifffile/tifffile.py in ?(*args, **kwargs)
    8228             def decode_raise_subsampling(*args, **kwargs):
-> 8229                 raise NotImplementedError(
    8230                     'chroma subsampling not supported without JPEG compression'
    8231                 )

NotImplementedError: chroma subsampling not supported without JPEG compression
```

**Comment by cgohlke** [comment]
Yes, chroma subsampling without JPEG compression is a niche feature that is not supported by tifffile as documented:

https://github.com/cgohlke/tifffile/blob/84c9c41668173965fdeb2907bfb42d037bf0cd00/tifffile/tifffile.py#L253-L257

You should be able to read the file using a libtiff based library like Pillow or imagecodecs.

**Comment by rodrigo-j-goncalves** [comment]
Thank you!
