### ISSUE TITLE
Bug in 2020.8.13

### ISSUE THREAD

**Issue by plankter** [cgohlke/tifffile#21]
In version 2020.8.13 when reading OME-TIFF files:

```Python
with tifffile.TiffFile(filepath) as tif:
    data = tif.asarray(out="memmap")
```

data shape, as an example, looks like (1, 1, 47, 801, 800, 1)

where in version 2020.7.24 it was (47, 801, 800)

**Comment by cgohlke** [comment]
Probably your file contains multiple metadata formats describing the image shape as (1, 1, 47, 801, 800, 1) and (47, 801, 800). It's best not to create such files.

**Comment by cgohlke** [comment]
When writing OME-XML to the ImageDescription tag, use `metadata=None` in `TiffWriter.save` to disable tifffile from also writing potentially conflicting JSON metadata. `xtiff` does not do that, while `aicsimageio` and `apeer-ometiff-library` do.
