### ISSUE TITLE
Include all compression parameters in aszarr metadata

### ISSUE THREAD

**Issue by jhamman** [cgohlke/tifffile#211]
Consider this small example using Kerchunk's `tiff_to_zarr`:

```python
import xarray as xr
import rioxarray
from numpy.random import default_rng
from kerchunk.tiff import tiff_to_zarr

rng = default_rng(seed=42)

shape = (3, 10, 20)
da = xr.DataArray(
    data=rng.random(shape),
    dims=["band", "y", "x"],
    name="foo",
)
da = da.rio.write_crs("epsg:4326")
da.rio.to_raster("test.tiff", driver="COG", compress="LZMA")

refs = tiff_to_zarr("./test.tiff")
refs
```
```
{'.zattrs': '{"_ARRAY_DIMENSIONS":["Y","X","S"],"DESCRIPTION":"foo","LAYOUT":"IFDS_BEFORE_DATA","BLOCK_ORDER":"ROW_MAJOR","BLOCK_LEADER":"SIZE_AS_UINT4","BLOCK_TRAILER":"LAST_4_BYTES_REPEATED","KNOWN_INCOMPATIBLE_EDITION":"NO","KeyDirectoryVersion":1,"KeyRevision":1,"KeyRevisionMinor":0,"GTModelTypeGeoKey":2,"GTRasterTypeGeoKey":1,"GeographicTypeGeoKey":4326,"GeogCitationGeoKey":"WGS 84","GeogAngularUnitsGeoKey":9102,"GeogSemiMajorAxisGeoKey":6378137.0,"GeogInvFlatteningGeoKey":298.257223563,"ModelTransformation":[[1.0,0.0,0.0,0.0],[0.0,1.0,0.0,0.0],[0.0,0.0,0.0,0.0],[0.0,0.0,0.0,1.0]]}',
 '.zarray': '{\n "chunks": [\n  512,\n  512,\n  3\n ],\n "compressor": {\n  "id": "lzma"\n },\n "dtype": "<f8",\n "fill_value": 0.0,\n "filters": null,\n "order": "C",\n "shape": [\n  10,\n  20,\n  3\n ],\n "zarr_format": 2\n}',
 '0.0.0': ['./test.tiff', 882, 5596]}
```

Notice specifically that the compressor field only includes the `id` and none of the settable parameters (e.g. [numcodecs docs](https://numcodecs.readthedocs.io/en/stable/lzma.html#numcodecs.lzma.LZMA)). Creating a similar array with zarr returns:

Would it be possible to provide the standard options to these compressors (e.g. `check`, `filters`, `format`, `preset`, `level`, etc.)?

For example, this is the metadata created by a similar zarr V2 array:

```python
import zarr
from numcodecs import LZMA
store = {}
a = zarr.open_array(store=store, mode='w', shape=(3, 10, 20), compressor=LZMA())
print(store['.zarray'].decode())
```
```
{
    "chunks": [
        3,
        10,
        20
    ],
    "compressor": {
        "check": -1,
        "filters": null,
        "format": 1,
        "id": "lzma",
        "preset": null
    },
    "dimension_separator": ".",
    "dtype": "<f8",
    "fill_value": 0.0,
    "filters": null,
    "order": "C",
    "shape": [
        3,
        10,
        20
    ],
    "zarr_format": 2
}
```
xref: https://github.com/zarr-developers/zarr-python/issues/1443

**Comment by cgohlke** [comment]
Looks like a bug in Zarr to require specifying default arguments to codecs.

An option may be to use `imagecodecs_lzma` instead of numcodecs?

**Comment by jhamman** [comment]
Thanks for the quick response @cgohlke. Two followups that would be helpful from my end:

1. Is it same to assume that if tifffile does not return additional parameters (e.g. `check`), that those values are the standard default values?
2. Separate from the question of "is Zarr doing the right thing", does tifffile have access/knowledge of these parameters or does the TIFF metadata not include them if/when they are set as the defaults?

**Comment by cgohlke** [comment]
> 1. Is it same to assume that if tifffile does not return additional parameters (e.g. check), that those values are the standard default values?

I assume so, but it depends on Zarr how the numcodecs are initialized. I don't think the tifffile test suite has a case for fsspec/kerchunk with LZMA. I assumed that numcodecs's LZMA codec would be compatible with Python's LZMA implementation.

> 2. Separate from the question of "is Zarr doing the right thing", does tifffile have access/knowledge of these parameters or does the TIFF metadata not include them if/when they are set as the defaults?

Tifffile does not use numcodecs and has no knowledge of its API.

If Zarr does not revert those requirements, I'll change the zlib and lzma codecs_ids to imagecodecs_zlib/lzma.

**Comment by jhamman** [comment]
One point of clarification. This issue isn't just about LZMA. Its more about "default" codec parameters. I believe all parametrizable codecs apply.  

> I assume so, but it depends on Zarr how the numcodecs are initialized.

This seems risky. Is there a reason not to include all parameters in the JSON output from tifffile?

**Comment by cgohlke** [comment]
> Is there a reason not to include all parameters in the JSON output from tifffile?

It is not required by v2 stores, which is what tifffile uses. It unnecessarily complicates implementation and testing. 

Is there an actual example using tifffile and zarr that produces an error or even a warning due to not including all codec parameters?

**Comment by jhamman** [comment]
I agree that a Zarr V2 does not strictly require these parameters. However, Zarr-python does include default codec parameters in its JSON (see example above).

My main concern here is that I don't see a clean way to enforce "default" parameters across the ecosystem. How do we guarantee that numcodecs and imagecodecs use the same defaults? If there is a solution to that problem, we can definitely revert the V3 implementation to allow for implicit/default parameters in codecs.
