### ISSUE TITLE
how to add 'Alpha Channels Names'

### ISSUE THREAD

**Issue by tlxfif** [cgohlke/tifffile#212]
How to add parameters to the metadata, I use exiftool to open the tif, the file found the name 'Alpha Channels Names', I want to modify this, how can I modify it? Thanks

[origin.zip](https://github.com/cgohlke/tifffile/files/11844519/origin.zip)

`./exiftool.exe origin.tif` 

`Alpha Channels Names            : W1, W2`

**Comment by cgohlke** [comment]
Those names are buried in the proprietary Adobe Photoshop specific ImageResources (#34377) and ImageSourceData (#37724) tags. You can try to use the [psdtags](https://github.com/cgohlke/psdtags) library to read or change those tags.

**Comment by Mick4994** [comment]
@tlxfif 
You can modify it like this.
```python
ir =  TiffImageResources(
    name=os.path.basename(output_path),
    psdformat=PsdFormat.BE32BIT,
    blocks=[
        PsdPascalStringsBlock(
            resourceid=PsdResourceId.ALPHA_NAMES_PASCAL,
            values=[  # 3
                'test',
                'W1', # modify its name
                'W2', # modify its name
            ],
        ),
        PsdStringsBlock(
            resourceid=PsdResourceId.ALPHA_NAMES_UNICODE,
            values=[  # 3
                'test',
                'W1', # modify its name
                'W2', # modify its name
            ],
        ),
    ]
)

imwrite(
    output_path,
    new_image_array,
    photometric='rgb',
    resolution=(dpi, dpi),
    extratags=[
        ir.tifftag()
    ],
)
```
