### ISSUE TITLE
Don't force backend to tkagg in main()

### ISSUE THREAD

**Issue by anntzer** [cgohlke/tifffile#219]
Currently, tifffile.main() forces the matplotlib backend to tkagg.  It would be nice if it instead respected whatever backend the user has set (nowadays matplotlib defaults to auto-detecting a backend for which the dependencies are available); for example, this can allow the use of the qt backends, which has an interactive dialog for setting figure options (e.g. colormap and colormap limits).

Alternatively you could allow the backend to be set with a command-line option, but that seems less convenient, if anything.

**Comment by cgohlke** [comment]
Thanks. That statement has been there forever unnoticed. I'll remove it.

I'd really like to replace the whole imshow and main functions. If only there would be a decent array/image previewer for Python...
