### ISSUE TITLE
Reading from .tiff file modifies original content

### ISSUE THREAD

**Issue by tandronescu** [cgohlke/tifffile#22]
Running into an issue where I read from a saved tiff file, and at some point (say 2 or 3 reads) I notice that the contents of the file are no longer correct. E.g. I calculate the mean temperature of the image on the data and it is about 90 degrees the whole way. After running the same analysis code, the temperature will then change to something like 60 degrees.

Here is the sudo code I am using to read the tifffile:
```
tiffFileHandle = tifffile.TiffFile(filename)
numTiffPages = len(self.tiffFileHandle.pages)

i = 0
while i < numTiffPages:
    img = tiffFileHandle.pages[i].asarray()
    i++
   process img
```

Any idea why this happens? I confirmed this issue by making a copy of my original data and comparing results on the backup. This indeed shows an unexpected temperature difference.

**Comment by cgohlke** [comment]
Please provide an example file and a complete, executable code to reproduce the issue

**Comment by tandronescu** [comment]
Apologies, it was an error in my code. Closing
