### ISSUE TITLE
Support opening files with 'x'

### ISSUE THREAD

**Issue by hmaarrfk** [cgohlke/tifffile#221]
In python 'x': open for exclusive creation, failing if the file already exists

https://docs.python.org/3/library/functions.html#open

To my knowledge, this would require a change to:

Update the documentation to show that 'xb' should be valid
https://github.com/cgohlke/tifffile/blob/7b162f968bc978bd374dfe87f05a913e82afd283/tifffile/tifffile.py#L14065

Update the error checking
https://github.com/cgohlke/tifffile/blob/7b162f968bc978bd374dfe87f05a913e82afd283/tifffile/tifffile.py#L14076

Then later on, if you provide a file handle, `'wb'` and `'xb'` should be equivalent.
https://github.com/cgohlke/tifffile/blob/7b162f968bc978bd374dfe87f05a913e82afd283/tifffile/tifffile.py#L14119

Let me know if you think this is ok.

**Comment by cgohlke** [comment]
Good idea. I added support for exclusive creation mode. It'll be in the next release.
