### ISSUE TITLE
Memory-efficient Image Loading

### ISSUE THREAD

**Issue by eduheise** [cgohlke/tifffile#224]
Description:
I would like to inquire if there's a way to load a single image by chunks or any alternative method that avoids loading the entire image into RAM. Loading large images entirely into memory can be resource-intensive, and I'm wondering if there are options available to handle images in a more memory-efficient manner. If not, I would like to suggest exploring the possibility of adding such functionality to the library to improve its usability for working with large images. I'm currently working with a image with 80,000 pixels by 65,000 pixels and can't see any way to process it.

Your insights and suggestions would be greatly appreciated.

Environment:

Operating System: Arch Linux 
Python Version: 3.8
tifffile Version: 2023.8.30
RAM specs: 64G
Thank you for your attention and assistance!

**Comment by cgohlke** [comment]
There are several options:

1. Read the image data into a memory-mapped numpy array by specifying the `out` parameter, e.g. `out='memmap'`:
https://github.com/cgohlke/tifffile/blob/103b6a337db6a84293562bda65fdc8c382281fe2/tifffile/tifffile.py#L22555-L22569

2. If possible, for example in case of ImageJ hyperstacks, directly memory-map the image data in the file:
https://github.com/cgohlke/tifffile/blob/103b6a337db6a84293562bda65fdc8c382281fe2/tifffile/tifffile.py#L547-L552

3. Use Zarr to read parts of an image:
https://github.com/cgohlke/tifffile/blob/103b6a337db6a84293562bda65fdc8c382281fe2/tifffile/tifffile.py#L686-L697

4. Index or iterate over pages or segments in the file, e.g.:
https://github.com/cgohlke/tifffile/blob/103b6a337db6a84293562bda65fdc8c382281fe2/tifffile/tifffile.py#L672-L684

**Comment by eduheise** [comment]
Thank you so much! It actually worked. I spent so much time trying different solutions, and I was just giving up. Is there any way to write a TIFF image like you did with zarr?

**Comment by eduheise** [comment]
I found some code snippets that maybe could solve this second problem.

```
Create a TIFF file containing an empty image and write to the memory-mapped
NumPy array (note: this does not work with compression or tiling):

>>> memmap_image = memmap(
...     'temp.tif',
...     shape=(256, 256, 3),
...     dtype='float32',
...     photometric='rgb'
... )
>>> type(memmap_image)
<class 'numpy.memmap'>
>>> memmap_image[255, 255, 1] = 1.0
>>> memmap_image.flush()
>>> del memmap_image
```
```
Successively write the frames of one contiguous series to a TIFF file:

>>> data = numpy.random.randint(0, 255, (30, 301, 219), 'uint8')
>>> with TiffWriter('temp.tif') as tif:
...     for frame in data:
...         tif.write(frame, contiguous=True)
``` 
```
Create an OME-TIFF file containing an empty, tiled image series and write
to it via the Zarr interface (note: this does not work with compression):

>>> imwrite(
...     'temp.ome.tif',
...     shape=(8, 800, 600),
...     dtype='uint16',
...     photometric='minisblack',
...     tile=(128, 128),
...     metadata={'axes': 'CYX'}
... )
>>> store = imread('temp.ome.tif', mode='r+', aszarr=True)
>>> z = zarr.open(store, mode='r+')
>>> z
<zarr.core.Array (8, 800, 600) uint16>
>>> z[3, 100:200, 200:300:2] = 1024
>>> store.close()
```

Also, the issue [#104](https://github.com/cgohlke/tifffile/issues/104) may be related.

**Comment by eduheise** [comment]
Yea, found it. This code snippet work for my case:

```
import numpy
from tifffile import imwrite

data = numpy.random.randint(0, 2**12, (1000, 1000), 'uint16')

def tiles(data, tileshape):
    for y in range(0, data.shape[0], tileshape[0]):
        for x in range(0, data.shape[1], tileshape[1]):
            yield data[y : y + tileshape[0], x : x + tileshape[1]]

imwrite(
    'temp.tif',
    tiles(data, (16, 16)),
    tile=(16, 16),
    shape=data.shape,
    dtype=data.dtype
)
```

Thank you so much @cgohlke. You and your collaborators have created an exceptional package here.

Wish you the best, and have a nice day!
Eduardo Heise
