### ISSUE TITLE
StopIteration while writing RGB TIF images using generator

### ISSUE THREAD

**Issue by eduheise** [cgohlke/tifffile#225]
I am trying to write a tiled RGB image to a TIF file, but I am getting an error. The image is shaped (3, 1024, 1024) and the demonstration code is as follows:

```python
import numpy as np
import tifffile as tifi

data = np.random.randint(0, 255, (3, 1024, 1024), 'uint8')

def tiles(data, tileshape):
  for y in range(0, data.shape[1], tileshape[0]):
    for x in range(0, data.shape[2], tileshape[1]):
      yield data[:, y: y + tileshape[0], x: x + tileshape[1]]

for i, im in enumerate(tiles(data, (256, 256))):
  print(i, im.shape)

tifi.imwrite(
  'temp.tif',
  tiles(data, (256, 256)),
  tile=(3, 256, 256),
  shape=data.shape,
  dtype=data.dtype
)
```

The error is from this loop:

https://github.com/cgohlke/tifffile/blob/e680307a1cbafd77151b37c30c5f4c68c24328f4/tifffile/tifffile.py#L3325-L3327

And output this:

```
0 (3, 256, 256)
1 (3, 256, 256)
2 (3, 256, 256)
3 (3, 256, 256)
4 (3, 256, 256)
5 (3, 256, 256)
6 (3, 256, 256)
7 (3, 256, 256)
8 (3, 256, 256)
9 (3, 256, 256)
10 (3, 256, 256)
11 (3, 256, 256)
12 (3, 256, 256)
13 (3, 256, 256)
14 (3, 256, 256)
15 (3, 256, 256)

Traceback (most recent call last):
  File "main.py", line 18, in <module>
    tifi.imwrite(
  File "/home/user/anaconda3/envs/tifwriter/lib/python3.8/site-packages/tifffile/tifffile.py", line 1289, in imwrite
    result = tif.write(
  File "/home/user/anaconda3/envs/tifwriter/lib/python3.8/site-packages/tifffile/tifffile.py", line 3327, in write
    iteritem = next(dataiter)
StopIteration
```

Environment:

Operating System: Arch Linux
Python Version: 3.8
tifffile Version: 2023.7.10

**Comment by cgohlke** [comment]
Several things:

1. `imwrite('temp.tif', data)` writes a planar RGB TIFF in this case. It's better to explicitly specify `planarconfig` and `photometric` parameters to avoid ambiguity.
2. `tile=(3, 256, 256)` instructs tifffile to write volumetric tiles. Since the data is not volumetric, this should probably fail or log a warning. Instead it is silently ignored by the current version of tifffile.
3. Tiling in TIFF is only along the spatial dimensions, not the RGB samples. Add an outer loop over the RGB samples to the generator function.

The corrected code looks like this:
```python
import numpy
import tifffile

data = numpy.random.randint(0, 255, (3, 1024, 1024), 'uint8')


def tiles(data, tileshape):
    for s in range(data.shape[0]):  # generate separate tiles for each sample
        for y in range(0, data.shape[1], tileshape[0]):
            for x in range(0, data.shape[2], tileshape[1]):
                yield data[s, y : y + tileshape[0], x : x + tileshape[1]]


tifffile.imwrite(
    'issue225.tif',
    tiles(data, (256, 256)),
    photometric='rgb',
    planarconfig='separate',
    tile=(256, 256),  # not (3, 256, 256)
    shape=data.shape,
    dtype=data.dtype,
)
```

**Comment by cgohlke** [comment]
The next version of tifffile will raise a ValueError when writing non-volumetric data with volumetric tiles.
