### ISSUE TITLE
IndexError: tuple index out of range

### ISSUE THREAD

**Issue by ktsitsi** [cgohlke/tifffile#227]
Trying to chunk ingest a tiff file I get an index error with the following stack trace.
```bash
~.venv/lib/python3.9/site-packages/zarr/core.py in ?(self, selection)
    838         fields, pure_selection = pop_fields(selection)
    839         if is_pure_fancy_indexing(pure_selection, self.ndim):
    840             result = self.vindex[selection]
    841         elif is_pure_orthogonal_indexing(pure_selection, self.ndim):
--> 842             result = self.get_orthogonal_selection(pure_selection, fields=fields)
    843         else:
    844             result = self.get_basic_selection(pure_selection, fields=fields)
    845         return result

~.venv/lib/python3.9/site-packages/zarr/core.py in ?(self, selection, out, fields)
   1120 
   1121         # setup indexer
   1122         indexer = OrthogonalIndexer(selection, self)
   1123 
-> 1124         return self._get_selection(indexer=indexer, out=out, fields=fields)

~.venv/lib/python3.9/site-packages/zarr/core.py in ?(self, indexer, out, fields)
   1384 
   1385         if math.prod(out_shape) > 0:
   1386             # allow storage to get multiple items at once
   1387             lchunk_coords, lchunk_selection, lout_selection = zip(*indexer)
-> 1388             self._chunk_getitems(
   1389                 lchunk_coords,
   1390                 lchunk_selection,
   1391                 out,

~.venv/lib/python3.9/site-packages/zarr/core.py in ?(self, lchunk_coords, lchunk_selection, out, lout_selection, drop_axes, fields)
   2220             partial_read_decode = False
   2221             contexts = {}
   2222             if not isinstance(self._meta_array, np.ndarray):
   2223                 contexts = ConstantMap(ckeys, constant=Context(meta_array=self._meta_array))
-> 2224             cdatas = self.chunk_store.getitems(ckeys, contexts=contexts)
   2225 
   2226         for ckey, chunk_select, out_select in zip(ckeys, lchunk_selection, lout_selection):
   2227             if ckey in cdatas:

~.venv/lib/python3.9/site-packages/zarr/_storage/store.py in ?(self, keys, contexts)
    156         This default implementation uses __getitem__() to read each key sequentially and
    157         ignores contexts. Overwrite this method to implement concurrent reads of multiple
    158         keys and/or to utilize the contexts.
    159         """
--> 160         return {k: self[k] for k in keys if k in self}

~.venv/lib/python3.9/site-packages/zarr/_storage/store.py in ?(.0)
--> 160     def getitems(
    161         self, keys: Sequence[str], *, contexts: Mapping[str, Context]
    162     ) -> Mapping[str, Any]:
    163         """Retrieve data from multiple keys.

~.venv/lib/python3.9/site-packages/zarr/storage.py in ?(self, key)
    772     def __contains__(self, key):
--> 773         return key in self._mutable_mapping

~.venv/lib/python3.9/site-packages/tifffile/tifffile.py in ?(self, key)
  12094     def __contains__(self, key: object, /) -> bool:
  12095         if key in self._store:
  12096             return True
  12097         assert isinstance(key, str)
> 12098         return self._contains(key)

~.venv/lib/python3.9/site-packages/tifffile/tifffile.py in ?(self, key)
  12739         """Return if key is in store."""
  12740         try:
  12741             _, page, _, offset, bytecount = self._parse_key(key)
  12742         except KeyError:
> 12743             return False
  12744         return (
  12745             page is not None
  12746             and offset is not None

~.venv/lib/python3.9/site-packages/tifffile/tifffile.py in ?(self, key)
  12860             try:
  12861                 offset = page.dataoffsets[chunkindex]
  12862             except IndexError:
  12863                 print(f"Error: key:{key}, chunkindex:{chunkindex}, dataoffsets:{len(page.dataoffsets)}")
> 12864         bytecount = page.databytecounts[chunkindex]
  12865         return page.keyframe, page, chunkindex, offset, bytecount
```

Disclaimer that the data refer to multi-resolution biomedical imaging tiffs and are proprietary, thus I cannot share them, but following the stack trace and doing some debugging, the issues seems to appear in a specific resolution level of the image and specifically the index error comes from an edge case where the `chunkindex` is equal to the length of the `page.databytecounts`

```bash
level:3 
key:13.0.0 
series: TiffPageSeries 0  6720x22976x3  uint8  YXS  generic  1 Pages
pageindex:0 
chunkindex:585
page:TiffPage 3 @732363938  6720x22976x3  uint8  ycbcr reduced tiled jpeg, 
keyframe:TiffPage 3 @732363938  6720x22976x3  uint8  ycbcr reduced tiled jpeg
Dataoffsets Length: 585 
Index Error: key:13.0.0, chunkindex:585, dataoffsets:585
```

The `Index Error` appears in `tifffile` version `2023.4.12` and later,  as till `2023.3.15` it is working. After some investigation it appears that between the two versions there were some changes concerning the `_contains` function , introduction of `parse_key` function, and some changes in `_getitem` for empty chunks etc.. Any help would be highly appreciated on this issue.

**Comment by cgohlke** [comment]
It looks like the file is corrupted. There is a whole row of tiles missing assuming 512x512 tiles.

**Comment by cgohlke** [comment]
Changing this line to `except (KeyError, IndexError):` might work.

https://github.com/cgohlke/tifffile/blob/70a09c7f04f7cad38fe7d321d7917f674fceb87b/tifffile/tifffile.py#L12955

**Comment by ktsitsi** [comment]
Indeed even without trying this change, also catching an index error, seems it will work, as it will rollback the functionality to previous versions in this case. However I am not sure if this change should be an ad-hoc solution for my case or a generic solution for similar cases. Not sure if the data is corrupted or not it might seem like this, but it was getting ingested just fine with previous versions and I was able to render them as well. It seems that the issue applies to the same level for all the images so there might be sth wrong indeed with the data but since I don't own them I cant be sure. Have you ever faced a similar issue before or is there any other application that you could think of?

**Comment by cgohlke** [comment]
I'm almost sure either the number of tile offsets/bytecounts or the image height/length are wrong in the file. 

In previous versions, and also the asarray function, the missing bottom row of tiles are zeroed, which is hardly noticeable for large arrays. IIRC zarr uses zeroed chunks for KeyErrors, not IndexErrors. I'll fix that in the next version of tifffile using a synthetic test case.

Anyway, try to report the issue to the software manufacturer producing the file. It could in principle be that the file does not fully adhere to the TIFF standard. For example, the tiles could need stitching based on some other metadata...

**Comment by cgohlke** [comment]
Please try tifffile 2023.9.26.
