### ISSUE TITLE
Writing / Loading additional metadata in ome.tif

### ISSUE THREAD

**Issue by FiReTiTi** [cgohlke/tifffile#233]
Sorry, it's not really an issue but more a question. So please let me know where I can ask such question next time.

When I write an one.tif file, I add my own metadata:

    metadata = {
            'axes': 'CYX',
            'Channel': {'Name': Channels},
            'MyOwnMetadata': MyOwnMetadata,
            'PhysicalSizeX': PixelSize,
            'PhysicalSizeXUnit': PixelUnit,
            'PhysicalSizeY': PixelSize,
            'PhysicalSizeYUnit': PixelUnit,
            'Plane': {'PositionX': [0.0] * 16, 'PositionXUnit': [PixelUnit] * 16},
            'SignificantBits': 16
            }

    tif.write(stack, subifds=SubResolutions, resolution=(PixelBase / PixelSize, PixelBase / PixelSize), metadata=metadata, **options)

However when I read the generated file, I can find the metadata in `ome_metadata` but not my own added metadata.

Where can I find them?
Or is this the wrong way to add supplementary metadata ?

**Comment by cgohlke** [comment]
It's a common issue. The [OME schema](https://www.openmicroscopy.org/Schemas/Documentation/Generated/OME-2016-06/ome.html) is large and complex with references between elements etc. Tifffile only deals with OME-XML Image/Pixels, Plane, and Channel elements. Other elements are ignored. See https://github.com/cgohlke/tifffile/blob/35c19b7c6c8b85aa09e490520677b5a2a31c14e4/tifffile/tifffile.py#L15522-L15542. 

The options are:

1. provide your own OME-XML, e.g. `imwrite(..., description=ome_xml, metadata=None)`
2. Edit the OME-XML created by tifffile using [ome-types](https://pypi.org/project/ome-types/), and write it back to the file. See the example at https://forum.image.sc/t/python-tifffile-ome-full-metadata-support/56526/3?u=cgohlke

**Comment by FiReTiTi** [comment]
Thank you for your answer.

1. I used `xmltodict.unparse` to convert my dict into a xml, and then `ome-types.from_xml`, but it seems that the dict keys must be very specific. Any advice about how to insert my own dict into such format?

3. I tried the solution you shared in the forum, but when writing the new metadata using `tiffcomment(filename, ome_xml)` I get the following error: `ValueError: TIFF strings must be 7-bit ASCII`.  I looked online and I found a single post (that was really confusing) to convert a string into 7-bit ASCII encoding. Any advise or documentation to do it?

**Comment by jmuhlich** [comment]
(speaking as an author of ome_types)
ome_types doesn't work with arbitrary XML, rather only XML conforming to the OME-XML schema. Do you have metadata that fits into the concepts supported by that schema, or is this other stuff like experimental/biological details? The visual schema documentation is here: https://www.openmicroscopy.org/Schemas/Documentation/Generated/OME-2016-06/ome.html

You can fix that ValueError by calling `.encode()` on the XML string before passing it to `tiffcomment`. If you pass a `str` to `tiffcomment`, tifffile will enforce that all characters fall within ASCII per the official TIFF spec. But if you pass a `bytes` then tifffile will allow it under the assumption that you know what you're doing, and although this technically violates the spec I think every TIFF parser is OK with it.

**Comment by jmuhlich** [comment]
Oh, and we should probably move any ome_types issues to the issue tracker at https://github.com/tlambert03/ome-types/issues or a discussion at https://forum.image.sc/ .
