### ISSUE TITLE
`imwrite` Produces Unexpected Output for uint16 Numpy Arrays with Shape (height, width)

### ISSUE THREAD

**Issue by Donovan-Eral** [cgohlke/tifffile#234]
When writing to a file with a tile generator function, a tile shape (height, width),  and a data type of uint16, I get the following result.

![uint16_single_channel](https://github.com/cgohlke/tifffile/assets/86755741/c676bfdb-d335-4e62-bf60-ea2b3bafd06b)

As you can see, the tiles at the edges (when they don't fit within the expected shape) wrap. The code to reproduce is
```
import numpy as np
import tifffile

def set_white_border(image: np.ndarray, border_size: int = 1) -> np.ndarray:
    image[:border_size, :] = np.iinfo(image.dtype).max
    image[-border_size:, :] = np.iinfo(image.dtype).max

    image[:, :border_size] = np.iinfo(image.dtype).max
    image[:, -border_size:] = np.iinfo(image.dtype).max

    return image

data = np.ones((400, 400), "uint16") * (np.iinfo("uint16").max // 2)
# data = numpy.stack((data, data, data), axis=-1)
# data = numpy.ones((400, 400), "uint8") * (numpy.iinfo("uint8").max // 2)


def tiles(data, tileshape):
    for y in range(0, data.shape[0], tileshape[0]):
        for x in range(0, data.shape[1], tileshape[1]):
            result = data[y : y + tileshape[0], x : x + tileshape[1]]
            result = set_white_border(result)
            yield result

tifffile.imwrite(
    "temp.tif",
    tiles(data, (64, 64)),
    tile=(64, 64),
    shape=data.shape,
    dtype=data.dtype,
```

I noticed that this issue doesn't occur with uint8. I could be doing something wrong, but it doesn't seem like it.

**Comment by cgohlke** [comment]
Which version of tifffile is used and how is the file read/displayed?

I ran the code and the produced file looks correct here.

**Comment by Donovan-Eral** [comment]
strange. I'm using tifffile==2023.9.26 and opened it with the standard image viewer on Ubuntu.

**Comment by cgohlke** [comment]
Can you attach the file? Any software I have on Windows and Mac can open the file produced here.

**Comment by Donovan-Eral** [comment]
Okay, I just opened it with Gimp and it looks fine. Must be an issue with the viewer. Thanks for the quick response.
