### ISSUE TITLE
Memory usage when writing tif with `tifffile.TiffWriter.write`

### ISSUE THREAD

**Issue by rdbs-oss** [cgohlke/tifffile#236]
Hello,

Thank you for developing and maintaining `tifffile`.

I use `tifffile.TiffWriter.write` to convert images from various formats to tif, but noticed a surprising behavior in terms of memory consumption. Find below the memory profile corresponding to the snippet at the end.

In short, what happens is the following:
1. Before anything, I create and write on disk a big `uint8` numpy array (20k * 20k * 3 pixels ~= 1.15 GiB)
2. When writing the tif out of this numpy array, I do not load the array in RAM, but load it has a memorymap, and write the `.tif` using a generator of tiles.

Doing so, I was expecting memory usage to never peak to total array size, and that tiles would progressively be collected by Python's GC. However, it seems memory footprint is regularly growing as long as tiles get written one after the other.

![iTerm2 L0MKOz plot](https://github.com/cgohlke/tifffile/assets/72745434/92d6ab15-b65c-4659-9d4c-d40593ac24f5)

MRE:
```python
from tempfile import NamedTemporaryFile
import numpy as np
from pathlib import Path
import tifffile
from itertools import product
from tqdm import tqdm


x = np.load("/tmp/x.npy", mmap_mode="r") # Memory maps 20k x 20k x 3 array
tile_h, tile_w = (224, 224)

with NamedTemporaryFile(suffix=".tif", dir="/tmp") as tmpfile:
    tmpfile = Path(tmpfile.name)
    with tifffile.TiffWriter(tmpfile, bigtiff=True, imagej=False, ome=False) as outtif:
        options = dict(
            photometric="rgb",
            tile=(tile_h, tile_w),
            metadata={},
        )

        level_h = x.shape[0]
        level_w = x.shape[1]
        c = x.shape[-1]

        tile_coordinates = list(product(range(0, x.shape[0], tile_h), range(0, x.shape[1], tile_w)))
        n_tiles = len(tile_coordinates)
        tiles_gen = (x[i : i + tile_h, j : j + tile_w] for i, j in tile_coordinates)
        outtif.write(
            tiles_gen,
            subfiletype=1,
            resolution=(20_000, 20_000, "CENTIMETER"),
            **options,
            shape=(level_h, level_w, c),
            dtype=np.uint8,
        )
```

Do you know what could explain this behavior, and if there would be a way to avoid accumulating memory footprint ?

Thank you

**Comment by cgohlke** [comment]
Bummer. This is reproducible outside of tifffile. Looks like contiguous copies of slices of memory-mapped numpy arrays are not garbage collected:

```python
from itertools import product

import numpy
import psutil

x = numpy.load('x.npy', mmap_mode='r')
t = 512

process = psutil.Process()
mem = process.memory_info().rss

for i, j in product(range(0, x.shape[0], t), range(0, x.shape[1], t)):
    a = numpy.ascontiguousarray(x[i : i + t, j : j + t])
    del a
    print(process.memory_info().rss - mem)
```

**Comment by cgohlke** [comment]
```python
```

**Comment by cgohlke** [comment]
This is reproducible outside of tifffile:
```python
from itertools import product

import numpy
import psutil

x = numpy.load('x.npy', mmap_mode='r')
t = 512

process = psutil.Process()
mem = process.memory_info().rss

for i, j in product(range(0, x.shape[0], t), range(0, x.shape[1], t)):
    a = numpy.ascontiguousarray(x[i : i + t, j : j + t])
    del a
    print(process.memory_info().rss - mem)
```
I think this might just be how memory mapping works. Are you actually running out of RAM?

**Comment by rdbs-oss** [comment]
Thank you very much for diving into the issue. Indeed, it seems to be completely related to `numpy`'s memory mapping process and not to `tifffile` at all.

FYI, the issue is solved if each tile is read from a brand newly read array, i.e something like:
```python
…
for i, j in product(range(0, x.shape[0], t), range(0, x.shape[1], t)):
    x = np.load("/tmp/x.npy", mmap_mode="r")
    a = numpy.ascontiguousarray(x[i : i + t, j : j + t])
    del a
    print(process.memory_info().rss - mem)
```
This adds significant overhead (~300ms per tile) but keeps memory footprint steady.

Closing the issue then, thanks again !
