### ISSUE TITLE
Modify image data, keeping everything else (metadata) intact

### ISSUE THREAD

**Issue by aljosahafner** [cgohlke/tifffile#237]
Hey,

How would it be possible to edit just the TIFF image data, keeping all the other metadata intact. I am working with some "rich" tiff files, modifying the image with some calculations. However, resaving the image causes the final file to be incompatible with programs further down the processing pipeline.

Maybe this could be achieved using the ```TiffFile``` object? I am just writing what I'd like to achieve:
```
import tifffile
with tifffile.TiffFile('image.tif') as f:
    f.imageArray = newImageArray
```

Thanks in advance and sorry if this is not the right place to ask for support.

Aljosa

**Comment by cgohlke** [comment]
Tifffile directly supports in-place modification of image data only when the image data is [memory-mappable](https://github.com/cgohlke/tifffile/blob/5ced58caa74936ecc53f58ade94938e251e83138/tifffile/tifffile.py#L566-L586) or can be [mapped to a Zarr array](https://github.com/cgohlke/tifffile/blob/5ced58caa74936ecc53f58ade94938e251e83138/tifffile/tifffile.py#L755-L760). That excludes use of compression and filters.
