### ISSUE TITLE
question: is this package dependent on Libtiff?

### ISSUE THREAD

**Issue by haixpham** [cgohlke/tifffile#240]
Hello,

I have been using Pillow and OpenCV to process TIF files at large scale. However, they are both based on LibTiff, and there are memory leak problems with it, so the program often crashes after processing a few hundred thousands of images.

Is Tifffile written from ground up or is it still dependent on LibTiff?

Thanks
Hai

**Comment by cgohlke** [comment]
Tifffile does not depend on libtiff. Tifffile is a Python library that depends on `numpy` and optionally `imagecodecs` for some compression schemes. The library was made to handle the pesky TIFF-like formats used in bio-imaging. It may not be suited as a replacement for libtiff for your use case. It may be better to report the memory leak to the [libtiff developers](https://gitlab.com/libtiff/libtiff) and push for a fix.
