### ISSUE TITLE
saving a imagej hyperstack with a single channel removes the channel number form the tiff metadata

### ISSUE THREAD

**Issue by kingbedjed** [cgohlke/tifffile#241]
I am attempting to save an array of shape (11, 1, 3120, 4096, 3) to an imagej formatted tiff. I use the axes labels TCYXS. When I run `tiffinfo` on the saved tiff image I only see the following metadata:
```
TIFF Directory at offset 0x8 (8)
  Image Width: 4096 Image Length: 3120
  Resolution: 1, 1 (unitless)
  Bits/Sample: 8
  Compression Scheme: None
  Photometric Interpretation: RGB color
  Orientation: row 0 lhs, col 0 bottom
  Samples/Pixel: 3
  Rows/Strip: 3120
  Planar Configuration: single image plane
  ImageDescription: ImageJ=1.11a
images=11
frames=11
hyperstack=true
loop=false
```

I also see that there is blocked code in `tifffile.py` with the comment ` TODO: do not squeeze data when writing OME or ImageJ files (breaking)` which seems like it could be related to this issue. 

Is preserving single dimensions when saving to imagej supported in tifffile in anyway? If not is it something that could be added? Or are there any suggested work arounds? We would like to maintain the single channel dimensions for information to the rest of the pipeline when loading the tiff in.

Thanks!

**Comment by cgohlke** [comment]
See #19, #66, and #155. The ImageJ format does not preserve size-one dimensions. The workaround is to read with `squeeze=False` but that may be removed again in a future version.
