### ISSUE TITLE
Create svs file with image pyramid, label and macro in tifffile?

### ISSUE THREAD

**Issue by tuttelikz** [cgohlke/tifffile#243]
How write/create .svs image and add associated images, label and macro? (preferably openslide-friendly) Is it possible in tifffile?

**Comment by cgohlke** [comment]
There is no high level support for writing SVS files in tifffile. Try the [wsic.SVSWriter](https://github.com/John-P/wsic/blob/632955cd9886777fb65e0a2b8dd921a03527e521/wsic/writers.py#L786), which is based on tifffile.

**Comment by gustavo-alberto** [comment]
@tuttelikz do you want to create in Aperio's format? I was facing the same problem, but after reading the TIF 6.0 documentation and the Openslide Aperio's specification, I found a way to write multiples IFD's (Pages) in a TIF file.
For Openslide recognize a label and macro inside a file, these IFD's (label and macro page) must have some specific description written in ImageDescription Tag.

So, assuming that all your images are in TIF format:

1. Open the baseline image and other images (label, macro, etc)
`baseline_image= tifffile.imread(path)`
`thumbnail_image= tifffile.imread(path)`
`macro_image= tifffile.imread(path)`
`label_image= tifffile.imread(path)`
2. Open/create the final file that you want:
` with tifffile.TiffWriter(output_file_name) as tif:`
3. Write the baseline image (The image at full resolution. The baseline image must be the first image (IFD) in file . This is a specification from TIF standard.)
`tif.write(baseline_image, tile=tile_size, resolutionunit='CENTIMETER') # Baseline image`
4. Now, write the other images. subfiletype parameter is a kind of low level value written in tif file to inform that is a subimage.
```
tif.write(.thumbnail_image, subfiletype=1) # Thumbnail image
tif.write(macro_image, subfiletype=1) # Macro image
tif.write(label_image, subfiletype=1) # Label image
```
5. Now, open that file in TiffFile mode and write specific string in ImageDescription tags
```
with tifffile.TiffFile(output_file_name, mode='r+b') as tif:
 _ = tif.pages[0].tags['ImageDescription'].overwrite('Aperio') # page 0 is baseline image
 _ = tif.pages[1].tags['ImageDescription'].overwrite('Aperio \nthumbnail') # page 1 is thumbnail image
 _ = tif.pages[2].tags['ImageDescription'].overwrite('Aperio \nmacro') # page 2 is macro image
 _ = tif.pages[3].tags['ImageDescription'].overwrite('Aperio \nlabel') # page 3 is label image
```

Your final script should be like this 

```
import tifffile

baseline_image= tifffile.imread(baseline_image_path)
thumbnail_image= tifffile.imread(thumbnail_image_path)
macro_image= tifffile.imread(macro_image_path)
label_image= tifffile.imread(label_image_path)

with tifffile.TiffWriter(output_file_name) as tif:
	tif.write(baseline_image, tile = tile_size, resolutionunit='CENTIMETER') # Baseline image. The tile parameter convert the baseline image to be tiled
	tif.write(.thumbnail_image, subfiletype=1) # Thumbnail image
	tif.write(macro_image, subfiletype=1) # Macro image
	tif.write(label_image, subfiletype=1) # Label image

with tifffile.TiffFile(output_file_name, mode='r+b') as tif:
 _ = tif.pages[0].tags['ImageDescription'].overwrite('Aperio') # page 0 is baseline image
 _ = tif.pages[1].tags['ImageDescription'].overwrite('Aperio \nthumbnail') # page 1 is thumbnail image
 _ = tif.pages[2].tags['ImageDescription'].overwrite('Aperio \nmacro') # page 2 is macro image
 _ = tif.pages[3].tags['ImageDescription'].overwrite('Aperio \nlabel') # page 3 is label image
```

With this, I was able to read some properties, including the label and macro, with openslide.
