### ISSUE TITLE
NumPy 2.0 support

### ISSUE THREAD

**Issue by jakirkham** [cgohlke/tifffile#252]
NumPy 2.0 is coming out soon ( https://github.com/numpy/numpy/issues/24300 ). NumPy 2.0.0rc1 packages for conda & wheels came out 3 weeks back ( https://github.com/numpy/numpy/issues/24300#issuecomment-2030603395 )

To prepare for NumPy 2.0, it might be worthwhile to start testing against NumPy 2 in CI

NumPy has put out [a migration guide]( https://numpy.org/devdocs/numpy_2_0_migration_guide.html#numpy-2-migration-guide ). More details are in [the release notes]( https://numpy.org/devdocs/release/2.0.0-notes.html )

Also as NumPy is tracking ecosystem support for NumPy 2.0, it would be helpful to share tifffile current support status in issue (with any plans): https://github.com/numpy/numpy/issues/26191

**Comment by cgohlke** [comment]
Fixed in tifffile-2024.4.24

**Comment by jakirkham** [comment]
Thanks Christoph! 🙏
