### ISSUE TITLE
add a spot color channel 

### ISSUE THREAD

**Issue by lyzhiyuan** [cgohlke/tifffile#256]
I intend to add a spot color channel to a TIFF image and have discovered the tifffile library. Could you advise if it supports my requirement?

**Comment by cgohlke** [comment]
I don't think spot colors are supported by the TIFF specification. You could save a TIFF with `photometric='SEPARATED'` and the extra spot channels in unspecified extra samples `extrasamples=['UNSPECIFIED', ...]`. According to [this](https://forums.aurigma.com/yaf_postst6454_HOWTO-Save-spot-color-channel-in-TIFF-image.aspx) Photoshop stores the colors of the extra samples in the `DISPLAY_INFO` resource block of the `ImageResources` TIFF tag value. The `ImageResources` structure, but not the `DISPLAY_INFO` structure, can be created with the [psdtags](https://github.com/cgohlke/psdtags) library. I do not have any more information.
