### ISSUE TITLE
Edit tags

### ISSUE THREAD

**Issue by gamis** [cgohlke/tifffile#26]
Hi!

Your library is awesome. I have a question. How can I edit tiff tags in a multi-page tiff file? 

Thanks!

**Comment by cgohlke** [comment]
Editing TIFF tags in existing TIFF files is out of the scope of the library. 

But the `TiffFile`, `TiffPage`, and `TiffTag` classes provide all the information (offsets, formats) about TIFF files to patch/rewrite specific parts of a file using standard Python file handling and struct module. This approach has been used to anonymize SVS medical images for example. It requires good knowledge of the TIFF format though.

Maybe other libraries such as [tifftools](https://github.com/DigitalSlideArchive/tifftools) provide higher level functions to edit TIFF files?

**Comment by gamis** [comment]
Thanks!

**Comment by cgohlke** [comment]
tifffile >= 2020.11.26 can overwrite values of existing tags, e.g. XResolution of the first page:

```Python
with TiffFile('temp.tif', mode='r+b') as tif:
    tif.pages[0].tags['XResolution'].overwrite(tif, (96000, 1000))
```

**Comment by gamis** [comment]
Nice! I'll have to try it out!
