### ISSUE TITLE
metadata={'axes': 'TZCYX'} when not all can be loaded into memory Can you read a small portion of the specified dimension in a tif of type metadata={'axes': 'TZCYX'},when it can't be loaded all the way into memory?

### ISSUE THREAD

**Issue by 464hee** [cgohlke/tifffile#263]
```
Write a 5-dimensional floating-point array using BigTIFF format, separate color components, 
tiling, Zlib compression level 8, horizontal differencing predictor, and additional metadata:

>>> data = numpy.random.rand(2, 5, 3, 301, 219).astype('float32')
>>> imwrite(
...     'temp.tif',
...     data,
...     bigtiff=True,
...     photometric='rgb',
...     planarconfig='separate',
...     tile=(32, 32),
...     compression='zlib',
...     compressionargs={'level': 8},
...     predictor=True,
...     metadata={'axes': 'TZCYX'},
... )
```
Suppose, for example, I now download a sample data( 'TZCYX') from somewhere else
As the example shows, when shape = (200, 500, 30, 3010, 2190)
I can't load a tif from memory at this time, can I support reading the data of ( 500, 30, 3010, 2190) in which T=1.

**Comment by cgohlke** [comment]
> I can't load a tif from memory at this time, can I support reading the data of ( 500, 30, 3010, 2190) in which T=1.

Use the zarr interface, similar to this example:

https://github.com/cgohlke/tifffile/blob/7230baf84200203c7d3f50f46324093cd71013fb/tifffile/tifffile.py#L712-L723

**Comment by 464hee** [comment]
OK, Thanks for the reply.
