### ISSUE TITLE
Support for installing specific extras

### ISSUE THREAD

**Issue by sammaxwellxyz** [cgohlke/tifffile#264]
Hey, thanks for the package.

At the moment the extras are installed together under the 'all' extra

https://github.com/cgohlke/tifffile/blob/a73812e98f58b068a590de862ed547820fd332ad/setup.py#L89-L97

could they be broken out so that one could install just the codecs, or codecs and xml for example?

e.g. `tifffile[codecs]` or `tifffile[codecs,xml]`

cheers

**Comment by cgohlke** [comment]
OK. The next version will have `codecs`, `xml`, `zarr`, `plot`, and `all` entries .
