### ISSUE TITLE
Reading BigTIFF metadata only

### ISSUE THREAD

**Issue by daniel-ji** [cgohlke/tifffile#267]
Hi,

Thanks for creating this package, has been very helpful! This may be a relatively stupid question, but is there any way to read the metadata for every `TiffPage` in a `TiffFile` without having to load in the actual data? 

```python
with tifffile.TiffFile(f) as tif:
    return [page.shape for page in tif.pages]
```

This seems to retrieving the entire TIFF file for me. I was wondering if I was on the right line and I can definitely share more details on my issue if this is how it's supposed to be done. 

Thank you!

**Comment by cgohlke** [comment]
Your code reads all pages (IFD structures) and select tag values from the TIFF file. It does not read or decode any image data.

**Comment by daniel-ji** [comment]
I see, really appreciate the help and quick response! I'll take deeper dive into why it's taking so long and I'll re-open this issue if I have any questions, if that's okay. Thank you!

**Comment by daniel-ji** [comment]
Hi, 

Thanks again for helping.

so my code is using `tifffile` as follows:

```
with s3fs.open(frame_file, "rb") as f:
    with tifffile.TiffFile(f) as tif:
        return tif.pages
``` 

which is done for about ~50 tiff files, each about 50 MB, 2.5GB total. 

And this results (monitored crudely with `iftop`) in a 500MB overall download (so 10MB from each file) from aws, taking about ~13s. Which might already be some unintended / interesting behavior. There are 10 TiffPages per BigTIFF file. 

And then when the code is changed to:

```
with s3fs.open(frame_file, "rb") as f:
    with tifffile.TiffFile(f) as tif:
        return [page for page in tif.pages]
``` 

It now is reading all 2.5GB, taking ~65s. 

And I don't believe this is an s3fs issue, because when the code is just:

```
with s3fs.open(frame_file, "rb") as f:
    print(f)
    return None
``` 

It is reading <1 MB, taking < 1s. 

However, with this: 
```
with s3fs.open(frame_file, "rb") as f:
    with tifffile.TiffFile(f) as tif:
        return None
``` 

It goes back to reading 500MB, 13s. 

If you'd like, I can send over the file. Thank you!

**Comment by cgohlke** [comment]
> ```python
> with s3fs.open(frame_file, "rb") as f:
>     with tifffile.TiffFile(f) as tif:
>         return tif.pages
> ```

This only reads the first page and select tag values from the TIFF file. The structure of the first page is usually located at the beginning of the file but in your case it's after the image data of the first page.

> ```python
> with s3fs.open(frame_file, "rb") as f:
>     with tifffile.TiffFile(f) as tif:
>         return [page for page in tif.pages]
> ```

This reads all pages and select tag values from the TIFF file, parsing the IFD chain until the end. The page structures and tag values are usually distributed all over the file, which results in a lot of seeks and cache misses.

> ```python
> with s3fs.open(frame_file, "rb") as f:
>     print(f)
>     return None
> ```

This does not read anything from the file.

> However, with this:
> 
> ```python
> with s3fs.open(frame_file, "rb") as f:
>     with tifffile.TiffFile(f) as tif:
>         return None
> ```

This reads the first page and select tag values from file.

> And I don't believe this is an s3fs issue...

What is the block size of s3/s3fs? It could be around 5 MB from what you describe. You need to read at least the first block to identify the TIFF header, and another block to parse the first page structure plus tag values. For each additional page, you need to read at least one additional block from S3. 

TIFF, by default, is not very cloud friendly. The cloud optimized GeoTIFF format (COG) avoids these issues by storing all page structures and tag values at the beginning of the file, before the image data. 

Also consider creating fsspec/[kerchunk](https://fsspec.github.io/kerchunk/) ReferenceFileSystem files for your TIFF files.

**Comment by daniel-ji** [comment]
I see, thank you so much for the help!!
