### ISSUE TITLE
IO[bytes] instead of BinaryIO

### ISSUE THREAD

**Issue by rharkes** [cgohlke/tifffile#268]
In the situation where you open a tiff file directly from a .zip file the python zipfile returns a `IO[bytes]` object.
It works perfectly fine with tifffile, but mypy complains `Argument 1 to "TiffFile" has incompatible type "IO[bytes]"; expected "str | PathLike[Any] | FileHandle | BinaryIO"  [arg-type]`.

Would it be possible to either add `IO[bytes]` or maybe replace `BinaryIO` with `IO[bytes]`?

**Comment by cgohlke** [comment]
This will be fixed in the next release. 

I think `BinaryIO`  supports writing `bytearray`s. But that's not used here and MyPy doesn't complain when replacing `BinaryIO` with `IO[bytes]`...
