### ISSUE TITLE
Clarity on geotiff_metadata

### ISSUE THREAD

**Issue by KipCrossing** [cgohlke/tifffile#27]
Hey,

I was just wondering if I could get some clarity on *ModelPixelScale* and *ModelTiepoint*.

```python
    tif = TiffFile(input_file)
    print(tif.geotiff_metadata['ModelPixelScale'])
    # [5.01483146067815e-05, 5.0153046594992315e-05, 0.0]
    print(tif.geotiff_metadata['ModelTiepoint'])
    # [0.0, 0.0, 0.0, 137.9049898, -30.9165658, 0.0]
```

Now I assume *ModelPixelScale* returns `[x,y,z]` but using gdals `GetGeoTransform()` the `y` should be a negative. ie: `-5.0153046594992315e-05`. That's no big deal though, I just thought Id mention it for consistency.

Not sure the order/contents of the  *ModelTiepoint*. Any ideas? Something like: `[?, ?, ?, lat, lon, ?]`

**Comment by KipCrossing** [comment]
btw, the output  of `GetGeoTransform()` is like:

```python
ds = gdal.Open(f, gdal.GA_ReadOnly)
print(ds.GetGeoTransform())
# (137.9049898, 5.01483146067815e-05, 0.0, -30.9165658, 0.0, -5.0153046594992315e-05)
```
ie:

`(lat, xScale, rtnX, lon, yScale, rtnY)`

**Comment by cgohlke** [comment]
The `geotiff_metadata` function just consolidates the values of the various GeoTIFF tags in a single dictionary. The values are not changed from what is in the file. The meaning of the values is defined in the GeoTIFF specification. The coordinate transformations are defined at http://geotiff.maptools.org/spec/geotiff2.6.html. The specification also defines a homogeneous transformation matrix from the ModelTiepoint and ModelPixelScale values and explains that "the -Sy is due the reversal of direction from J increasing- down in raster space to Y increasing-up in model space." There's a comment in the tifffile code that shows how to calculate the ModelTransformation matrix from ModelPixelScale and ModelTiepoint:

https://github.com/cgohlke/tifffile/blob/f206e4af068d12dfc1db500a4d9d0808bf4ca14f/tifffile/tifffile.py#L6454-L6467

**Comment by KipCrossing** [comment]
Thanks for taking the time to explain this, I really appreciate it. And that's a great little script.

Keep up the good work!
