### ISSUE TITLE
A probable mismatch with Zarr package

### ISSUE THREAD

**Issue by MosheHersh** [cgohlke/tifffile#272]
Error when trying to open a ZarrTiffStore instance (that was returned from `store = tifffile.imread(path, aszarr=True)` with `zarr_array = zarr.open(store,mode='r')`

 

> zarr_array = zarr.open(store, mode='r')
> 
>   File ~\PycharmProjects\DNAalyzer\venv\Lib\site-packages\zarr\_compat.py:43 in inner_f
>     return f(*args, **kwargs)
> 
>   File ~\PycharmProjects\DNAalyzer\venv\Lib\site-packages\zarr\api\synchronous.py:77 in open
>     obj = sync(
> 
>   File ~\PycharmProjects\DNAalyzer\venv\Lib\site-packages\zarr\core\sync.py:91 in sync
>     raise return_result
> 
>   File ~\PycharmProjects\DNAalyzer\venv\Lib\site-packages\zarr\core\sync.py:50 in _runner
>     return await coro
> 
>   File ~\PycharmProjects\DNAalyzer\venv\Lib\site-packages\zarr\api\asynchronous.py:228 in open
>     store_path = await make_store_path(store, mode=mode, storage_options=storage_options)
> 
>   File ~\PycharmProjects\DNAalyzer\venv\Lib\site-packages\zarr\store\common.py:120 in make_store_path
>     raise TypeError(msg)
> 
>  TypeError: Unsupported type for store_like: 'ZarrTiffStore'_
> 

any suggestions for solution?

To be noted that the same code was working fine before a ~month (the error has began since a full reinstallation of the enviroment due to a bad OS update).

thanks alot.

**Comment by cgohlke** [comment]
You are using a pre-release of Zarr 3. Tifffile requires zarr 2. It is not compatible with zarr 3.
