### ISSUE TITLE
Fast way to get the number of frames in a scanimage tiff stack

### ISSUE THREAD

**Issue by neuromantic99** [cgohlke/tifffile#276]
Hi,

Thanks a lot for all your work with this tool. 

I'm looking to read the number of frames in a scanimage tseries. I know that I can use:
```python 
tiff = tifffile.TiffFile(tiff_path)
n_frames = len(tiff.pages)
````

But this is very slow in my hands (on the order of a minute for a large tiff). Is there a faster way of doing this, e.g. by just reading the metadata without iterating through pages? The number of frames does not seem to appear in `tiff.scanimage_metadata`

Thanks again!

**Comment by cgohlke** [comment]
AFAIK, that is not possible with files written by newer ScanImage. For TIFF files written by ScanImage <= 2015, tifffile can [avoid parsing most TIFF structures](https://github.com/cgohlke/tifffile/blob/8a25a0d4738390af0a1f693705f29875d88fc320/tifffile/tifffile.py#L10826-L10879). For the new, BigTIFF based ScanImage format that is no longer possible (unless the format changed again?).

Try [scanimage-tiff-reader](https://pypi.org/project/scanimage-tiff-reader/), by the makers of ScanImage, which is specifically optimized for ScanImage files and uses faster, OS specific functions to read from files.
