### ISSUE TITLE
Write BigTIFF as XYZ instead of TXY

### ISSUE THREAD

**Issue by chourroutm** [cgohlke/tifffile#277]
I am using a code to write a large matrix as XYZ / ZYX from either dask or numpy but I get a TXY volume when I open it with either Fiji or Napari.

Code:

```python
import tifffile as tiff
import numpy as np

dataset_crop = np.random.randint(0,255,(14107, 15767, 32),dtype=np.uint8)
print(dataset_crop.shape)
data_path = "data_cropped.tif"
tiff.imwrite(data_path,dataset_crop.transpose((2,1,0)),metadata={'axes': 'ZYX'})
print('Downloaded data to', data_path)
```

Info from Fiji:

>  BitsPerPixel	8
>  DimensionOrder	XYCZT
>  IsInterleaved	false
>  IsRGB	false
>  LittleEndian	true
>  PixelType	uint8
>  Series 0 Name	data
>  SizeC	1
>  SizeT	32
>  SizeX	14107
>  SizeY	15767
>  SizeZ	1
> BitsPerSample	8
> Compression	Uncompressed
> ImageLength	15767
> ImageWidth	14107
> Location	--
> MetaDataPhotometricInterpretation	Monochrome
> MetaMorph	no
> NumberOfChannels	1
> PhotometricInterpretation	BlackIsZero
> ResolutionUnit	None
> SamplesPerPixel	1
> Software	tifffile.py
> XResolution	1.0
> YResolution	1.0

Other software such as Dragonfly or 3D Slicer can read it correctly.

**Comment by cgohlke** [comment]
Specify `imagej=True` or `ome=True` to write a format/metadata that ImageJ/Bio-Formats support.
