### ISSUE TITLE
How to force decoding an EXIF tag's value as another tag structure

### ISSUE THREAD

**Issue by marsfan** [cgohlke/tifffile#278]
I'm working on decoding a CR2 file (which is just a tiff file with some extra tags and a few tweaks) in it. So far, I've been fairly successful, but I'm hitting a wall because I need to extract some data from the camera's makernote, which is embedded within the EXIF tag

I know for a fact that on my camera, the makernote is just another level of tags, just like how the ExifData is a level of tags with the page's tags (but the data does not come right after the header, making the offsets even more important), but the tifffile library is not decoding it as such, instead just returning the bytes from it. Is there a way to tell the library that I want it to look into the `MakerNote` tag, and parse the data within it as well (even if it requires me modifying the library myself and having a custom version)? I don't really care about getting the tag names at the momet, as I can work with just the tag numbers. 

Example: 

```python3
with tifffile.TiffFile("Low_Quality/IMG_2478.CR2") as tif:
    makernote = tif.pages[0].tags["ExifTag"].value["MakerNote"]
    print(makernote)
```
prints a large byte array `b'\'\x00\x01.....`

but I'd like to be able to access the elements of the makernote, for example as such:
```python3
with tifffile.TiffFile("Low_Quality/IMG_2478.CR2") as tif:
    FIRMWARE_TAG = 0x07
    makernote = tif.pages[0].tags["ExifTag"].value["MakerNote"]
    print(makernote[FIRMWARE_TAG])
```
should print out `"Firmware Version 1.2.0"` (The firmware version tag within the makernote is a string for Canon cameras)

**Comment by cgohlke** [comment]
Tifffile doesn't know much about EXIF tags. Better use a dedicated EXIF reader library.

If that is not an option, try to use the private `read_tags` function (not recommended):
```Python
import tifffile
from tifffile.tifffile import TIFF, TiffTagRegistry, read_tags

filename = 'Canon - EOS M6 - RAW (3 2).cr2'

with tifffile.TiffFile(filename) as tif:
    makernote_value = tif.pages[0].tags['ExifTag'].value['MakerNote']
    tif.filehandle.seek(0)
    makernote_offset = tif.filehandle.read().find(makernote_value)
    tif.filehandle.seek(makernote_offset)
    makernote_tags = read_tags(
        tif.filehandle,
        tif.tiff.byteorder,
        tif.tiff.offsetsize,
        TiffTagRegistry({}),
    )[0]
    print(makernote_tags['7'])

```

**Comment by marsfan** [comment]
@ cgohlke 
I was trying that before, but using a smaller BytesIO object of just the makernote. The example you have provided looks like it might work better for me, I did not realize I could manipulate the `TiffFile` Object's pointer directly. I'll try that and report back.

**Comment by marsfan** [comment]
@cgohlke Good news! That seems to have worked as needed. Interacting with the actual `TiffFile` object did the trick, so the offsets are now valid. 

One small change I made is storing the original byte position with `orig_seek = tif.filehandle.tell()` at the start, and restoring that at the end with `tif.filehandle.seek(orig_seek)`, just in case.  

I might look into seeing how I might be able to add support for that to the library itself, so others will be able to parse this data as well.

**Comment by cgohlke** [comment]
> using a smaller BytesIO object of just the makernote

That won't work. The offsets in TIFF/EXIF tags are absolute (relative to the beginning of the TIFF file). Also, currently EXIF tags are only parsed for codes and values, such that there is no direct way to get the offset of a EXIF tag value through tifffile. The workaround to get the offset by searching for the value in the file is an ugly hack.

**Comment by cgohlke** [comment]
> add support for that to the library itself

The proper way to implement this would be a public `read_tags` function that return a (Sequence of) `TiffTags` objects instead of dicts of tag codes and values.
