### ISSUE TITLE
Write single image series in append mode

### ISSUE THREAD

**Issue by alejoe91** [cgohlke/tifffile#28]
Hi @cgohlke 

Thanks for the awesome package :)

I'm trying to write chunks of a video to tiff using the append mode (`append=True`). When I load the tiff file I get the right number of pages, but if I try to memmap it I only get one chunk at a time. In fact, each `imsave` call appends a new series to the tiff file.
Is it possible to write in append mode and extend the existing series, so that in the end I can memmap the entire video?

Minimal example:

```
import numpy as np
import tifffile

save_path = 'test_append.tif'

# create 1000 frmes, 50x50 image size
video = np.random.randn(1000, 50, 50)

# write 100 frames at a time:
len_chunk = 100
for i in range(10):
     tifffile.imsave(save_path, video[i * len_chunk:(i+1) * len_chunk], append=True)

tif = tifffile.TiffFile(save_path)
print(len(tif.pages)) # correctly prints 10000
tif.close()

video0 = tifffile.memmap(save_path, series=0)
print(video0.shape) # prints (100, 50, 50)

video1 = tifffile.memmap(save_path, series=1)
print(video1.shape) # prints (100, 50, 50)
```

**Comment by cgohlke** [comment]
If the number of frames is unknown before, the only way to achieve that is to write frame by frame to an open TiffWriter instance in contiguous mode:
```Python
with TiffWriter('video.tif') as tif:
    for frame in video:
        tif.save(frame, contiguous=True)
```

**Comment by alejoe91** [comment]
@cgohlke thanks for the quick reply! 

I actually know the total number of frames. In this case, is it possible to write chunks of frames at once to the same series (not frame by frame)?

**Comment by cgohlke** [comment]
> I actually know the total number of frames. In this case, is it possible to write chunks of frames at once to the same series (not frame by frame)?

If you don't need the tifffile metadata, try:
```Python
with TiffWriter('video.tif') as tif:
    for chunk_of_frames in video:
        tif.save(chunk_of_frames, contiguous=True, metadata=None)
```

Otherwise provide a generator of frames (not tested): 
```Python
def frames():
    for chunk_of_frames in video:
        for frame in chunk_of_frames:
            yield frame

imwrite('video.tif', frames(), shape=video.shape, dtype=video.dtype)
```

**Comment by alejoe91** [comment]
Thanks! I'll try these solutions and let you know :)

**Comment by alejoe91** [comment]
The first solution did the trick :)

Thanks!
