### ISSUE TITLE
reading tiff stacks 

### ISSUE THREAD

**Issue by shaojus** [cgohlke/tifffile#30]
I am using tifffile as a plugin in the scikit-image io module, and for some reason when I read tif stacks, it only reads the first layer. Not sure what the issues is as it works with other plugins like pil. Ex. 
```
from skimage import io
im = io.imread('an_image.tif')
```

**Comment by cgohlke** [comment]
There is probably some metadata in the file that specifies "the first layer" as a series. Tifffile by default scans common metadata to detect series of pages that belong together and returns the first such series.

**Comment by shaojus** [comment]
I used io.imsave(file, append=True) to generate the tif stacks. Could this be the problem?

**Comment by cgohlke** [comment]
By default tifffile.imwrite writes a new "series" to the file. You may want to turn off metadata creation using the argument `metadata=False` to get a plain "tif stack".
