### ISSUE TITLE
Bug with user submitted descriptions

### ISSUE THREAD

**Issue by davideboschetto** [cgohlke/tifffile#31]
Hi there,

I have a problem with the TiffWriter.write() function.
I'm providing the write function a custom description (tag 270).
This results with the tags list having two descriptions (two items with value 270), one with the description I want and one with the shape+metadata (not provided by me).

Since two tags with 270 value exist, they both are removed from this:
`            if pageindex == 0:
                tags = [tag for tag in tags if not tag[-1]]`

, and we end up with no description among tags.

I think this is not the wanted behaviour of the function, right?

I ended up temporarily solving this problem by commenting all the code regarding "write shape and metadata to ImageDescription" (line 1838) to "del description" (line 1895).

**Comment by cgohlke** [comment]
I can't reproduce this. The following code gives the expected results for me.

```Python
import tifffile

tifffile.imwrite(
    'test.tif',
    [[0]],
    extratags=[(270, 's', None, 'My description', False)],
    # metadata=None  # do not write an ImageDescription tag with shape info
)
```

**Comment by davideboschetto** [comment]
`tifffile.imwrite(
    'test.tif',
    [[0]],
    description='My description'
)`
If i remember correctly (not at a PC right now), this should not write the description.

**Comment by cgohlke** [comment]
> `description='My description'`

That description will be "saved with the first page of a contiguous series only" along with a second ImageDescription tag describing the shape of the input data. Use `metadata=None` if you don't want the second ImageDescription tag.
