### ISSUE TITLE
How to write GPSTags via tifffile.TiffWriter.write()?

### ISSUE THREAD

**Issue by LukasBommes** [cgohlke/tifffile#33]
Dear Mr Gohlke,

first of all, thanks for providing and maintaining this very helpful tool. 
I attempt to write a bunch of individual TIFF files into a multipage TIFF using tifffile.TiffWriter.write() as shown below. this works well. However, I can not figure out how to "transplant" the meta tags from the individual TIFF files into the according page in the output TIFF stack. You can see below that I read the meta tags and then attempt to manually reassemble it in the "extratags" argument. This does not yield the desired output.

Do you know, how I could copy the meta tags of the individual TIFF (ideally all, not only the GPSTags) into the output TIFF stack most easily and flexibly?

Your help would be gladly appreciated!

`
image_files = sorted(glob.glob("radiometric/*"))

with tifffile.TiffWriter("out.tif", bigtiff=True) as tif:
    for i, image_file in enumerate(image_files):
        if i == 10:
            break
        
        # get GPS meta tag
        with tifffile.TiffFile(image_file) as file:
            gps_info = file.pages[0].tags["GPSTag"].value
            
        meta = {k: v for k, v in gps_info.items() if k != 'GPSVersionID'}
        print(meta)
        
        img = tifffile.imread(image_file)
        tif.write(img, compression="ZSTD", extratags=[(34853, 's', 1, 'N', False),
                                                      (34853+1, 's', 2, gps_info['GPSLatitudeRef'], False),
                                                      (34853+2, '2i', 3, gps_info['GPSLatitude'], False),
                                                     ])
`

EDIT:

This are the tags which end up in the output TIFF stack.

read_tags: corrupted tag list at offset 78
read_tags: corrupted tag list at offset 78
TiffTag 256 ImageWidth @848268 1I @848280  640
TiffTag 257 ImageLength @848288 1I @848300  512
TiffTag 258 BitsPerSample @848308 1H @848320  16
TiffTag 259 Compression @848328 1H @848340  ZSTD
TiffTag 262 PhotometricInterpretation @848348 1H @848360  MINISBLACK
TiffTag 270 ImageDescription @848368 22s @848616  {"shape": [512, 640]}
TiffTag 273 StripOffsets @848388 11Q @848702  (848880, 888675, 931301, 975444,
TiffTag 277 SamplesPerPixel @848408 1H @848420  1
TiffTag 278 RowsPerStrip @848428 1I @848440  51
TiffTag 279 StripByteCounts @848448 11I @848790  (39795, 42626, 44143, 42165, 4
TiffTag 282 XResolution @848468 2I @848480  (1, 1)
TiffTag 283 YResolution @848488 2I @848500  (1, 1)
TiffTag 296 ResolutionUnit @848508 1H @848520  NONE
TiffTag 305 Software @848528 12s @848834  tifffile.py
TiffTag 34853 GPSTag|OlympusSIS2 @848548 2s @78  ()
TiffTag 34854 @848568 2s @848580  N
TiffTag 34855 ISOSpeedRatings @848588 6i @848846  (49, 1, 36, 1, 20727, 500)

**Comment by cgohlke** [comment]
This is a duplicate of issue #1.

Writing EXIF or GPS tags is not supported and out of the scope of this library:

https://github.com/cgohlke/tifffile/blob/26ce449b6251bbe4c6cd8af7e5b9cc2f2dd28599/tifffile/tifffile.py#L905-L907

What you could try is writing the GPS IFD to the GPSTag verbatim and later patch the absolute offsets in the GPS IFD manually.

It's probably easier to try other libraries such as [tifftools](https://github.com/DigitalSlideArchive/tifftools).

**Comment by LukasBommes** [comment]
Thanks a lot for the reply and sorry for overlooking this paragraph in the documentation. I will take a look at tifftools.

**Comment by dbuscombe-usgs** [comment]
@LukasBommes did you ever get tifftools working for this issue? I'm running into the same issue again and again. There doesnt seem to be a simple python library that will read and write tiffs, and create both metadata tags and exif data

I spent a while looking at tifftools and couldn't see how it could work with writing an arbitrary numpy array with exif and metdata as arrays or dictionaries (or JSON or whatever)
