### ISSUE TITLE
Exception when writing contiguous OME-TIFF

### ISSUE THREAD

**Issue by gmazzamuto** [cgohlke/tifffile#36]
Please consider this minimal example, taken from the documentation ("Successively write the frames of one contiguous series to a TIFF file"), which works as expected:
```py
data = numpyp.random.randint(0, 255, (30, 301, 219), 'uint8')
with TiffWriter('temp.tif', bigtiff=True) as tif:
    for frame in data:
        tif.write(frame, contiguous=True)
```
This is the same identical example, with the only difference that I'm saving to a `.ome.tif`:
```py
data = numpyp.random.randint(0, 255, (30, 301, 219), 'uint8')
with TiffWriter('temp.ome.tif', bigtiff=True) as tif:
    for frame in data:
        tif.write(frame, contiguous=True)
```
Unfortunately this does not work and throws a `ValueError: shape does not match stored shape`.

**Comment by cgohlke** [comment]
That is expected. Contiguous mode does not work with OME or ImageJ formats because the shape of the data must be known when writing the first frame. I will update the documentation.

**Comment by gmazzamuto** [comment]
Thanks for your reply. In my particular case, I do know the shape of the final data from the very beginning. Is there a way to pass the metadata and the final shape so that it is written in the first frame? or, equivalently, to write the metadata at the end, after all the frames have been written.

Thanks a lot.

**Comment by cgohlke** [comment]
There is no public API to patch the ImageDescription tag of the first page. It should be relatively easy to write an utility function that patches the ImageDescription tag of an existing file. Alternatively try to use Bio-Format's [`tiffcomment`](https://docs.openmicroscopy.org/bio-formats/6.5.1/users/comlinetools/edit.html) tool.

**Comment by cgohlke** [comment]
This should work in v2020.11.26:
```Python
import numpy
from tifffile import TiffWriter, OmeXml

data = numpy.random.randint(0, 255, (30, 301, 219), 'uint8')

with TiffWriter('temp.ome.tif', bigtiff=True) as tif:
    # successively write image data to TIFF pages
    # disable tifffile from writing any metadata
    # add empty ImageDescription tag to first page
    for i, frame in enumerate(data):
        tif.write(frame, metadata=None, description=None if i else b'')
    # update ImageDescription tag with custom OME-XML
    xml = OmeXml()
    xml.addimage('uint8', (22, 301, 219), (22, 1, 1, 301, 219, 1), axes='ZYX')
    xml.addimage('uint8', (8, 301, 219), (8, 1, 1, 301, 219, 1), axes='CYX')
    tif.overwrite_description(xml.tostring())
```

**Comment by gmazzamuto** [comment]
Seems very convenient, thank you!

**Comment by gmazzamuto** [comment]
I've tried your solution and indeed it works, I just wanted to add that it seems to work even when writing the whole array in one go instead of writing it one frame at a time:

```py
import numpy
from tifffile import TiffWriter, OmeXml

data = numpy.random.randint(0, 255, (10, 301, 219, 3), 'uint8')

with TiffWriter('temp.ome.tif', bigtiff=True) as tif:
    tif.write(data)
    xml = OmeXml()
    metadata = {
        'Channel': [
            {'ExcitationWavelength': 500},
            {'ExcitationWavelength': 550},
            {'ExcitationWavelength': 600},
        ],
    }
    xml.addimage('uint8', (10, 301, 219, 3), (10, 1, 1, 301, 219, 3), axes='ZYXS', **metadata)
    tif.overwrite_description(xml.tostring())
    print(xml.tostring())
```

However I am noticing an inconsistency: the code above produces the following ome xml string where `SizeC="3"` but only the first channel property is populated. I guess it should either be `SizeC="1"` or it should populate all the three properties (I'd very much prefer the latter). Should I open a new issue or am I missing something? Thanks a lot
```xml
<Image ID="Image:0" Name="Image0">
    <Pixels ID="Pixels:0" DimensionOrder="XYCZT" Type="uint8" SizeX="219" SizeY="301" SizeC="3" SizeZ="10" 
                SizeT="1" Interleaved="true">
    <Channel ID="Channel:0:0" SamplesPerPixel="3" ExcitationWavelength="500"><LightPath/></Channel>
    <TiffData IFD="0" PlaneCount="10"/>
   </Pixels>
</Image>
```

**Comment by cgohlke** [comment]
I'm not sure the OME model supports that case. You'll have to store the channels as separate pages, not RGB samples. I.e. rearrange your data to have a shape of  `(10, 3, 301, 219)`, `axes='ZCYX'` and `photometric='minisblack'`.
