### ISSUE TITLE
micromanager_metadata['Time']

### ISSUE THREAD

**Issue by TomPJWyatt** [cgohlke/tifffile#39]
Hello,

For an image file created by micromanager, should the time that the image was created be in the metadata somewhere?

I recently updated tifffile from an old version and I thought previously it was something like (although maybe I'm mistaken):

```
with tifffile.TiffFile(tifpath) as tif:
    time = tif.micromanager_metadata['Time']
```

Many thanks in advance for your help,
Tom

**Comment by cgohlke** [comment]
Hello. Since tifffile v2020.8.25, `TiffFile.micromanager_metadata` only returns the MicroManager non-TIFF metadata. `Time` is found in the `MicroManagerMetadata` tag of each page:
```Python
import tifffile

with TiffFile('MicroManager.tif') as tif:
    for page in tif.pages:
        print(page.tags['MicroManagerMetadata'].value['Time'])
```

**Comment by TomPJWyatt** [comment]
ah I see, thank you for the help. (and sorry for the trivial question)
