### ISSUE TITLE
Merge several z-stacks from several files into one file

### ISSUE THREAD

**Issue by hsiaoyi0504** [cgohlke/tifffile#40]
Hi there, I am new here.
I have several tiff files which are named as `PECCU_A23_T0001F001L01A03Z*C01.tif`.
That is, there are several files like `PECCU_A23_T0001F001L01A03Z01C01.tif`, `PECCU_A23_T0001F001L01A03Z02C01.tif`, `PECCU_A23_T0001F001L01A03Z03C01.tif` ... till `PECCU_A23_T0001F001L01A03Z81C01.tif`.

What will be the best way to merge them together as a single tiff file.
Originally, I thought I could do something like this:

```
import numpy as np
import tifffile

stack_1 = '/nfs/turbo/umms-jzsexton/VirtualStaining/BRO0117014VirtStain-20X_20201111_163715/PECCU/PECCU_A23_T0001F001L01A03Z80C01.tif'
stack_2 = '/nfs/turbo/umms-jzsexton/VirtualStaining/BRO0117014VirtStain-20X_20201111_163715/PECCU/PECCU_A23_T0001F001L01A03Z81C01.tif'

img = tifffile.imread(stack_1)
img = np.expand_dims(img, axis=0)
img2 = tifffile.imread(stack_2)
img2 = np.expand_dims(img2, axis=0)
img_merged = np.concatenate([img, img2], axis=0)
tifffile.imwrite('./temp.tif', img_merged, photometric='minisblack')

img3 = tifffile.imread('./temp.tif')
print(img3.shape)
```

However, it seems to me that this will consume lots of memory. I am thinking if it's possible to write to a file in an unsynchronized way. Thank you.

**Comment by cgohlke** [comment]
If you don't need to preserve metadata, use:
```Python
import glob
import tifffile

with tifffile.TiffWriter('temp.tif') as tif:
    for fname in glob.glob('*.tif'):
        img = tifffile.imread(fname)
        tif.write(img, metadata=None, photometric='minisblack')
        del img
```

**Comment by hsiaoyi0504** [comment]
Thanks @cgohlke . It works like a charm.
