### ISSUE TITLE
Why tifffile package only load 5 series rather than 9 series as openslide does?

### ISSUE THREAD

**Issue by Yuvi-416** [cgohlke/tifffile#41]
Hello there,
When I load an NDPI image with an Openslide package, it shows there are 9 different image dimensions but when I try to load the same image with tifffile package, it just loads 0, 2, 4, 6, 8 series (not 1, 3, 5, 7). Why is that? How to solve this problem?
![1](https://user-images.githubusercontent.com/65744819/100947730-23175000-34fe-11eb-9160-a6a2bec7bbfb.PNG)

As you can see in the above picture, Image_dimension has 9 dimensions from 40x to 0.125x, but I open the same image with the below code, it just loads even series, not an odd one.
Code:
with tifffile.imread(input_1, aszarr=True) as store:
    group = zarr.open(store, mode='a')
    assert isinstance(group, zarr.Group)
    for r in group.keys():
        stack = group[r]
        assert stack.ndim == 4  # ZYXC
        for z in range(stack.shape[0]):
            zstack = z
And one more question, how can I pass the input in a tiles format. so that I don't have a memory problem
Thank you

**Comment by cgohlke** [comment]
Please share the file. I assume it is the same file you referred to at <https://forum.image.sc/t/how-to-twitch-python-bioformats-code-so-that-it-will-show-all-dimensions-like-openslide-do/45950/6> but I cannot access it.

**Comment by Yuvi-416** [comment]
Thanks for the quick reply.
Yeah, it's the same file.
Here, the file:
https://uapt33090-my.sharepoint.com/:u:/g/personal/ygupta_ua_pt/EUELGq1xuQ5Eu3jewAB04NkBevZmgdbkoVtviuzbQOxwTw?e=4YmKvq

**Comment by cgohlke** [comment]
Thank you. The file does only contain 5 levels, consisting of 11 TIFF pages/IFDs each. It is my understanding that OpenSlide "synthesizes" missing power of two levels by partially decoding the JPEG streams of larger levels.
