### ISSUE TITLE
Write a geotiff

### ISSUE THREAD

**Issue by francoisremi** [cgohlke/tifffile#42]
Hi,

First, thank you for this fantastic Python Library which is very useful to me.

I am trying to write a geotiff with the same geo-metadata than another file.
Here is my code which duplicates tags of a geotiff file and create another one :

```python
from tifffile import TiffFile, imwrite

path='geofile.tiff'
new_path='new_geofile.tiff'

tiff = TiffFile(path)

extratags = []

# for each tag, append to extratags
for _, tag in tiff.pages[0].tags.items():
    extratags.append((tag.code, tag.dtype, tag.count, tag.value, False))

# create the new geotiff
imwrite(new_path, data=tiff.asarray(), extratags=extratags)
```

Unfortunatly, the result is unexpected : the returned map is partly shifted as illustrated above.

![shift](https://wtf.roflcopter.fr/pics/UB8XqQn4/y1ZHPO52.png)

Is my method to copy geo-metadata wrong ? Is there a better way to do it ?

Thanks !

**Comment by cgohlke** [comment]
Passing all tags as extratags like that won't work:

* there will be many duplicate tags written to the output file, e.g. for ImageWidth.
* tifffile will not validate or use extratags, e.g. to determine how the image data is stored in the output file.
* hence some of the extratags might corrupt the file, e.g. a TileWidth tag in a file that does not use tiling.
* some TiffTag.value are parsed into Python objects on reading. They cannot simply be rewritten to the output file.
* some tag values might be, or contain, file offsets. They will be pointing to wrong places in the output file.

Try to limit extatags to the GeoTIFF tags, e.g.:

```Python
from tifffile import TiffWriter, TiffFile

with TiffFile('geotiff.tif') as tif:
    with TiffWriter('geotiff_copy.tif') as out:
        for page in tif.pages:
            im = tif.asarray()
            extratags = []
            for code in (
                33920,
                33550,
                34264,
                33922,
                50844,
                34735,
                34736,
                34737,
            ):
                tag = page.tags[code]
                extratags.append((code, tag.dtype, tag.count, tag.value))
            out.write(
                im,
                photometric=page.photometric,
                extratags=extratags,
                metadata=None,
            )
```

If that doesn't work, please share your specific file or better use a GeoTIFF aware library such as GDAL or rasterio.

**Comment by francoisremi** [comment]
Thanks a lot for your quick answer, it works !
I will have a look at rasterio which is indeed specific for GeoTiff.

**Comment by gsakkis** [comment]
@cgohlke has there been any update since then that allows getting only the extra tags from a TiffPage, in case it is not desirable or possible to hardcode them (as the GeoTIFF tags in this example)? See also [this issue](https://github.com/TileDB-Inc/TileDB-BioImaging/pull/53).

**Comment by cgohlke** [comment]
I am thinking to filter `extratags` such that no duplicate tag codes are written (maybe with the exception of `ImageDescription`) and also filter tags that are set by tifffile (e.g. `StripOffsets`). That will reduce the chances of writing corrupted TIFF files. Would that help you?

A main limitation for preserving general tags is the inability to write `ExifIFD` metadata, or any tags with an IFD code.

**Comment by gsakkis** [comment]
> That will reduce the chances of writing corrupted TIFF files. Would that help you?

I am not familiar enough with the tiff internals to tell why even that wouldn't be foolproof enough but it would be an improvement so yes, I think it would help. Thanks!
