### ISSUE TITLE
Create new (big) tiff tile by tile?

### ISSUE THREAD

**Issue by catweis** [cgohlke/tifffile#43]
Hello,
Is there an option to create a new tiff or ometiff and fill it tile-wise? The section covering creating a new image by tiles looks like the entire image needs to be in the workspace?
The background is that I want to process a whole slide image and create a heatmap of the same size.
Maybe, I just have not found the option yet.
With kind regards.

**Comment by cgohlke** [comment]
I assume you are referring to the following example? The data array does not need to be a numpy array in memory. It could be a memory mapped array on disk or a zarr array, or the tiles could be loaded on demand from a database, etc. The only requirements is that the tile generator function returns enough tiles as numpy arrays of specified tile size and dtype.

https://github.com/cgohlke/tifffile/blob/025b5e0e0046a4dd0990852fe423c262f5338d72/tifffile/tifffile.py#L518-L526

**Comment by catweis** [comment]
Thank you very much for your fast answer. Now generating new images works for me.
