### ISSUE TITLE
aszarr feature not supported?

### ISSUE THREAD

**Issue by KipCrossing** [cgohlke/tifffile#45]
From one of the examples in the README:

```python
>>> import zarr
>>> store = imread('temp.ome.tif', aszarr=True)
>>> z = zarr.open(store, mode='r')
>>> z
<zarr.hierarchy.Group '/' read-only>
>>> z[0]  # base layer
<zarr.core.Array '/0' (1024, 1024, 3) uint8 read-only>
>>> store.close()
```

got:

```bash
Traceback (most recent call last):
  File "/home/kipling/Programs/fsm-python/big_tiff.py", line 66, in <module>
    store = imread(mytif_file, aszarr=True)
  File "/home/kipling/.local/lib/python3.8/site-packages/tifffile/tifffile.py", line 716, in imread
    return tif.asarray(**kwargs)
TypeError: asarray() got an unexpected keyword argument 'aszarr'
```

Is this feature not supported anymore or is there something that I'm missing?

**Comment by cgohlke** [comment]
Looks like you are using an outdated version of tifffile. Zarr support was first added in v2020.9.22 but it's best to use the latest version.

**Comment by KipCrossing** [comment]
That's it! Thanks!

**Comment by KipCrossing** [comment]
Wow @cgohlke, its so fast! I was going to iterate over the segments and make a hackey solution but this is 10X better. 

Also, if you end up doing a readthedocs.org, let me know and I'll try help out. I've started watching this repo so I can get updates.

**Comment by KipCrossing** [comment]
Well, it seems good for large GeoTiff files based on the few tests I have done. 

Segment shape for my largest tif was `(1, 128, 128, 1)` Either way, It's a lot faster then what i was doing before; filtering the data using Apache spark RDD's. This way, I only have to get the bounding box and filter from a much smaller dataset in spark. 

I wanted to test one of the larger files from [here](https://ecat.ga.gov.au/geonetwork/srv/eng/catalog.search#/metadata/89644) but couldn't extract it because my local hard drive was too small...
