### ISSUE TITLE
Writing direction for creating ome.tif?

### ISSUE THREAD

**Issue by catweis** [cgohlke/tifffile#47]
Hello,
at the moment I am trying to read a tiff-file tile-wise, modify it and subsequently upload it.
For the tile-generator I am using the following chunk of code (with openslide):

    #%% iterate over all tiles
    x, y = 0, 0
    count =  1
    while x < x_tiles:

        while y < y_tiles:

            new_tile = np.array(tiles.get_tile(level, (x, y)), dtype=np.uint8)

            new_tile = func_handle(new_tile)
            yield new_tile 
            y += 1
            count += 1
            print('iteration #' + str(count) + ' from n=' + str(y_tiles * x_tiles))

        y = 0
        x += 1

However, the created image is somehow shifted. The tiles are not fitting to each other.
Therefore, I wonder in which direction the file-writing is done? A nested while-loop seems not to work?
Or would it be better to use your tile-reading function? If so, how could I there choose the tile-size?

With kind regards.

**Comment by cgohlke** [comment]
I think OpenSlide uses dimension order `(width, height)` while tifffile uses `(height, width)`, which aligns with the order of how data is stored in the file and numpy conventions.
