### ISSUE TITLE
How to read photometric

### ISSUE THREAD

**Issue by horsto** [cgohlke/tifffile#48]
How can I read the `photometric` of a tif? 
At the moment I am doing: 
```
with TiffFile(tif_file) as tif:
    tif. ... 
```
I just can't seem to find a way to extract the photometric string, for example `minisblack`.

**Comment by cgohlke** [comment]
It's a property of pages/IFDs in the file, not the TIFF file:
```Python
>>> from tifffile import TiffFile
>>> tif = TiffFile('itemp.tif')
>>> tif.pages[0].photometric
<PHOTOMETRIC.MINISBLACK: 1>
>>> tif.pages[0].tags['PhotometricInterpretation'].value
<PHOTOMETRIC.MINISBLACK: 1>
>>> tif.close()
```

**Comment by horsto** [comment]
Perfect, thank you for your fast response! 
Closing this because it answered my question.
