### ISSUE TITLE
Faster method to find number of images in file?

### ISSUE THREAD

**Issue by TomPJWyatt** [cgohlke/tifffile#49]
Hello,

I have lots of large tiff files and some have had problems during copying so that their metadata (e.g. fluoview_metadata['Dimensions']) doesn't match how many images are actually stored in the file.  What is the fastest way to check how many images are in the file? I'm currently doing:

```python
with tifffile.TiffFile('test.tif') as tif:
    t = len(tif.pages)
```

but it seems like it has to do a lot of work that way. Is there a better way?

Many thanks in advance,
Tom

**Comment by cgohlke** [comment]
`len(tif.pages)` is the correct way to determine the number of pages/IFDs in the file (unless you are interested also in SubIFDs). TIFF pages are organized as linked lists. To get to the end of the list the whole list has to be followed.
Some TIFF files might have the number of pages stored in the metadata of the first page, but it's not part of the TIFF specification.

**Comment by TomPJWyatt** [comment]
Ok many thanks for the help
