### ISSUE TITLE
imread and imwrite different

### ISSUE THREAD

**Issue by ear-lee** [cgohlke/tifffile#5]
Forgive my bad English. when I ```img = imread(path)``` , I get ```img.shape``` like (11, 1000, 2000, 2) but expect like (11, 1000, 2000). And when I ``` img = imread(path)``` ```imwrite(img)```, the result is different from the original.

**Comment by cgohlke** [comment]
Please provide an example file. Does your file contain grayscale images with an extrasample? To re-save those images use `imwrite('img.tif', img, photometric='minisblack', planarconfig='contig')`

**Comment by ear-lee** [comment]
@cgohlke very very thankful. it solve my question.   By the way, i wanna make some ```xx.tiff``` to ```.pdf```, and do you have any library recommendations.  Thanks for your prompt reply again!!!!!
