### ISSUE TITLE
Example saving ImageJ TIFF has 57 channels instead of 57 z slices

### ISSUE THREAD

**Issue by tomgoddard** [cgohlke/tifffile#50]
In your examples you give the following for saving an ImageJ TIFF of a 3D volume.  This actually saves a 57 channel ImageJ 2D image instead of the intended 3D (57, 256, 256) map.  You would need to use shape (57, 1, 256, 256) since ImageJ uses axis order ZCYX.  Maybe there is some other way to specify 1 channel when saving ImageJ TIFF but I didn't see it in the code.

Write a volume with xyz voxel size 2.6755x2.6755x3.9474 micron^3 to an ImageJ hyperstack formatted TIFF file:
>>> volume = numpy.random.randn(57, 256, 256).astype('float32')
>>> imwrite('temp.tif', volume, imagej=True, resolution=(1./2.6755, 1./2.6755),
...         metadata={'spacing': 3.947368, 'unit': 'um', 'axes': 'ZYX'})

Thanks for the fantastic tifffile.py!  You keep the whole light microscopy field going.

**Comment by cgohlke** [comment]
The example works for me. I think you might be using an outdated version. Support for the `axes` key in `metadata` for ImageJ was added in v2020.11.26. Older versions need the data in TZCYXS order:

https://github.com/cgohlke/tifffile/blob/dd88603cea590ff08597ca7dc2c45febc19efbb5/tifffile/tifffile.py#L384-L387

**Comment by tomgoddard** [comment]
Thanks!  You are right I am using tifffile 2020.9.3. I will update.  Sorry for the false alarm!	.3.
