### ISSUE TITLE
Save file in CCITT tif format issues

### ISSUE THREAD

**Issue by sergtk** [cgohlke/tifffile#51]
Hello,

how can I save file in CCITT format?
I tried to use following constants: CCITTRLE, CCITTFAX3, CCITT_T4, CCITTFAX4, CCITT_T6

This is in the statement:

        tifffile.imwrite('tifffilename.tif', tif_data, compression="<one of the CCITTRLE, CCITTFAX3, CCITT_T4, CCITTFAX4, CCITT_T6>")
        
I was not able to get anything work.
The library `imagecodecs` installed.

Thank you

**Comment by cgohlke** [comment]
CCITT compression schemes are not implemented as documented:

https://github.com/cgohlke/tifffile/blob/025b5e0e0046a4dd0990852fe423c262f5338d72/tifffile/tifffile.py#L52-L54

Tifffile is geared more towards scientific imaging. Fax compression schemes are out of that scope but could be added to the imagecodecs package using an existing CCITT compression library with C API and BSD compatible license (I'm not aware of any).
