### ISSUE TITLE
Windows serialization behavior is different from OSX or Linux

### ISSUE THREAD

**Issue by JacksonMaxfield** [cgohlke/tifffile#57]
I will keep looking and attempting to debug on my side but just curious: did anything change / did the 2021.01.14 windows wheels / builds get in-place switched?

I have a log from last week where all of tests pass with that version on windows. [log](https://github.com/AllenCellModeling/aicsimageio/runs/1739537041)
And I have a log from today where windows (all python versions) fail due to a very specific `TIFF.DATATYPES` serialization error. [log](https://github.com/AllenCellModeling/aicsimageio/pull/185/checks?check_run_id=1755651600)

From those logs I can confirm that they are:
* both using `windows-latest` as the CI env
* both installed `tifffile==2021.1.14`
* nothing changed in the tests (except minor renaming of variables)

**Comment by cgohlke** [comment]
> did anything change / did the 2021.01.14 windows wheels / builds get in-place switched?

No. There's a MemoryError during pickle. Maybe the tests are running out of memory?

**Comment by JacksonMaxfield** [comment]
Good catch! Assuming it's out of memory because the file is ~2 GB in memory. Sorry!
