### ISSUE TITLE
How to split an existing multipage TIFF in chunks?

### ISSUE THREAD

**Issue by fra-luc** [cgohlke/tifffile#58]
Hi and thanks for this great library!

I have a question: I need to split an existing TIFF file, made of several pages, into TIFF files of a fixed number of pages, say 5. I managed to do this with PIL but it's not very efficient (see the following example, which "extracts" the first five pages). I think the reason for it not being efficient is PIL needs to decode the pages content, then encode it back in order to save the file.

``` python
doc = Image.open('file.tiff')

pages = []

for i in range(5):
    doc.seek(i)
    pages.append(doc.copy())
    
pages[0].save('first_five_pages.tif, format="tiff", append_images=pages[1:], save_all=True)
```

I was wondering if you can suggest a more efficient solution using `tifffile`.
Thanks!

**Comment by cgohlke** [comment]
Tifffile doesn't support writing already compressed chunks and there are pitfalls when copying metadata manually.

Try the [tifftools](https://github.com/DigitalSlideArchive/tifftools) library, which is designed for such cases (AFAIK).

**Comment by fra-luc** [comment]
Thanks for the quick answer!
