### ISSUE TITLE
While writing ome.tif pyramid structure image, input take all ram and swap memory.

### ISSUE THREAD

**Issue by Yuvi-416** [cgohlke/tifffile#60]
I am receiving a memory error when I try to convert a bigger (like 800 MB or 2 GB) .tif image into .ome.tif image. 
I followed your code over here: https://forum.image.sc/t/tifffile-ome-tiff-generation-is-taking-too-much-ram/41865
My input: https://uapt33090-my.sharepoint.com/:f:/g/personal/ygupta_ua_pt/ElUrNh8e4CxKkTvEho80VPIB7ZusVNA7eG--XUewZ6NI-A?e=LhKeBF
Code:
```
with tifffile.imread(input_path, aszarr=True) as store:
    group = zarr.open(store, mode='r')
    assert isinstance(group, zarr.Group)
    for r in group.keys():
        stack = group[r]
        with tifffile.TiffWriter('Rectum_de_chat_HE-pyramidal.ome.tif', bigtiff=True) as tif:
            # use tiles and JPEG compression
            options = {'tile': (512, 512), 'compress': 'jpeg'}
            # save the base image
            tif.save(stack, subifds=8, **options)
            # successively generate and save pyramid levels to the 8 SubIFDs
            for _ in range(8):
                image = cv2.resize(
                    stack,
                    (stack.shape[1] // 2, stack.shape[0] // 2),
                    interpolation=cv2.INTER_LINEAR
                )
                tif.save(stack, **options)
```
Any can you give me some suggestion about it. Currently, I am getting the error on this line: `tif.save(stack, subifds=8, **options)`

**Comment by cgohlke** [comment]
The code looks flawed on several levels: overwriting the same file with pyramid levels, unnecessarily recalculating pyramid levels, wrongly calculating pyramid levels, and passing zarr arrays to functions requiring numpy arrays.

Besides that, the conversion works for me as expected, using ~20 GB peak memory. 

To save memory, use the pyramid levels from the original file and try a tile iterator as input to the `TiffWriter.write` function, similar to the example at:

https://github.com/cgohlke/tifffile/blob/75a11f2d781705a64151d3d329e47187e3be82a8/tifffile/tifffile.py#L535-L541

It would be best to avoid re-compressing JPEG compressed tiles, but that is not officially supported in tifffile.

**Comment by Yuvi-416** [comment]
Hi,
Thanks for your suggestion. I was able to write a pyramid structure image.
Now, I am having trouble while inserting original metadata into it.
Can you tell me how can I insert previously written metadata to newly created ome.tif file.

Currently i am passing bellow line:
```
Metadata_tif = tifffile.TiffFile(input_path, multifile=True, is_ome=True)
xml_metadata = Metadata_tif.pages.keyframe.tags

tif.write(tiles(stack, (stack.chunks[0], stack.chunks[1])), shape=stack.shape,
                      dtype=stack.dtype, metadata={'xml_metadata': 'xml_metadata'}, **options)
```
But when I open this newly created image into ImageJ. It shows nothing beside bellow:
![Screenshot from 2021-01-27 19-33-35](https://user-images.githubusercontent.com/65744819/106043677-ac01d080-60d6-11eb-87ba-fc71c3f4ac35.png)
How can I put all original tags into it?

**Comment by Yuvi-416** [comment]
Sry it was the fault of the ImageJ.
Everything is fine.
Once again thank you for your suggestion.
