### ISSUE TITLE
Cannot read 32 bit TIFF from Pilatus detector

### ISSUE THREAD

**Issue by asteppke** [cgohlke/tifffile#61]
When trying to read a TIFF file obtained with a Pilatus detector using the following example code:

````python
import tifffile as t

with t.TiffFile('pilatus.tif') as tif:
    print(tif.is_pilatus)
    data = tif.asarray()
    print(data)
    print(max(data.flatten()))
    
````
The output for the file does not correspond to its contents (which contain several non-zero values):

````
True
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
0
````

Am I doing something wrong here or do I need to provide `tifffile` with more information about the input data? This occurs with the current version '2021.1.14'. (Example file: https://www.dropbox.com/s/m1sifq9y4lu2pjg/pilatus.tif?dl=0)

**Comment by cgohlke** [comment]
AFAICT tifffile returns the correct image data, in agreement with other TIFF readers (ImageJ, libtiff). Btw, the image data are `int16` not 32-bit.

**Comment by asteppke** [comment]
Thank you for looking into this. 

I found a manual from the Pilatus people and it clearly states (from the [manual](http://www.esrf.eu/files/live/sites/www/files/UsersAndScience/Experiments/MX/New_Web_Files/Beamlines/Hardware_components/Detectors/User_Manual-PILATUS2-V1_4.pdf)): 

> Due to the high dynamic range of 20 bits (1’048’576) of the PILATUS
detectors, images are stored as 32 bit (signed) integers. These images can
be viewed and analyzed with TVX or other image viewers. Many viewers do
not support 32 bit TIFF files.

As a workaround in numpy 

```python
with open(filepath, 'rb') as f:
    f.seek(4096)
    a = np.fromfile(f, dtype=np.int32)
```
returns the correct values but then all metadata is lost (size, dimensions, etc.). 

It seems that the information in the TIFF header that the data is recorded as `int16` is not correct. Tifffile recognizes all other metadata correctly though.

**Comment by cgohlke** [comment]
> `f.seek(4096)`

Where does that offset come from? In the file you sent the data starts at `StripOffsets=8` and is `LZW` compressed. Either the file is corrupt or the image data are hidden from TIFF readers.

**Comment by asteppke** [comment]
The offset was suggested from the manual as an alternative way:

> The TIF header is of a fixed length of 4096 bytes, so it is possible to make a
file reader by stripping off the header and reading the row-major block of data.

It is implied in the manual that this is a valid TIFF file and only certain readers do not support all the features. If the metadata is completely misleading, that is indicating `int16`, `LZW` compression and a wrong start of the image data this is a bit messy. I have no knowledge to judge whether this is a legal TIFF file or if they took a lot of liberty when implementing their version.

**Comment by cgohlke** [comment]
I only have a few Pilatus test files. Tifffile can read all of them correctly as `int32`. The image data start at offset 4096 only in some file, which is OK.

I think you should contact the maker of the software used to record the files and ask for clarification.

**Comment by asteppke** [comment]
Thank you for digging into this so quickly. Fully agree, if the information in the header is not correct any bets at parsing this are off. 

I will contact the manufacturer and will report back what they reply.
