### ISSUE TITLE
Parallelisation issue with tifffile import order

### ISSUE THREAD

**Issue by edwardando** [cgohlke/tifffile#63]
Let me excuse myself in advance, but this is going to be an obscure bug report.
I'm one of the [spam](https://pypi.org/project/spam/) co-developers, and we're working on profiling our parallel image correlation code.
We use `tifffile` since a long time happily, but there's a very strange bug we're seeing that we would like help with.

In both `mpi4py` or `multiprocessing` parallelisation (shared or not shared memory) we have an approximately 2x slowdown if we `import tifffile` *before* our `import spam.DIC.correlate`. Yes, just that.
The reason for the slowness seems to be an extraordinary amount of system time which we think is possibly due to memory copies?

Have you seen this issue before?
It's persistent over a number of version of `tifffile` we tried from 2018.11.6 to the latest version.
We're not doing anything fancy with `tifffile`, just two `tifffile.imread()` of 3D tiff files and then running computations on subsections with some C code which is bound to our python.
Incredibly this slowdown is still present when we `import tifffile` first but use `numpy.load` to load previously-saved 3D files (*i.e.*, never actually calling `tifffile` but importing it first).

Any clue would be helpful, since we started to think one of our scripts was cursed, until we reduced the difference to this surprising import order.

**Comment by edwardando** [comment]
Hmm, it seems to be related to your `import numpy` so the problem is not here, sorry.
It remains very strange, more news soon.

**Comment by cgohlke** [comment]
I can't reproduce this issue. It is also unclear what exactly is profiled/timed.

Look out for monkey patching or setting environment variables used in your code or dependencies. E.g. OpenMP, OpenBLAS, and MKL can be tuned by environment variables; numpy.fft might be replaced with faster versions. Tifffile doesn't do any of this.

**Comment by cgohlke** [comment]
Looks like this might be due to spam's usage of [`OPENBLAS_NUM_THREADS`](https://gricad-gitlab.univ-grenoble-alpes.fr/ttk/spam/-/blob/master/tools/__init__.py).

See also https://github.com/numpy/numpy/issues/11826 and https://github.com/joblib/threadpoolctl

**Comment by edwardando** [comment]
Yes that it!!! You're right, openblas is going parallel again in the threads due to import order and slowing things down overall.
Thanks very much for the hint!
