### ISSUE TITLE
eer format, avoid warning.

### ISSUE THREAD

**Issue by pconesa** [cgohlke/tifffile#68]
Hi! First, congratulations for this package. It seems flexible and very useful.

There is a new file format in the Cryo electron microscopy called eer. Is a Bigtiff file with some, at least specific compression.

I've tried this library and it gets the pages and size properly and wants about the COMPRESSION:

`TiffTag 259: 65001 is not a valid COMPRESSION`

For me, so far, I'm ok with this behaviour, do not actually need to read the images but know its dimensions.

Is there a way to avoid the warning?

I see this could be the right package to read these files. What would be the procedure in case you agree to read eer?

**Comment by cgohlke** [comment]
Hi,

for reference: the EER file format is described at https://github.com/fei-company/EerReaderLib and http://dx.doi.org/10.1107/S205225252000929X.

The library is GPL licensed. Hence the decompression code cannot be integrated into tifffile/imagecodecs. I'll check if the codec can be implemented independently, e.g. from a specification or publication.

It is probably a good idea to silence the warning for unknown compressions.

Could you share a file for testing?

**Comment by pconesa** [comment]
I asked this in their repo recently: https://github.com/fei-company/EerReaderLib/issues/1

The only one I see in this folder is here:
https://fei-box.app.box.com/s/3enc37s3nnfdh558ovysxus8bcyrc8t4/folder/117486307754 (ending with .eer)

In EMPIAR (public repository for electron microscopy data) there are a few entries:
ftp://ftp.ebi.ac.uk/empiar/world_availability/10612
ftp://ftp.ebi.ac.uk/empiar/world_availability/10568

Th

**Comment by pconesa** [comment]
I've managed to silence it with:

       # eer format (In case we want to cancel the warning)
        import logging
        tifffileLogger = logging.getLogger("tifffile.tifffile")
        tifffileLogger.disabled = True

A bit hacky, but works.

**Comment by cgohlke** [comment]
Thank you. The next version of tifffile will silence the warning and detect EER files. But it won't be able to decode the image data.

**Comment by cgohlke** [comment]
Partially fixed in v2021.3.5.

**Comment by pconesa** [comment]
Many thanks for the fast reaction!

Which licence will allow the addition of the compression code to tifffile/imagecodecs?

There is a chance they can change the license. At least I'll ask them.
