### ISSUE TITLE
Would like to know little bit insight why one image size is increased and other one decreased?

### ISSUE THREAD

**Issue by Yuvi-416** [cgohlke/tifffile#69]
Hello there,
I have downloaded two .tiff images from cytomine website:
1. https://cytomine.com/collection/hsm0170/400-human-ileons (it's a huge image 158 GB ) 
2. https://cytomine.com/collection/uliege001/cat-rectum (size 847 Mb)
After that, I converted them into ome.tiff using the below code (bcoz bioformat was unable to read these image resolution layers). 

```
def tiles(stack, tileshape):
    for y in range(0, stack.shape[0], tileshape[0]):
        for x in range(0, stack.shape[1], tileshape[1]):
            yield stack[y: y + tileshape[0], x: x + tileshape[1]]


with tifffile.imread(input_path, aszarr=True) as store:
    group = zarr.open(store, mode='a')
    assert isinstance(group, zarr.Group)
    with tifffile.TiffWriter(output_path + f'HSM0170.ome..tiff', bigtiff=True) as tiff:
        start_time = timeit.default_timer()
        for r in group.keys():
            stack = group[r]
            width = stack.shape[0]
            length = stack.shape[1]
            # assert stack.ndim == 3  # YXC
            a = tiles(stack, (stack.chunks[0], stack.chunks[1]))

            options = {'tile': (stack.chunks[0], stack.chunks[1]), 'compression': 'JPEG'}
            tiff.write(tiles(stack, (stack.chunks[0], stack.chunks[1])), shape=stack.shape,
                       dtype=stack.dtype, **options)
    end_time = timeit.default_timer()
    total_time = float(end_time - start_time)
    print(total_time)
```
It got converted and I receive generated image first image size was increased to 247.2 GB and the second image size was decreased to 713.5 MB.
I want to know a little bit of insight detail why the first image size is increased and the second image size is decreased while applying the same code. Which parameter is crucial while converting, is it jpeg quality?

**Comment by cgohlke** [comment]
`HSM0170-20x20.tiff` was compressed at 70%. You are re-compressing at 90%. The other image doesn't specify the compression level used. There can also be significant differences in the software/library used for JPEG compression.

Your code doesn't create a pyramidal OME-TIFF. OME-TIFF expects a file ending `ome.tif` and subresolutions in subifds:

https://github.com/cgohlke/tifffile/blob/0b6a4355225c750262838558eaab51a5f4614540/tifffile/tifffile.py#L579-L589

**Comment by Yuvi-416** [comment]
Thanks for your reply, 
I tried to implement the above example but I am getting some error related to subifds.
code:
```
with tifffile.imread(input_path, aszarr=True) as store:
    group = zarr.open(store, mode='a')
    assert isinstance(group, zarr.Group)
    with tifffile.TiffWriter(output_path + f'Rectum_1.ome.tif', bigtiff=True) as tif:
        start_time = timeit.default_timer()
        for r in group.keys():
            stack = group[r]
            width = stack.shape[0]
            length = stack.shape[1]
            options = {'tile': (stack.chunks[0], stack.chunks[1]), 'subifds': r, 'subfiletype': 1,
                       'compression': 'JPEG'}
            tif.write(tiles(stack, (stack.chunks[0], stack.chunks[1])), shape=stack.shape,
                      dtype=stack.dtype, **options)
    end_time = timeit.default_timer()
    total_time = float(end_time - start_time)
    print(total_time)
```
Error:
```
Traceback (most recent call last):
  File "/home/yuvi/PycharmProjects/task-1/temp/Code_to_convert_images_into_ome_tif.py", line 38, in <module>
    dtype=stack.dtype, **options)
  File "/home/yuvi/anaconda3/envs/task-1/lib/python3.7/site-packages/tifffile/tifffile.py", line 1474, in write
    'SubIFDs in SubIFDs are not supported'
ValueError: SubIFDs in SubIFDs are not supported

Process finished with exit code 1
```
I could not find much help with it. As far as I understood Subifds are required for multi-resolution and in my case, every **for r** is a new resolution so why I do get the above error when I run the above code as:
**options = {'tile': (stack.chunks[0], stack.chunks[1]), 'subifds': r, 'subfiletype': 1,  'compression': 'JPEG'}**
And, how can I have control over jpeg compression quality?

**Comment by cgohlke** [comment]
For pyramidal OME-TIFF you have to reserve subifds for all subresolutions when writing the base/first level.

This should work, although it will probably take several hours to decode and compress several terabytes of image data:

```Python
import tifffile
import zarr

input_path = 'HSM0170-20x20.tiff'
output_path = 'HSM0170.ome.tif'


def tiles(stack, tileshape):
    for y in range(0, stack.shape[0], tileshape[0]):
        for x in range(0, stack.shape[1], tileshape[1]):
            yield stack[y : y + tileshape[0], x : x + tileshape[1]]


with tifffile.Timer():

    with tifffile.imread(input_path, aszarr=True) as store:
        group = zarr.open(store, mode='r')
        assert isinstance(group, zarr.Group)

        with tifffile.TiffWriter(output_path, bigtiff=True) as tiff:
            for i, r in enumerate(group.keys()):
                stack = group[r]
                assert stack.ndim == 3  # YXC
                options = {
                    'tile': (stack.chunks[0], stack.chunks[1]),
                    'compression': ('jpeg', 70),
                }
                if i == 0:
                    options['subifds'] = len(group.keys()) - 1
                else:
                    options['subfiletype'] = 1
                tiff.write(
                    tiles(stack, (stack.chunks[0], stack.chunks[1])),
                    shape=stack.shape,
                    dtype=stack.dtype,
                    **options,
                )
```

**Comment by Yuvi-416** [comment]
Thank you
It worked.

**Comment by cgohlke** [comment]
There was another issue in the code.  You need to iterate over the the zarr groups in the correct order `for i, r in enumerate(tifffile.natural_sorted(group.keys())):`.
