### ISSUE TITLE
Depends on imagecodecs-lite on non x86 architectures

### ISSUE THREAD

**Issue by Czaki** [cgohlke/tifffile#7]
There are person who would like to use tifffile on non x86 architecture processors. 
https://github.com/Czaki/imagecodecs/issues/6#issuecomment-628907454
https://github.com/scikit-image/scikit-image/issues/4705#issuecomment-628673011

I try to fast build aarm64 wheel but it wail without proper message and I do not have access to arm64 hardware to check it locally 

https://travis-ci.com/github/Czaki/imagecodecs/builds/

So maybe best soulltion is to use imagecodecs-lite on other architectures? 

(I'm not sure why issues lands in my repository, not in your)

**Comment by cgohlke** [comment]
Tifffile can be used without imagecodecs (install with `--no-deps` option).
Imagecodecs can be build without any external C library dependencies (build with `--lite` option).
Imagecodecs-lite no longer exists.
I don't have access to non-x86 and non-Windows systems.
