### ISSUE TITLE
Bug: Using aszarr flag reshapes data incorrectly

### ISSUE THREAD

**Issue by camFoltz** [cgohlke/tifffile#70]
Hello,

After the recent update to 2021.3.4, it seems that the multi-file, multi-series fix works great.  However, it seems that when using the `aszarr=True` flag returns a zarr array with the correct dimensionality of the dataset, but with the images not in the correct order.  i.e. it will correctly return a zarr array with (6, 65, 2048, 2048) but (0, 0, :, :) will not be the correct image.

This is how the data is being loading when get this error:
```
positions = {}
with TiffFile(master_ome) as tif:
    for idx, tiffpageseries in enumerate(tif.series):
        positions[idx] = zarr.open(tiffpageseries.aszarr(), mode='r')
```

To asses this, I instead loaded each page of the tifffile in order and reshaped myself, to which the images were then in the correct order.  See this code below:
```
data = []
obj = tiff.TiffFile(master_ome)
imgs = obj.asarray(key=range(0,390))
for img in imgs:
    data.append(img)
    
data_reshape = np.reshape(data, (6,65, 2048, 2048))
```

Do you know why this is happening?  Here is the example dataset from the last issue regarding multi-file, multi-series read error [Link](https://drive.google.com/drive/folders/1_57ZflZIF9FS0IpuAK0TOlUtfv8SClgx?usp=sharing)

It is hard to distinguish between images in different channels/z-positions with this dataset, so if you would like one more suited for debugging this issue please let me know.

**Comment by cgohlke** [comment]
I can't reproduce this with the data files you shared. I don't think your test is correct. There are 4 series of 4x1201x512x512 in CZYX order each. These series are identified in the OME-XML. The results from aszarr and asarray match. Importing via Bio-Formats returns the same data AFAICT.

**Comment by camFoltz** [comment]
I found this error with a dataset from a recent experiment, but did not confirm with the example dataset as it is hard to tell if the images are out of order due to the repeating pattern.  I will create a new test dataset this week to see if the issue still persists.

**Comment by cgohlke** [comment]
OK, I'll leave this open.

**Comment by camFoltz** [comment]
Issue was solved and not related to tifffile-- closing this issue.

**Comment by cgohlke** [comment]
Thanks for following up.
