### ISSUE TITLE
Axes not written in metadata?

### ISSUE THREAD

**Issue by ggirelli** [cgohlke/tifffile#71]
Hi, when I write tiff files with `imagej=True`, the `axes` metadata is not stored in the ImageDescription field. Is that expected? How can I store the `axes` information?
```python
tf.imwrite(
    path,
    volume,
    compress=0,
    imagej=True,
    metadata={"axes": "TZCYX", "spacing": 0.2, "unit": "um"},
    software=f"vXXX",
    extratags=[(339, "i", 1, 1, False)],
    resolution=(1 / 0.13, 1 / 0.13, None),
)
```

Output with `imageJ=False`:
```
  ImageDescription: {"axes": "ZYX", "unit": "um", "spacing": 0.2, "shape": [91, 1024, 1024]}
```
Output with `imageJ=True`:
```
  ImageDescription: ImageJ=1.11a
images=31
slices=31
hyperstack=true
mode=grayscale
unit=um
spacing=0.2
```

Many thanks in advance!

**Comment by cgohlke** [comment]
The dimension order in ImageJ files is always `TZCYXS` and the `TZC` shape is stored in the `frames`, `slices`, and `channels` keys. The `axes` argument is used by tifffile to identify the dimensions in the `volume` array and map them to `frames`, `slices`, and `channels` in the ImageJ format.
