### ISSUE TITLE
Issue writing Float64 Image array

### ISSUE THREAD

**Issue by Prehani** [cgohlke/tifffile#73]
Having some issues exporting image arrays of Float64 Datatype. I'm on 2021.3.17 for Tifffile. 
Yields an output image that ImageJ cannot open. Am I missing something? 
![image](https://user-images.githubusercontent.com/20289373/112544047-92060680-8d84-11eb-80a1-6224ffe2ab5a.png)
Example: 
```
data = np.random.uniform(0, 255, (512, 512))
data.dtype
Out[18]: dtype('float64')
tifffile.imwrite('temp.tif', data)
```

**Comment by cgohlke** [comment]
ImageJ can only open uint8, uint16, and float32 TIFF images. You should be able to import the file into Fiji using the Bio-Formats plugin.
