### ISSUE TITLE
Question to overwrite or remove some pages in file

### ISSUE THREAD

**Issue by yubn** [cgohlke/tifffile#74]
Hello,

First, thanks to your library.

There is one question about way to overwrite on existed pages.
Because I want to make white or to get rid of some images(pages) to anonymize files(*.svs).
I success to overwrite "ImageDescription" in files and to read pages, but I have no idea to overwrite on existed page(image).
I tried to extract target pages to copy to temp files, I don't think it is right way.

Is there any way to access and modify images using your library ?

**Comment by cgohlke** [comment]
Hello, 

please see #53. Consider using https://github.com/pearcetm/svs-deidentifier.

**Comment by yubn** [comment]
Thanks for your quick response.
I referenced #53 and additional link, the results was successful to delete target page with index.

**Comment by fiendish** [comment]
The answer in #53 covers replacing a page, but is there a simpler way to just delete a page?

**Comment by cgohlke** [comment]
>  is there a simpler way to just delete a page?

In the context of anonymizing TIFF files, there is no simple way to just delete/erase a page (including all image and metadata it refers to) from an existing TIFF file. Even when carefully overwriting image data and tag values, and recursively removing IFD branches (exif, subifds...), TIFF tags can point to proprietary binary structures, which cannot be erased without knowing their format. For really simple cases it might work to overwrite the tag values of the page and patch the pointer of the previous page to point to the next page...

Consider https://github.com/DigitalSlideArchive/tifftools to rewrite TIFF files instead, copying only known metadata.
