### ISSUE TITLE
Support preview OJPEG image reading from Canon CR2 files

### ISSUE THREAD

**Issue by kmilos** [cgohlke/tifffile#75]
[Canon CR2 raw files are actually TIFFs](https://raw.pixls.us/getfile.php/1382/nice/Canon%20-%20EOS%20M6%20-%20RAW%20(3:2).CR2), and IFD0 is a preview image which is OJPEG encoded.

Unfortunately `tifffile` reads this IFD0 somewhat corrupted, as the OJPEG IFD0 is missing some mandatory tags like `SamplesPerPixel` and `PhotometricInterpretation`, and I guess defaults of 1 and MinIsBlack are currently assumed...

However, if I write those manually to the CR2 file using e.g. `ExifTool` (3 and YCbCr), then `tifffile` decodes the preview image just fine.

`libtiff` has implicit [fallbacks for OJPEGs](https://gitlab.com/libtiff/libtiff/-/blob/master/libtiff/tif_dirread.c#L4081), maybe not a bad idea to include something similar in `tifffile` as well?

**Comment by cgohlke** [comment]
Thank you. Good idea! It will be in the next version.

**Comment by kmilos** [comment]
Great, thanks!
