### ISSUE TITLE
tiffsequence with pattern and axesorder

### ISSUE THREAD

**Issue by dschneiderch** [cgohlke/tifffile#76]
this seems like its getting off topic from the original [thread](https://github.com/zarr-developers/zarr-python/issues/631#issuecomment-815367527) but i wanted to ask more about higher dimension arrays

> If you are interested in organizing your files into a higher dimensional zarr array, TiffSequence takes an optional regular expression pattern that matches axes and sequence indices in the file names. That can quite complicated: https://github.com/cgohlke/tifffile/blob/581d7a5d4d7784154066b9f11a0167bc08570b7c/tests/test_tifffile.py#L12686-L12729

This one works:
```
pattern = r'(.{2})-(.+)-\d{8}T\d{6}-PSII0-(\d)'
pngs = tifffile.TiffSequence('data/psII/dataset-A1-20200531/*.png', imread=imagecodecs.imread, pattern=pattern)
```

can you clarify why this doesnt work? it doesn't like the lack of the 2nd group even though that regex works too at [regex101](https://regex101.com/).

```
pattern = r'(.{2})-.+-\d{8}T\d{6}-PSII0-(\d)'
pngs = tifffile.TiffSequence('data/psII/dataset-A1-20200531/*.png', imread=imagecodecs.imread, pattern=pattern)
```

`FileSequence: failed to parse file names (axes do not match within image sequence)`

Also, based on your example I thought I could give an axes per group in the regex. is that not correct?
```
pattern = r'(.{2})-(.+)-\d{8}T\d{6}-PSII0-(\d)'
pngs = tifffile.TiffSequence('data/psII/dataset-A1-20200531/*.png', imread=imagecodecs.imread, pattern=pattern, axesorder=(2,1,0))
```
gives `IndexError: list index out of range`

my files are:
```
A1-doi-20200531T210155-PSII0-1.png
B1-doi-20200531T210155-PSII0-2.png
```

**Comment by cgohlke** [comment]
Can you explain what shape and axes you are expecting, at which indices the files should be, and where in the file name the indices are encoded? Axes labels are single letters, indices are integers.

**Comment by dschneiderch** [comment]
For every group I expected an extra dimension, even if length one.
`pattern = r'(.{2})-(.+)-\d{8}T\d{6}-PSII0-(\d)'`
would give shape (2,1,2,640,480)
sampleid = A1, B1
experiment = 'doi'
frameid = 1, 2
image dimensions are 640x480

and in this particular example, I would expect an array of NA for the case where sampleid=B1, frameid=1 and sampleid=A1, frameid=2

Sorry, I don't understand axes labels vs indices and it sounds like I'm missing something fundamental here.

**Comment by cgohlke** [comment]
Thank you. I understand now. The current implementation does not handle categories (like A1, B1) but requires indices in form of numbers or characters (which can be converted to numbers) for each dimension. You can probably work around this if your categories all have distinct characters at certain positions, e.g.:
```Python
import tifffile
import imagecodecs

pattern = r'(?P<A>[A-Z])\d-(?P<B>d)oi-\d{8}T\d{6}-PSII0-(?P<C>\d)'

with tifffile.TiffSequence(
    'dataset-A1-20200531/*.png', imread=imagecodecs.imread, pattern=pattern
) as pngs:
    print(pngs)
    print(pngs.asarray().shape)
```
Output:
```
FileSequence: files are missing. Missing data are zeroed
TiffSequence
 A1-doi-20200531T210155-PSII0-1.png
 files: 2
 shape: 2, 1, 2
 axes: ABC
(2, 1, 2, 200, 200)
```
You might be better off with a DataFrame or database than with a numpy or zarr array to handle your data. Check if similar tools like [PIMS](soft-matter.github.io/pims/) can handle categories...

**Comment by dschneiderch** [comment]
Ok, Thanks. I did not realize axes could only be individual letters. 

Thanks for the alternative suggestions. I was trying to avoid rolling my own solution and zarr seemed like a potential solution but it seems I am pushing this beyond where it is. I will check out PIMS too.

**Comment by cgohlke** [comment]
This can be done with v2021.10.10:

```Python
import tifffile
import imagecodecs

with tifffile.FileSequence(
    imagecodecs.imread,
    'dataset-A1-20200531/*.png',
    pattern=(
        r'(?P<sampleid>.{2})-'
        r'(?P<experiment>.+)-\d{8}T\d{6}-PSII0-'
        r'(?P<frameid>\d)'
    ),
    categories={'sampleid': {'A1': 0, 'B1': 1}, 'experiment': {'doi': 0}},
) as pngs:
    print(pngs)
    print(pngs.asarray().shape)
```
```
FileSequence
 A1-doi-20200531T210155-PSII0-1.png
 files: 2 (2 missing)
 shape: 2, 1, 2
 labels: sampleid, experiment, frameid
(2, 1, 2, 200, 200)
```
