### ISSUE TITLE
is it possible to save different units for xy and z ?

### ISSUE THREAD

**Issue by orena1** [cgohlke/tifffile#78]
Hi, 
When saving in imagej=True, is it possible to save different units for xy, and z?
e.g. assuming I have a video so xy will be in um but z is in ms:

```python
video = numpy.random.randn(57, 256, 256).astype('float32')
imwrite('temp.tif', video, imagej=True, resolution=(1./2.6755, 1./2.6755),
         metadata={ 'unit': 'um', 'axes':'TYS', frameinterval=?, fps=?})
```

Thanks!

**Comment by cgohlke** [comment]
It's a timeseries of grayscale images. The axes are 'TYX' and the time unit is seconds ('fps'):
```Python
import numpy
from tifffile import imwrite

video = numpy.random.randn(57, 256, 256).astype('float32')
imwrite(
    'temp.tif',
    video,
    imagej=True,
    resolution=(1.0 / 2.6755, 1.0 / 2.6755),
    metadata={'axes': 'TYX', 'fps': 32.0},
)
```

**Comment by orena1** [comment]
Thanks a lot @cgohlke, but it does not work:
```python
import numpy
from tifffile import imwrite

video = numpy.random.randn(57, 256, 256).astype('float32')
imwrite(
    'temp.tif',
    video,
    imagej=True,
    resolution=(1.0 / 2.6755, 1.0 / 2.6755),
    metadata={'axes': 'TYX', 'fps': 32.0, 'unit':'um'},
)
```

![image](https://user-images.githubusercontent.com/8983713/115963341-93fbea80-a527-11eb-8e4d-cfa2d27afdcd.png)

**Comment by cgohlke** [comment]
Try `metadata={'axes': 'TYX', 'finterval': 32}`. The frame interval field in the properties dialog maps to `finterval`, the frame rate in the Info window maps to `fps`.

**Comment by orena1** [comment]
Amazing! thanks!
Is there documentation for this? how did you manage to find this variable?

**Comment by cgohlke** [comment]
I don't think it's documented. I changed the "Frame interval" value in Fiji's Properties dialog, re-saved the file, and looked at the ImageDescription TIFF tag of the resulting file.

**Comment by orena1** [comment]
Thanks a lot!
