### ISSUE TITLE
Read a tile of the image without loading the whole file in memory.

### ISSUE THREAD

**Issue by estebvac** [cgohlke/tifffile#82]
Hi, first of all, thanks for the great library!
I have a question regarding reading a specific tile of the image without loading the whole file to memory. I have a big TIFF file with multiple pages (H, W, C), and I would like to access a specific tile of the file that does not match the file's internal chunks. 

The following pseudo code illustrate the desired behaviour : 
```python
tif = tiff.TiffFile('Stack_s0114_small.tif'):
tile = np.array(tif[0:128, 0:128, :]) # Read only this part of the image
```

**Comment by cgohlke** [comment]
Try the [zarr](https://zarr.readthedocs.io/en/stable/index.html) interface:

```Python
import numpy
import zarr
import tifffile

filename = 'stack.tif'

tifffile.imwrite(
    filename, numpy.ones(shape=(1024, 1024, 3), dtype='uint8'), tile=(64, 64)
)

with tifffile.imread(filename, aszarr=True) as store:
    za = zarr.open(store, mode='r')
    tile = za[:128, :128, :]

```

**Comment by estebvac** [comment]
Thanks for your help!, It's exactly what I was looking for.
