### ISSUE TITLE
lazy load ome-tiff scenes

### ISSUE THREAD

**Issue by bryantChhun** [cgohlke/tifffile#83]
For very large ome-tiff files, loading can take a long time.  For example, we access data this way:
```
with TiffFile(<ome-tiff-file.tif>) as tif:
    for idx, tiffpageseries in enumerate(tif.series):
        z = zarr.open(tiffpageseries.aszarr(), mode='r')
```
The problem is that any call to `TiffFile.series` will scan through the whole file structure.  Is there a way to, instead, return a generator so we can manually step through that search?

**Comment by cgohlke** [comment]
There's no high level API for that. You'll have to parse the OME-XML and TIFF structures manually.
