### ISSUE TITLE
"could not import name 'jpeg8_encode' from 'imagecodecs'" when using PyInstaller

### ISSUE THREAD

**Issue by ItayKishon-Vayyar** [cgohlke/tifffile#84]
Hi,
I have the following test code, which saves an image in two encodings (deflate & jpeg):
```python
import tifffile as tiff
import numpy as np
image = np.array(np.arange(0,1000000), dtype=np.uint8).reshape(1000,1000)
tiff.imwrite(file=r'D:\temp\test_deflate.tiff', data=image, compression='deflate')
tiff.imwrite(file=r'D:\temp\test_jpg.tiff'    , data=image, compression='jpeg')
```

It works when invoked using the python interpreter, in the standard way ('python test_jpeg.py').
However, when packaged using PyInstaller ('pyinstaller test_jpeg.py'), the _deflate_ encoding works successfully, yet the _jpeg_ encoding fails:
```
Traceback (most recent call last):
  File "test_jpeg.py", line 5, in <module>
  File "tifffile\tifffile.py", line 858, in imwrite
  File "tifffile\tifffile.py", line 2496, in write
  File "imagecodecs\imagecodecs.py", line 949, in jpeg_encode
  File "imagecodecs\imagecodecs.py", line 532, in stub_encode
imagecodecs.imagecodecs.DelayedImportError: could not import name 'jpeg8_encode' from 'imagecodecs'
[31992] Failed to execute script test_jpeg
```

I've tried following both tifffile & imagecodecs's code, but couldn't get to the source of the problem. I can only guess it has something to do with the dynamic declaration of codecs.

Thanks.

**Comment by cgohlke** [comment]
See https://github.com/cgohlke/imagecodecs/issues/11
