### ISSUE TITLE
COMPESSOR typo

### ISSUE THREAD

**Issue by GuillaumeBeaudin** [cgohlke/tifffile#85]
Hello,
There is a typo in the TIFF class. You use the word "COMPESSOR" instead of "COMP**R**ESSOR".
Thanks for the great library!
Guillaume

**Comment by cgohlke** [comment]
Thanks.

**Comment by GuillaumeBeaudin** [comment]
Thanks to you! I'm pretty sure that there is an error in the `write()` docstring for the `compression` argument. It is written to use TIFF.COMPRESSOR, but I think that it is TIFF.COMPRESSION that should be used.

**Comment by cgohlke** [comment]
> I think that it is TIFF.COMPRESSION that should be used.

Correct. I had noticed that already. The fixes will be in the next version.
