### ISSUE TITLE
Create a valid jpeg bytestream from a tile

### ISSUE THREAD

**Issue by hhoeflin** [cgohlke/tifffile#86]
Hi,

thank you very much for this library. We are using it as an openslide replacement and for us it is considerably faster!

I already saw that you gave some code on how to decode a single tile. I wanted to ask how I would go about doing something closely related.

Instead of decoding a single tile, I would like to create a jpeg from a single tile, avoiding the decoding and re-encoding. From what I have read about the jpeg format, all pieces seem to be there, and it is just a question of putting it together in the right form? Do you have some advice on how to best go about that? This could be very useful as I want to send the info to a browser.

Thanks

**Comment by cgohlke** [comment]
> I would like to create a jpeg from a single tile, avoiding the decoding and re-encoding

If I understood the question correctly, that is only possible if the tiles are already JPEG compressed. If your files don't have JPEGTables stored separately, it's as simple as reading and returning the tile bytes from file:
```Python
import numpy
import tifffile
from imagecodecs import jpeg8_decode


def tile_as_jpeg(tifpage, tileindex):
    """Return tile as JPEG without decoding."""
    assert tifpage.is_tiled
    assert tifpage.compression == tifffile.TIFF.COMPRESSION.JPEG
    assert tifpage.bitspersample == 8
    assert tifpage.samplesperpixel == 3
    assert tifpage.jpegtables is None
    assert tifpage.jpegheader is None
    number_tiles = (
        tifpage.imagelength
        // tifpage.tilelength
        * tifpage.imagewidth
        // tifpage.tilewidth
    )
    assert len(tifpage.dataoffsets) == number_tiles
    assert len(tifpage.databytecounts) == number_tiles
    assert 0 <= tileindex < number_tiles

    fh = tifpage.parent.filehandle
    fh.seek(tifpage.dataoffsets[tileindex])
    return fh.read(tifpage.databytecounts[tileindex])


tifffile.imwrite(
    'test_tiled_jpeg.tif',
    numpy.random.randint(0, 255, (1024, 1024, 3), 'uint8'),
    tile=(64, 64),
    compression='jpeg',
)

with tifffile.TiffFile('test_tiled_jpeg.tif') as tif:
    jpeg = tile_as_jpeg(tif.pages[0], 42)
    decoded = jpeg8_decode(jpeg)  # assert JPEG can be decoded
```
