### ISSUE TITLE
Different axis ordering reading .tif files

### ISSUE THREAD

**Issue by adrigrillo** [cgohlke/tifffile#87]
Hello,

I am writing this issue because I was playing with the [SpaceNet 6 dataset](https://spacenet.ai/sn6-challenge/) and I have found a strange behavior when loading the files. In this dataset we can find several types of images, saved as _geotiff_, with a varying number of channels. For example, the RGB images have 3 channels whereas the SAR or RGBNIR ones have 4 channels.

What I found is that the behavior of the library changes depending on the channels when reading the file and creating the NumPy array. Concretely, the shape of the array is the following:

- With the RGB images, with 3 channels, the shape is: `[3, 900, 900]`.
- With the SAR and RGBNIR images, with 4 channels, the shape is: `[900, 900, 4]`.

I do not understand why the order of the channels is different. I have tried using the _scikit-image_ library, and it works as intended.

I attach in the following zip an RGB and a SAR image which can be used to reproduce the problem: [example-images.zip](https://github.com/cgohlke/tifffile/files/6623039/example-images.zip)

**Comment by cgohlke** [comment]
Tifffile returns the data in the order they are stored in the file (with the exception of some JPEG compressed files). The TIFF [PlanarConfiguration](https://www.awaresystems.be/imaging/tiff/tifftags/planarconfiguration.html) tag describes two ways the components of a pixel (the Samples) can be stored. Your SAR image stores the samples contiguous (PlanarConfiguration=1). Your RGB image stores the samples in separate planes (PlanarConfiguration=2), which is not common for RGB images.
