### ISSUE TITLE
[feature] let imread accept pathlib.Path filenames  

### ISSUE THREAD

**Issue by maweigert** [cgohlke/tifffile#9]
Hi,

First, thanks so much for all the great work put into `tifffile`! 

Currently, `imread` does not accept `pathlib.Path` objects, i.e. the following fails:

```
import numpy as np 
import tempfile
from pathlib import Path
import tifffile

with tempfile.NamedTemporaryFile(suffix='.tif') as tmp:
    # save random data 
    tifffile.imsave(tmp, np.random.randint(0,255,(100,100)))

    fpath = Path(tmp.name)

    # works 
    tifffile.imread(str(fpath))

    # does not work
    tifffile.imread(fpath)
```    

I suspect it should be easy to fix this, as removing this [line](https://github.com/cgohlke/tifffile/blob/master/tifffile/tifffile.py#L622) does already fix the issue (`FileSequence` already can handle `Path` objects as indicated [here](https://github.com/cgohlke/tifffile/blob/master/tifffile/tifffile.py#L6206)).

**Comment by cgohlke** [comment]
Thank you. Should be fixed in v2020.6.3.

**Comment by maweigert** [comment]
Thanks for the super quick fix! :)

**Comment by kayleyhake** [comment]
Wow! This was awesome! Thanks for fixing this!
