### ISSUE TITLE
read_segment() in class FileHandle raises IndexError when indices is specified.

### ISSUE THREAD

**Issue by erikogabrielsson** [cgohlke/tifffile#90]
From the documentation, I expect the following code to provide the segment bytes and indexes of the segments specified in indices.
```python
from tifffile import TiffFile
with TiffFile(path_to_ndpi_file) as tif:
    page = tif.pages[0]  
    indices = [0, 1]
    segments = tif.filehandle.read_segments(page.dataoffsets, page.databytecounts, indices)
    for segment, index in segments:
        print(index)
```
However, this raises IndexError: list index out of range from line 9716:
```
   9715             segments = [
-> 9716                 (indices[i], offsets[i], bytecounts[i]) for i in range(length)
   9717             ]
```

The problem looks to be that the loops iterates range(length) instead of indices, and indicies[i] is used instead of i.

Additionally, further down in the while loops, the variable length is used, which represents the number of segments defined in dataoffset. The while loops should instead test i against the number of segments to read.

I have a fix for the above, but I cant guarantee that it will not break anything else. If you want I can make a pull request.

**Comment by cgohlke** [comment]
I think you might have misunderstood the `indices` parameter. It is not to specify which segments to read but defines where in the image the segments are positioned. This parameter is currently nowhere used in tifffile nor is it tested. To specify which segments to read, filter the `offsets` and `bytecounts` lists before passing them to the `read_segments` function, or -in your simple case- just directly read seek/read each segment from the filehandle without going through the `read_segments` function.

**Comment by erikogabrielsson** [comment]
Thanks for the quick response. Yes, I had misunderstood the indices parameter and will go back to just using the filehandler to get the segment bytes.
