### ISSUE TITLE
Tifffile.imwrite doesn't seem to write the image in correct form or there's something wrong somewhere which i couldn't understand.

### ISSUE THREAD

**Issue by Yuvi-416** [cgohlke/tifffile#91]
Hi there,
I have downloaded some .mrc electron microscope images from some public databases (Image can be downloaded from here: https://uapt33090-my.sharepoint.com/:u:/g/personal/ygupta_ua_pt/ETm5L3JOyRJLhreQiNg7f1wB-zwUDRzSgRg3J7K3Z9RvRQ?e=4SeNGh) and the downloaded image was in a stack form with float32 bit. As my requirement is to split them and save each image into .tiff form, therefore, to read them I use package mrc which can be downloaded from here (https://pypi.org/project/mrc/). 
After successfully reading the image, now I used tifffile.imwrite option to write an image and it worked very well but when I was analyzing the newly written image; like say slice number 211.tiff with original stack image slice number 211 in ImageJ. I saw image intensity is different. As an example:

![Origina_stack_Image_slice_211_VS_newly_generated_slice_211](https://user-images.githubusercontent.com/65744819/124014463-780b3e00-d9db-11eb-8844-15f5446de57b.png)

And here is the code:
```
import mrcfile
import mrc
import tifffile
import numpy as np
from PIL import Image
# import cv2
# Image.MAX_IMAGE_PIXELS = None

input1 = "/media/new_data/Electron_micro_MRC/20200312_tomo23_3DS30_man.mrc"
output = "/media/new_data/Electron_micro_MRC/output/"

# i = mrcfile.open(input1)
ii1 = mrc.imread(input1)
bf_tiles_org = ii1.data.transpose(0, 1, 2)
# print(i.data.dtype)
# print(i.data[0][0][:])
# print(i.data.shape)

for ii in range(ii1.shape[0]):
    # mrc.imsave(str(output) + f'{ii}.tiff', ii1[ii])
    tifffile.imwrite(str(output) + f'{ii}.tiff', ii1[ii], imagej=True)
    # cv2.imwrite(str(output) + f'{ii}.tiff', ii1[ii])
    # img_tiles_org = Image.fromarray(i.data[ii, :, :], 'F')
```
I tried to save each image using mrc.imsave, tifffile.imwrite, cv2.imwrite, and PIL save command but the generated image was the same in each case.
Therefore, Can you tell me why each newly generated slice intensity is different even though their pixel resolution value is the same?
And here's the generated 211.tiff image (https://uapt33090-my.sharepoint.com/:i:/g/personal/ygupta_ua_pt/EYRYZqBt8s1Fkqodvbrtf9UBAa2VY32pQP-IoE-M7Cv_sg?e=kTICdP)
Thank you!

**Comment by cgohlke** [comment]
I don't think there's anything wrong with tifffile.imwrite in this case. Apart from that the provided script does not execute as is, you are apparently visually comparing the wrong frames (ImageJ uses one-based indexing, Python zero-based) with different brightness/contrast settings.
