### ISSUE TITLE
Metadata writing with OME-TIFF files

### ISSUE THREAD

**Issue by etiennebergeron** [cgohlke/tifffile#92]
Hello,
I'm trying to convert different file types (i.e. NDPI) to OME-TIFF while preserving its metadata. Following the examples in _tifffile.py_, I read the test NDPI and write the OME-TIFF this way:

```
import tifffile

with tifffile.TiffFile('test3-TRITC_2_(560).ndpi', is_ndpi=True) as ndpi:
    ndpi_series1 = ndpi.pages[0].asarray()
    ndpi_meta = ndpi.pages[0].ndpi_tags

with tifffile.TiffWriter('test_ndpi_to_ometiff.ome.tif', bigtiff=True) as tif:
    options = dict(tile=(256, 256), photometric='rgb', compression='jpeg')
    tif.write(ndpi_series1, subifds=2, **options, metadata={'axes': 'YXS',
                                                            'Description':'Just a test OME-TIFF with NDPI data.',
                                                            'PhysicalSizeX':'1',
                                                            'PhysicalSizeXUnit':'um',
                                                            'PhysicalSizeY':'2',
                                                            'PhysicalSizeYUnit':'um',
                                                            'PhysicalSizeZ':'0.5',            # Arbitrary values
                                                            'PhysicalSizeZUnit':'um',
                                                            'Plane':{'ExposureTime':'1', 'ExposureTimeUnit':'us'}})
```

That way, I can add values to the metadata fields that figure in the documentation. But, is there a way to add specific fields? For example, I would like to add fields like 'Make', 'Model' or 'Magnification' that are in the NDPI's metadata and add the values of the `ndpi_meta` dict directly in the OME-TIFF metadata. Is it possible to do that while keeping the OME-XML format?

Thanks for your help!

**Comment by cgohlke** [comment]
Tifffile only deals with the Image/Pixels elements of the OME Model. The [OME Model](https://www.openmicroscopy.org/Schemas/Documentation/Generated/OME-2016-06/ome.html) is quite complex, with many elements and cross references, etc.  Your extra metadata probably fit best in a StructuredAnnotation element. Try to write the OME-TIFF using your code above, then read the OME-XML from the ImageDescription tag, add your metadata using an XML library or [ome-types](https://pypi.org/project/ome-types/), and finally overwrite the ImageDescription tag value in the file.

**Comment by etiennebergeron** [comment]
Perfect, I will try something in that way. Thank you for the fast reply!
