### ISSUE TITLE
Support reading dimensionless OJPEG thumbnails

### ISSUE THREAD

**Issue by kmilos** [cgohlke/tifffile#94]
Quite a few cameras embed these in a TIFF-based raw format, but sadly do not include `ImageWidth` and `ImageLength` tags for those IFDs. The offset and length of the OJPEG are there, so it could perhaps be decoded first and then dimensions figured out?

See Sony A1 sample [here](https://raw.pixls.us/data/Sony/ILCE-1/A1_full_lossless_compressed.ARW).

**Comment by cgohlke** [comment]
Thanks. I already implemented this when applying #93.

**Comment by kmilos** [comment]
Great, thanks!

**Comment by cgohlke** [comment]
Try v2021.7.30.
