### ISSUE TITLE
bug: offset & valueoffset of ndpi file are incorrect 

### ISSUE THREAD

**Issue by noobOriented** [cgohlke/tifffile#96]
https://github.com/cgohlke/tifffile/blob/master/tifffile/tifffile.py#L5707-L5722

since `data` in line 5712 is interleaved with `ext` , its index mismatches with file's offset

in this case, line 5718-5722 should be
```python
for i in range(tagno):
    tag_i_offset = tagoffset + i * 12
    tag_i_data = data[i * tag size : (i + 1) * tagsize]
    try:
        tag = TiffTag.fromfile(parent, offset=tag_i_offset, header=tag_i_data)

```

and https://github.com/cgohlke/tifffile/blob/master/tifffile/tifffile.py#L7756
should be
```python
valueoffset = offset + 8
```

it may produce incorrect `valueoffset` when `valuebytecount <= 4`

I'm not sure if the modification above is compatible with other format like BigTiff
Please check it

Regards & Wish you have a good day

**Comment by cgohlke** [comment]
Thank you. Should be fixed in v2021.8.8
