### ISSUE TITLE
io.BufferedReader left open and returned with Zarr in tifffile >= 2021.7.30

### ISSUE THREAD

**Issue by JacksonMaxfield** [cgohlke/tifffile#97]
Hey @cgohlke 

We got some CI failures last week about build failures. Nothing had changed on our part, and when looking at the log, the only tests failing were our serialization and deserialization tests for TIFFs. [Logs](https://github.com/AllenCellModeling/aicsimageio/runs/3283363547?check_suite_focus=true)

I tested a bunch of the `tifffile` releases and it seems this bug started with the `2021.7.30` release.

We are constructing our `TiffReader` in `aicsimageio` using the `aszarr` functionality and pass to dask delayed with `from_zarr` ([see here for impl](https://github.com/AllenCellModeling/aicsimageio/blob/main/aicsimageio/readers/tiff_reader.py#L157)). But it seems somewhere along the way, a file handle is left open / the produced zarr keeps hold of the file handle?

I looked through the `2021.7.2 -> 2021.7.30` and don't see anything immediately obvious. Any ideas?
[GitHub 2021.7.2 -> 2021.7.30 Comparison](https://github.com/cgohlke/tifffile/compare/v2021.7.2...v2021.7.30)

**Comment by cgohlke** [comment]
The zarr stores returned by tifffile need to be closed after use (to close any open file handles), either explicitly with the close method or by using a context manager. But that did not change recently. The only significant change in 2021.7.30 is that all TiffTag instances keep a reference to the TiffFile instance they belong to. Did you try to run the tests with `python -X dev`?

**Comment by JacksonMaxfield** [comment]
It may be related to `TiffTag` stuff. As we do use those as well.

We run the tests with `pytest aicsimageio/tests/`

**Comment by cgohlke** [comment]
I don't see where the zarr store is closed at https://github.com/AllenCellModeling/aicsimageio/blob/main/aicsimageio/readers/tiff_reader.py#L157-L171

**Comment by cgohlke** [comment]
Does this work?
```Python
with fs.open(path) as open_resource:
    with imread(
        open_resource, aszarr=True, series=scene, level=0, chunkmode="page"
    ) as store:
        arr = da.from_zarr(store)
        arr = arr.transpose(transpose_indices)
        return arr[retrieve_indices].compute(scheduler="synchronous")
```

**Comment by JacksonMaxfield** [comment]
It was the `TiffTags` holding onto a file handle reference. Got a fix. Thanks for the help.
